### ISSUE TITLE
HMR with Remix 

### ISSUE THREAD

**Issue by DavoCg** [chakra-ui/panda#1021]
### Description

When I update a recipe or a token used in panda config everything is rebuild accordingly **except** the css file. In order to see effective changes, I need to restart remix dev server.

On the other hand, if I update a css property in any page or component, everything is rebuilt including the css file.

### Link to Reproduction

https://codesandbox.io/p/github/efflam/remix-pandacss/main

### JS Framework

React w/ Remix 1.18.1

### Panda CSS Version

^0.6.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Bug reproduction repository : https://github.com/efflam/remix-pandacss

**Comment by segunadebayo** [comment]
This has already been fixed in one of the recent PRs. We'll release an update shortly.

If the issue persists after the release, I'll re-open this issue.

**Comment by fcisio** [comment]
Hi, I'm on Remix 2.5.0 and Panda 0.27.1 and this is still an issue.

**Comment by fcisio** [comment]
After some testing, I can confirm that the bug reappeared on version 0.24.0.
Version 0.23.0 is the latest version without this bug.

**Comment by anubra266** [comment]
@fcisio Does this happen in v0.27.2?

**Comment by fcisio** [comment]
Yes, seems to still happen in v0.27.2

**Comment by segunadebayo** [comment]
I just tested this with the latest remix and it works as expected.

Here's the `app/root.tsx`

```jsx
import type { LinksFunction } from '@remix-run/node'
import {
  Links,
  LiveReload,
  Meta,
  Outlet,
  Scripts,
  ScrollRestoration,
} from '@remix-run/react'
import styles from './index.css'

export const links: LinksFunction = () => [{ rel: 'stylesheet', href: styles }]
```

Here's the  `app/index.css`

```jsx
@layer reset, base, tokens, recipes, utilities;

* {
  color: orange;
  font-size: 40px;
}
```

https://github.com/chakra-ui/panda/assets/6916170/4f7320a6-2b0e-4ded-8203-5ed03dbdb55b
