### ISSUE TITLE
Storybook loses hot-reload functionality when tokens/recipes are defined in another file

### ISSUE THREAD

**Issue by mayteio** [chakra-ui/panda#1025]
### Description

When I define tokens or recipes in a separate file than `panda.config.ts` and make changes to them, I expect storybook to hot reload with the new changes. Instead, I have to stop and start storybook again, or make a change and save `panda.config.ts` to see reflected changes. Here's a video explaining:

https://www.loom.com/share/67ce95f64e604481be71fc91f6d8e3a6

My first clue here was the extraction time dropped significantly for subsequent storybook renders:
![Screenshot 2023-07-12 at 1 33 01 pm](https://github.com/chakra-ui/panda/assets/43975092/92ccec51-a4bb-4e51-9614-b3dc1dd34203)

This works:
```ts
export default defineConfig({
  ...,
  theme: {
    extend: {
      tokens: defineTokens({
        colors: {
          heavy: { value: "blue" },
          light: { value: "red" },
        },
      }),
    }
  },
});
```

this only works on startup, then doesn't pick up any new changes.
```ts
import { tokens } from "./theme";

export default defineConfig({
  ...,
  theme: {
    extend: { tokens }
  },
});
```

I can get panda to pick up the changes by making a change in `panda.config.ts`, so I assume it's reloading the context, running over the files it needs to generate and then losing that context for subsequent extractions. 

Maybe worth mentioning - in our codebase we've split the theme into multiple files (theme/tokens, theme/semantic-tokens, theme/recpies/button, theme/recpies/text-field, etc) as we've got stacks of tokens and recipies that make up our component library.

Next.js works as expected, it's just storybook that seems to lose the context of which files need to be watched.

### Link to Reproduction

[codesandbox](https://codesandbox.io/p/github/mayteio/panda-next-storybook-2/draft/blissful-jang?file=%2Fpanda.config.ts%3A25%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljzdzq6n000g3b6m34lgijh1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljzdzq6m000b3b6m72nirauv%2522%253A%257B%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%252C%2522activeTabId%2522%253A%2522cljzdzq6m000a3b6mo7o5p557%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6m000a3b6mo7o5p557%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522id%2522%253A%2522cljzefrq601hm3b6myzt9pexr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpanda.config.ts%2522%252C%2522id%2522%253A%2522cljzeh0gc00cp3b6mu6234esb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftheme.ts%2522%252C%2522id%2522%253A%2522cljzeil2j00po3b6myyqzpyha%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljzdzq6n000d3b6maavs851h%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%252C%2522activeTabId%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljze1yuh012j3b6mi4mlcwyb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A6006%252C%2522id%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fstory%252Fpage--preview%2522%257D%255D%257D%252C%2522cljzdzq6n000f3b6mqcwg87yy%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%252C%2522activeTabId%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljzdzqbg000pe8hx5g8e06q8%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljze1v1c00pl3b6m9nrufipm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. Go to [codesandbox](https://codesandbox.io/p/github/mayteio/panda-next-storybook-2/draft/blissful-jang?file=%2Fpanda.config.ts%3A25%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljzdzq6n000g3b6m34lgijh1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljzdzq6m000b3b6m72nirauv%2522%253A%257B%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%252C%2522activeTabId%2522%253A%2522cljzdzq6m000a3b6mo7o5p557%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6m000a3b6mo7o5p557%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522id%2522%253A%2522cljzefrq601hm3b6myzt9pexr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpanda.config.ts%2522%252C%2522id%2522%253A%2522cljzeh0gc00cp3b6mu6234esb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftheme.ts%2522%252C%2522id%2522%253A%2522cljzeil2j00po3b6myyqzpyha%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljzdzq6n000d3b6maavs851h%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%252C%2522activeTabId%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljze1yuh012j3b6mi4mlcwyb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A6006%252C%2522id%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fstory%252Fpage--preview%2522%257D%255D%257D%252C%2522cljzdzq6n000f3b6mqcwg87yy%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%252C%2522activeTabId%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljzdzqbg000pe8hx5g8e06q8%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljze1v1c00pl3b6m9nrufipm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Run `pnpm storybook`
3. Make changes in `theme.ts`
4. See changes are not reflected in storybook

### JS Framework

React (TS), Storybook, Next.js

### Panda CSS Version

0.6.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
can't access the repro link, do you have a github repo instead ?
![Screenshot 2023-07-12 at 10 35 40](https://github.com/chakra-ui/panda/assets/47224540/d1f8d003-ce3e-4516-bae8-110c4438ad51)

**Comment by mayteio** [comment]
Sure do! Sorry about that: https://github.com/mayteio/panda-next-storybook-2/tree/draft/blissful-jang

[Codesandbox link again 🤞](https://codesandbox.io/p/github/mayteio/panda-next-storybook-2/draft/blissful-jang?file=%2Fpanda.config.ts%3A25%2C9&layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522cljzdzq6n000g3b6m34lgijh1%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljzdzq6m000b3b6m72nirauv%2522%253A%257B%2522id%2522%253A%2522cljzdzq6m000b3b6m72nirauv%2522%252C%2522activeTabId%2522%253A%2522cljzeh0gc00cp3b6mu6234esb%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6m000a3b6mo7o5p557%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.gitignore%2522%252C%2522id%2522%253A%2522cljzefrq601hm3b6myzt9pexr%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fpanda.config.ts%2522%252C%2522id%2522%253A%2522cljzeh0gc00cp3b6mu6234esb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftheme.ts%2522%252C%2522id%2522%253A%2522cljzeil2j00po3b6myyqzpyha%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljzdzq6n000d3b6maavs851h%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000d3b6maavs851h%2522%252C%2522activeTabId%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522cljze1yuh012j3b6mi4mlcwyb%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A6006%252C%2522id%2522%253A%2522cljzefk5101eg3b6mmnnvvxdo%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fstory%252Fpage--preview%2522%257D%255D%257D%252C%2522cljzdzq6n000f3b6mqcwg87yy%2522%253A%257B%2522id%2522%253A%2522cljzdzq6n000f3b6mqcwg87yy%2522%252C%2522activeTabId%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljzdzq6n000e3b6m5sgs8c89%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522cljzdzqbg000pe8hx5g8e06q8%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522cljze1v1c00pl3b6m9nrufipm%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Comment by mayteio** [comment]
Thanks so much for the quick action @astahmer @segunadebayo 🙏🏻
