### ISSUE TITLE
zIndex tokens are intellisensed but not generated or made available

### ISSUE THREAD

**Issue by fredericoo** [chakra-ui/panda#1038]
### Description

When I add tokens in the panda config file, the `zIndex` option is available.
When I create a list of possible values, I expect to be able to codegen and select from that list when using the `css` function or jsx components.
However they get ignored and aren’t generated at all.

### Link to Reproduction

https://stackblitz.com/edit/nextjs-h2sd4l?file=styled-system%2Ftypes%2Fprop-type.d.ts

### Steps to reproduce

1. Add in some `zIndex` tokens
2. Run `panda codegen`
3. Expect to see them generated
4. They don’t

### JS Framework

TS

### Panda CSS Version

0.6.0

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Bear in mind the docs have the tokens for zIndex listed as `zIndices`, but intellisense suggests `zIndex`.

**Comment by segunadebayo** [comment]
Good catch @fredericoo.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by RyKilleen** [comment]
Was this part of a recent release? I'm also experiencing this with `latest`, v2.8.0
