### ISSUE TITLE
generatePackageJson function doesn't consider 'outExtension' option when attaching "exports" inside generated package.json if emitPackage is set to true

### ISSUE THREAD

**Issue by luciancostinailenei** [chakra-ui/panda#1050]
### Description

Reference: https://github.com/chakra-ui/panda/blob/579080b751c2ede1c49c5e315fce52ec143638ed/packages/generator/src/artifacts/pkg-json.ts#L4

Current behavior: If emitPackage option is set to true in a panda.config file, a node_modules/[outdir] folder will be generated, containing a package.json that specifies the mapping of files exported by the package. Looking over the above mentioned code file, you can see that the specified exported files are hardcoded with '.mjs' extension which means that if you choose `outExtension: 'js' ` as a config option, the exports will point to inexistent `.mjs ` files and applications won't be able to discover the needed resources via `'import'`.

Expected behavior: generatePackageJson function should also consider the chosen outExtension config parameter and generate export mappings accordingly.

### Link to Reproduction

https://github.com/chakra-ui/panda/blob/579080b751c2ede1c49c5e315fce52ec143638ed/packages/generator/src/artifacts/pkg-json.ts#L4

### Panda CSS Version

0.6.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
I also thought pointing to inexistent `.mjs` files was weird but it fixed this issue https://github.com/chakra-ui/panda/discussions/960#discussioncomment-6374538 🤷‍♂️ 

if updating the actual generated files extension to `.js` doesn't break that issue I linked, then feel free to send a PR
here's the PR https://github.com/chakra-ui/panda/pull/972 that fixed the previous issue

**Comment by segunadebayo** [comment]
Good catch @luciancostinailenei.

I just pushed a fix for this in [156b6bd](https://github.com/chakra-ui/panda/commit/156b6bde69ad903377bbf9ec537c03cc79c80142). We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by luciancostinailenei** [comment]
@segunadebayo thanks a lot ! 💪
