### ISSUE TITLE
Missing styles when using config recipes and Storybook

### ISSUE THREAD

**Issue by rcoedo** [chakra-ui/panda#1057]
### Description

Panda loses track of used styles when writing [Storybook stories using args](https://storybook.js.org/docs/react/writing-stories/introduction#using-args).

The bug can be reproduced [using this repository](https://github.com/rcoedo/pandacss-pnpm-turbo). The steps to reproduce it are detailed in the README.md.

Thanks for the hard work!

### Link to Reproduction

https://github.com/rcoedo/pandacss-pnpm-turbo

### Steps to reproduce

1. Install the dependencies
2. Run `pnpm dev` to start the `front` and `workshop` applications.
3. Open [workshop](http://localhost:6006/) and [front](http://localhost:5173/) in your browser.
4. Notice that the `Edgy` story is missing its styles.
5. Edit `packages/design-system-react/src/button/button.stories.ts`, comment out the Edgy args story, uncomment the Edgy
   render story.
6. Restart the servers.
7. Notice that `Edgy` is now correctly styled.

### JS Framework

React (TS)

### Panda CSS Version

0.7.0

### Browser

Any

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
I'm not sure if this is what you expect, but this:

https://github.com/rcoedo/pandacss-pnpm-turbo/blob/main/packages/design-system-react/src/button/button.stories.tsx#L29-L36

```ts
export const Edgy: Story = {
	args: {
		visual: "edgy",
		shape: "square",
		size: "sm",
		children: "edgy button",
	},
};
```

can't be extracted by panda as we have no way to know that this object is related to styling

---
on the other hand, this should be just fine:

```tsx
export const FunkyRenderStory: Story = {
	render: () => (
		<Button shape="square" visual="funky" size="lg">
			I'm a button!
		</Button>
	),
};
```

---

if you want to keep using an object, then you could do something like:

```ts
export const Edgy: Story = {
	args: {
		className: css({
			visual: "edgy",
			shape: "square",
			size: "sm",
			children: "edgy button",
		})
	},
}

**Comment by segunadebayo** [comment]
Closing this as the new `.raw` syntax will help hint the extractor.

More details here: https://github.com/chakra-ui/panda/pull/1069

**Comment by ShakurOo** [comment]
What is `button` in your exemple ? A component ? A recipe ? 

`button.raw` because I can't use it with recipe : `Property 'raw' does not exist on type 'RecipeConfig'.`
