### ISSUE TITLE
Better same-next-sibling selector support?

### ISSUE THREAD

**Issue by anulman** [chakra-ui/panda#1072]
### Description

Sibling selectors—in particular `& + &` for same-next-sibling relationships—are very helpful in CSS. Please consider adding more conditional selector keywords, or documenting how end-users can do so?

### Problem Statement/Justification

I am working on a card-based design, where I'm supposed to put a border between `<div class="card">`. To keep the DOM relatively flat, I was hoping not to wrap these in a `<div class="card-group">`. I usually achieve this with a `& + &`-style selector, for which Panda offers no modifier keywords.

I can't:

- Use the `:first` or `:first-of-type` modifiers, because I'm not guaranteed these will be the first elements (or `<div>`s) without introducing a wrapper element
- Use the `:even` / `:odd` modifiers to apply top and bottom borders to only the even (or odd) elements, because sometimes an interstitial element will break up my card groups
- Use the `_peer` modifiers, because this isn't related to a hover / etc. effect, and because they will also not work correctly when interstitial elements break up my cards.

### Proposed Solution or API

I'd love to write a style that looks like:

```js
const card = css({
  bg: "red.400",
  _sameNextSibling: {
    borderTop: "1px solid white"
  }
});
```

_n.b. I'm not convinced `_sameNextSibling` is the right name; perhaps `_samePreviousSibling` would make more sense._

### Alternatives

- Wrap my cards in a `<div class="card-group">` — a flatter DOM will make more sense semantically and, with more complex element trees, will be more performant.
- Use existing modifiers — as described above, the available options have common failure modes that will break my styles
- Write my own modifier keyword — not sure where to do this

### Additional Information

I'm happy to write this code! If you can just help me find where the current modifiers are for e.g. `_peerFocus`, `_onlyOfType`, etc.

**Comment by anubra266** [comment]
@anulman conditions are customizable, so you can add this to your config. Guide here https://panda-css.com/docs/customization/conditions

**Comment by anulman** [comment]
Oh wow, just stumbled on that myself! This is fab.

I guess my suggestion then is to link this somewhere in the conditions documentation :)
