### ISSUE TITLE
Storybook autodocs

### ISSUE THREAD

**Issue by olafurns7** [chakra-ui/panda#1078]
### Description

When I import a for example `Box` from `styled-system/jsx` and create a Story with it, I expect the autodocs to be able to generate the properties for it. This however does not happen.

### Link to Reproduction

.

### Steps to reproduce

Create a Panda with Storybook integration, create a `box.stories.tsx`:

```typescript
import { Box, BoxProps } from '@aurora-ui/styled-system/jsx';
import type { Meta, StoryObj } from '@storybook/react';

// More on how to set up stories at: https://storybook.js.org/docs/react/writing-stories/introduction#default-export
const meta = {
  title: 'Layout/Box',
  component: Box,
  tags: ['autodocs'],
} satisfies Meta<BoxProps>;

export default meta;
type Story = StoryObj<typeof meta>;

// This story uses a render function to fully control how the component renders.
export const Primary: Story = {
  render: (props) => {
    const { children, ...rest } = props;
    console.log(props);
    return <Box {...props}>I'm in a box!</Box>;
  },
};
```

### JS Framework

React  TS

### Panda CSS Version

0.7.0

### Browser

Google Chrome 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/chakra-ui/panda/assets/85343965/815f729c-c34c-4b2b-afe5-09bdb6e5785d)

**Comment by segunadebayo** [comment]
This doesn't seem to be a Panda bug.

The type definitions for all components are generated. Kindly re-open this in the Storybook repo.

> When this works, that prop table will be very massive since it includes all common CSS properties.
