### ISSUE TITLE
`panda studio` fails to read `postcss` config from `package.json`

### ISSUE THREAD

**Issue by kevva** [chakra-ui/panda#1104]
### Description

When running `panda studio` and having configured `postcss` using the `postcss` field in `package.json` it just fails with the following error:

```
TypeError: Invalid PostCSS Plugin found at: plugins[0]
```

After removing the configuration it runs successfully. However, it's common to configure `postcss` [using `package.json`](https://github.com/postcss/postcss-load-config#packagejson) to reduce the number of config files so I'd assume `panda studio` would work as well.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-e5apzn

### Steps to reproduce

1. Run `npx panda studio` in the terminal
2. See error

### Panda CSS Version

0.7.0

**Comment by segunadebayo** [comment]
Hi @kevva,

The Panda studio is built with Astro which in turn uses Vite. The issue is related to how they resolve or detect PostCSS.

Within our source code, we don't search for the PostCSS config; we leave that to the framework.

Kindly move this issue to the Astro or Vite repo.

Thanks
