### ISSUE TITLE
Reduce the size of generated styled system

### ISSUE THREAD

**Issue by Temzasse** [chakra-ui/panda#1106]
### Description

First of all thank you for this amazing library! 🤗 

I've been migrating a project template from styled-components to panda and it's going great but I noticed that the generated styled system is rather large in size.

Two things in particular caught my eye in the bundle analyzer:

1. **Patterns are not tree shaken.** I'm currently only using one or two patterns and still all of the baked-in patterns end up in the JS bundle.
2. **`is-valid-prop` is very large.** This file seems to contain all the possible css properties and user defined custom ones. Is it needed to verify these properties during runtime? Wouldn't it be enough to rely on type checking alone?

### Link to Reproduction

https://github.com/TaitoUnited/full-stack-template/blob/pandacss-repro-1/client/styled-system/setup/config.ts

### Steps to reproduce

1. Go to `/client` directory
2. Run `npm install`
3. Run `npm run analyze`
4. See the bundle analysis

### JS Framework

React (TS)

### Panda CSS Version

0.8.0

### Browser

-

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

<img width="1730" alt="Screenshot 2023-07-26 at 9 14 45" src="https://github.com/chakra-ui/panda/assets/6152032/e4974de1-dcfb-4c4a-834e-452aa3f218a0">

**Comment by astahmer** [comment]
Hey, thanks for pointing that, we're working on it [here](https://github.com/chakra-ui/panda/pull/1115)

> This file seems to contain all the possible css properties and user defined custom ones. Is it needed to verify these properties during runtime?

It is needed to split between style & element props when using JSX such as :

```ts
<styled.div onClick={() => console.log("click")} margin="10px" data-thing="123"
```

so we can forward onClick & data-thing to the JSX constructor, for ex with react:

https://github.com/chakra-ui/panda/blob/4147b242fea98b82037fd1da493567f1cd0ee3ee/packages/generator/src/artifacts/react-jsx/jsx.ts#L20-L22

https://github.com/chakra-ui/panda/blob/4147b242fea98b82037fd1da493567f1cd0ee3ee/packages/generator/src/artifacts/react-jsx/jsx.ts#L39-L41

**Comment by Temzasse** [comment]
Thanks for explaining the reasoning @astahmer 👍🏻 

Would it be possible to have a config option to disable `<styled.div marginTop="10px">` usage and only allow `const Comp = styled('div', {})`? Would this allow not outputting the `is-valid-prop` altogether? The option could be called something like:

```ts
jsxMode: 'styled-props' | 'styled-component' | 'all'
```

Our use case is to try to replace styled-components with panda so we don't necessarily need the style props functionality since `css()` and `styled()` are sufficient for us.

**Comment by astahmer** [comment]
Disabling the styled factory is also what we had in mind that would happen when using `jsxStyleProps: "none"`

jsxStyleProps: "none" also means no `<Stack css={{ color: "red.300" }} />` possible, is that still in your use-case ? or are you saying that you would like to be able to use the `css` prop but to disable the styled factory anyway ?

**Comment by Temzasse** [comment]
Aaah sorry I didn't take a good enough look at the draft PR that you linked. If `jsxStyleProps: "none"` disables `<styled.div>` but not `styled('div', {})` then that's perfect 👌🏻 

We could  still add extra styles to the `Stack` with `<Stack className={css({...})}>`, right? For us it's probably fine if we lose access to the `css` prop as long as we can use `css()` to apply styles.

**Comment by astahmer** [comment]
> We could still add extra styles to the Stack with <Stack className={css({...})}>, right? For us it's probably fine if we lose access to the css prop as long as we can use css() to apply styles.

yes you can still pass any react/vue/{your framework} props, so className would be the way to override styles indeed !

**Comment by Temzasse** [comment]
Awesome! Thank you @astahmer so much for working on this! 🙏🏻 ✨
