### ISSUE TITLE
[TS types] Cannot set flexDirection as important

### ISSUE THREAD

**Issue by lalexdotcom** [chakra-ui/panda#1112]
### Description

Typescript is emitting an error if using any of those syntax;
```typescript
css({
	flexDirection: 'column !important',
	// Or
	flexDirection: 'column!',
})
```

### Link to Reproduction

<none>

### JS Framework

React (TS)

### Panda CSS Version

0.8.0

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

**Comment by alexanderhorner** [comment]
The same thing happens with colorPalette btw.

**Comment by anubra266** [comment]
@alexanderhorner I understand it for the css propoerties. But what usecase would this be needed for in colorPalette? it's not a css property.

**Comment by alexanderhorner** [comment]
It's applied as css property in the end. So when you use cva and set the colorpalatte to use in your variants, but you wanna overwrite it when using the cva, you can use !important. I tried it and it works, but if there's a better way please tell me.

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
