### ISSUE TITLE
When one of component's prop has default value, some atomic classes are not generated

### ISSUE THREAD

**Issue by young-do** [chakra-ui/panda#1123]
### Description

First, I think panda-css is a fantastic library. 
I've been using it very well in my personal projects. However, I think I've found an issue and I'm curious if it's a bug.

If a default value is assigned to one of the component's props, it is included in the class list. But in reality, the proper styling was not applied because there was no generated some atomic CSS.

To resolve this issue temporarily, I found that one could either not assign a default value, or use cva. However, I don't believe that cva exists to prevent this situation, so in my opinion, this is a bug.

<img width="1616" alt="스크린샷 2023-07-29 오전 1 19 56" src="https://github.com/chakra-ui/panda/assets/22021344/4f4a0023-95df-4a4b-aefd-6c5633fa3fd7">

### Link to Reproduction

https://play.panda-css.com/kL4qzUGcPh

### Steps to reproduce

You can check it intuitively from the link above.

### JS Framework

React + TypeScript

### Panda CSS Version

0.8.0

### Browser

Chrome 114.0.5735.248

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
It is indeed a bug with our extractor

What happens is that since `CompB`'s `disabled` prop is statically analyzable (to `false`) through its default prop, we skip entirely the `whenTrue` branch

Fixed [here](https://github.com/chakra-ui/panda/pull/1125)

**Comment by young-do** [comment]
@astahmer 
So, it was a bug. Thanks for fixing it quickly. 🙇‍♂️
