### ISSUE TITLE
Pattern styles are not generated in Windows machine

### ISSUE THREAD

**Issue by jeiea** [chakra-ui/panda#1130]
## Expected behavior

Github icon should be places at the bottom of the page because body > div's class contains `d_flex h_100%` and div > main's class contains `flex_1`.

## Actual behavior

Github icon is located right after button.

### Link to Reproduction

https://github.com/jeiea/node_report

### Steps to reproduce

1. Execute the following

```
git clone https://github.com/jeiea/node_report.git
cd node_report
pnpm i
pnpm panda
pnpm run dev
```

2. Open http://localhost:5173

### JS Framework

qwik

### Panda CSS Version

0.9.0

### Browser

Google Chrome 115.0.5790.110 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by astahmer** [comment]
![Screenshot 2023-07-30 at 23 13 16](https://github.com/chakra-ui/panda/assets/47224540/80a82d0d-a1a2-43a8-b753-6e4c474c6bb3)
i'm not sure to follow, what's the issue here ?

**Comment by jeiea** [comment]
It seems it is not reproducible with your environment. What I'm seeing is the following.

<img width="1049" alt="image" src="https://github.com/chakra-ui/panda/assets/4188984/9228d692-f7b0-4e4f-9d60-6328cd0c4083">

I don't know the why, but attach additional information.

```
 pnpm panda debug
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/config.json
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__routes__index.ast.json
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__routes__index.css
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__routes__layout.ast.json
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__routes__layout.css
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__components__starter__footer.ast.json
🐼 info [cli] Writing D:/Repos/jeiea/2023/07/node_report/src/styled-system/debug/src__components__starter__footer.css
🐼 info [cli] Found 3/11 files using Panda
```

`src__routes__layout.ast.json`
```
{
  "css": [
    {
      "type": "object",
      "name": "css",
      "box": {
        "type": "map",
        "value": {},
        "node": "CallExpression",
        "line": 31,
        "column": 20
      },
      "data": [
        {
          "flex": 1
        }
      ]
    }
  ],
  "cva": [],
  "recipe": {},
  "pattern": {},
  "jsx": [
    {
      "type": "jsx",
      "name": "Header",
      "box": {
        "type": "map",
        "value": {},
        "node": "JsxSelfClosingElement",
        "line": 30,
        "column": 7
      },
      "data": [
        {}
      ]
    },
    {
      "type": "jsx",
      "name": "Slot",
      "box": {
        "type": "map",
        "value": {},
        "node": "JsxSelfClosingElement",
        "line": 32,
        "column": 9
      },
      "data": [
        {}
      ]
    },
    {
      "type": "jsx",
      "name": "Footer",
      "box": {
        "type": "map",
        "value": {},
        "node": "JsxSelfClosingElement",
        "line": 34,
        "column": 7
      },
      "data": [
        {}
      ]
    }
  ]
}
```

**Comment by segunadebayo** [comment]
You're using both the CLI and PostCSS simultaneously, which is not ideal.

You need to include this step in the PostCSS setup: https://panda-css.com/docs/installation/qwik#configure-the-entry-css-with-layers.

When you do that, you only need to add `panda codegen` to the `prepare` script.

Try these and if the issue still persists we'll re-open.

**Comment by jeiea** [comment]
> You're using both the CLI and PostCSS simultaneously, which is not ideal.

Sorry, I can't get your words. I followed [this instruction](https://qwik.builder.io/docs/integrations/panda-css/) and adding `"prepare": "panda codegen"` to the package.json didn't make difference.

In other words I can't know what to try.
