### ISSUE TITLE
`🐼 error [❌] No matching pid found`

### ISSUE THREAD

**Issue by nightgrey** [chakra-ui/panda#1139]
### Description

When working with Panda and Remix, compilation errors will occasionally produce `🐼 error [❌] No matching pid found` error. 

If that happens, panda will not re-generate anymore (even though Remix continues) and I have to restart the whole process. 

* This is flaky and/or I couldn't pin down the exact reason / couldn't find a way to perfectly reproduce it yet.
* It only happens after a hot reload / compilation exception is triggered (i.e. syntax error, wrong import, etc.)

I mainly wanted to report this so it is known. I hope that maybe, others have that issue, too, and we can solve it over time with more manpower :)

### Link to Reproduction

https://stackblitz.com/edit/remix-run-remix-nd5q6i?file=app%2Froutes%2F_index.tsx

### Steps to reproduce

1. Create a Remix project
3. Install panda according to the docs
4. Run `npm run dev`
5. Work on the project and produce a compilation exception
6. Observe how even though Remix continues to hot reload, Panda does not.

> Note: `🐼 error [❌] No matching pid found` is flaky and does not appear after every compilation exception.
### JS Framework

React, NPM, TypeScript

### Panda CSS Version

^0.9.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

#### Screenshots

![image](https://github.com/chakra-ui/panda/assets/6065401/7bffb81b-b9ec-4323-acdc-33d6dceb55cd)

> Thought: Given the exception is sourced in the panda folder itself, could it be a race condition between Remix and the generation of panda's styled system?

#### Edits / further info

- It now just happened a second time after modifying a recipe. There was no error in the recipe. First, it generated a Remix compilation error like above. On the next file-save, it was fine, but generated the `no matching pid found` error.

**Comment by nightgrey** [comment]
Hey, I have some updates after some more expirementation. It seems as though it happens almost everytime specifically when updating a recipe created with `createRecipe`, like this:

**tag.ts**
```tsx
import { createRecipe } from '@pandacss/dev';

export const tag = createRecipe({
  className: 'tag',
  base: {
    // ...
  }
});
```

> Note: Code is from the top of my head, may be slightly incorrect - but the spirit is accurate. Recipe is imported into the panda config just like in Ark UI's website. Will update the sandbox later.

**Findings**

1. When updating the recipe's styles, the error in the screenshot happens very often and the hot reloading does not work reliably, or at all, even with no compilation error.
4. The compilation error (same as in the screenshot above) happens pretty often.
5. `No matching pid found` happens often after the compilation error in this case.

Now, when I don't use `createRecipe`, but instead just export an object and use the `RecipeConfig`type for type safety, these problems all disappear and the hot-reloading when modifying styles works properly, too.

**Comment by astahmer** [comment]
This looks like a PostCSS/Remix specific issue, [we can't reproduce it](https://stackblitz.com/edit/remix-run-remix-kpkfvn?file=app%2Froutes%2F_index.tsx,app%2Froot.tsx,panda.config.ts,app%2Fentry.client.tsx), please transfer the issue there
