### ISSUE TITLE
container pattern not working when having tokens

### ISSUE THREAD

**Issue by cpatigny** [chakra-ui/panda#1149]
### Description

When having tokens in panda.config.ts, container pattern function or even using Container jsx has invalid css values like "max-width: 8xl". When I remove tokens from config it works perfectly fine. 
In the panda css playground I provided there is nothing in tokens but even with something defined in tokens it doesn't work. The simple fact of having tokens in config make container stop working properly. I tried with stack pattern and it works fine. Semantic tokens doesn't seem to make container bug.

### Link to Reproduction

https://play.panda-css.com/5WJY2rWIEO

### JS Framework

react (TS)

### Panda CSS Version

0.9.0

### Browser

Google Chrome 115

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

![image](https://github.com/chakra-ui/panda/assets/63152989/89ad15e0-0d24-4e9f-95fd-3a12a3854f23)

**Comment by astahmer** [comment]
you're replacing the tokens entirely instead of extending them, change your config like so:

```diff
- theme: { extend: {}, tokens: {} },
+ theme: { extend: { tokens: {} }, },
```

**Comment by cpatigny** [comment]
> you're replacing the tokens entirely instead of extending them, change your config like so:
> 
> ```diff
> - theme: { extend: {}, tokens: {} },
> + theme: { extend: { tokens: {} }, },
> ```

It works perfectly, thank you !
