### ISSUE TITLE
Recipe variant types are not being exported

### ISSUE THREAD

**Issue by khanh-le-otsv** [chakra-ui/panda#1167]
### Description

Variant types are not being exported and tsup shows warnings:

```
src/components/Button/Button.tsx (11:95) "ButtonVariant" is not exported by "styled-system/recipes/index.d.ts", imported by "src/components/Button/Button.tsx".
```

### Link to Reproduction

No need

### Steps to reproduce

1. Create a recipe: button
2. Register that recipe
3. Use that recipe type:
```typescript
type ButtonProps = ButtonVariantProps;
```
4. Build with tsup
5.Got the warning:
```
src/components/Button/Button.tsx (11:95) "ButtonVariant" is not exported by "styled-system/recipes/index.d.ts", imported by "src/components/Button/Button.tsx".
```

### Panda CSS Version

0.9.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
I can't reproduce this locally, can you provide a minimal repro ?
