### ISSUE TITLE
HTMLStyledProps type ommits my 'size' property.

### ISSUE THREAD

**Issue by MiiZZo** [chakra-ui/panda#1174]
### Description

```tsx
import { cva, RecipeVariantProps } from 'styled/css';
import { styled, HTMLStyledProps } from 'styled/jsx';

const buttonStyle = cva({
  variants: {
    size: {
      xs: {
       // ...
      }
    }
  }
});

const StyledButton = styled('button', buttonStyle);
type Props = HTMLStyledProps<typeof StyledButton>;

function Button(props: Props) {}

<Button size="xs" /> // Property 'size' does not exist on type Props
```
The problem is this type in /styled-system/types/styled-system.d.ts
```ts
export type OmittedHTMLProps = 'color' | 'translate' | 'transition' | 'width' | 'height' | 'size' | 'content'
```

### Link to Reproduction

https://play.panda-css.com/T8Tq1mZU5h

### Panda CSS Version

0.9.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @anubra266,

Please use `React.ComponentProps` instead. `HTMLStyledProps` is a type that mirrors the `styled` API; it supports basic DOM elements. The omit is used to avoid the clash between style props and their equivalent native attributes.

```ts
type Props = React.ComponentProps<typeof StyledButton>;
```

https://play.panda-css.com/Llc--WZZeg
