### ISSUE TITLE
ts error on custom selectors inside properties

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/panda#1186]
### Description

When selecting a custom selector using a string as key in the object, typescript will complain that it only accepts known values:

const className = css({
    borderColor: {
      base: 'gray.800',
      _focusWithin: 'purple.600',
      // @ts-ignore
      '&:has([aria-invalid])': 'red.7',
    }
  })
  
  this works, but typescript will complain. 
  Alternativelly, you can create a condition, like invalidWithin: 
 conditions: {
   extends: {
     invalidWithin: '&:has([aria-invalid="true"])',
   }
 }
 
 this will work, because now typescript recognizes it. But I still think that '&:has([aria-invalid])' should be recognized too.

### Link to Reproduction

https://github.com/FilipePfluck/panda-bugs

### Steps to reproduce

clone the repo
go to app/layout.tsx
uncomment the //@ts-ignore

### JS Framework

React (TS)

### Panda CSS Version

0.10.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
This is a TS limitation at the moment. Loosening the type to support any selector will break the existing typings.

Please put the selector on the root object instead.
