### ISSUE TITLE
Missing content property for before

### ISSUE THREAD

**Issue by stuarthendren** [chakra-ui/panda#1192]
### Description

When I use `content: ''` in a before expression the content does not appear in the generated css.
Other properties in the same expression to appear.

In the linked example this is the output:

![Screenshot 2023-08-10 at 10 51 21](https://github.com/chakra-ui/panda/assets/39833/12861974-e881-4cbd-af81-dfcf91ad6289)

Manually adding the content in the dev tools gives:

![Screenshot 2023-08-10 at 10 53 29](https://github.com/chakra-ui/panda/assets/39833/45fcaef6-fae0-433a-afd5-b09603cd15a2)

### Link to Reproduction

https://play.panda-css.com/IoEKnUr4sC

### JS Framework

React

### Panda CSS Version

0.9.0

### Browser

Chrome 115

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please wrap it in an extra quote like so: `content: `''`

https://play.panda-css.com/ewXS0az8iU
