### ISSUE TITLE
 utility classes are not being generated when use with mergeCss() in styled-system/css

### ISSUE THREAD

**Issue by tanangular** [chakra-ui/panda#1222]
### Description

Working on Sveltekit and Panda CSS for a while, I noticed that there is mergeCss() in "styled-system/css" 
Try to test simple code with mergeCss() only following code below but utility classes are not being generated. (but with css() it's ok )

**Test1: mergeCss only**
<img width="1109" alt="Screenshot 2566-08-15 at 16 41 58" src="https://github.com/chakra-ui/panda/assets/1311673/5090bba4-e745-4a7b-abd3-b3dadd1bf9c5">
<img width="864" alt="Screenshot 2566-08-15 at 16 40 48" src="https://github.com/chakra-ui/panda/assets/1311673/57a70687-034d-40e2-8eac-dd15575a7f03">

**Test2: work with css()**
<img width="817" alt="Screenshot 2566-08-15 at 16 49 20" src="https://github.com/chakra-ui/panda/assets/1311673/2bffe1f7-0496-466c-8ae5-6ed9d4ccb388">
<img width="957" alt="Screenshot 2566-08-15 at 16 48 23" src="https://github.com/chakra-ui/panda/assets/1311673/a3e2f8a1-3e66-4bfb-b04a-be4b0da05181">

### Link to Reproduction

https://github.com/tanangular/pandacss102

### JS Framework

Sveltekit TS

### Panda CSS Version

0.11.0

### Browser

Google Chrome 115.0.5790.170 / Edge 115.0.1901.188 

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

this is the content of package.json
{
	"name": "pandacss102",
	"version": "0.0.1",
	"private": true,
	"scripts": {
		"prepare": "panda codegen --clean",
		"dev": "vite dev",
		"build": "vite build",
		"preview": "vite preview"
	},
	"devDependencies": {
		"@pandacss/dev": "^0.11.0",
		"@sveltejs/adapter-auto": "^2.1.0",
		"@sveltejs/kit": "^1.22.6",
		"svelte": "^4.2.0",
		"vite": "^4.4.9"
	},
	"type": "module"
}

/* svelte.config.js */
import adapter from '@sveltejs/adapter-auto';
import { vitePreprocess } from '@sveltejs/kit/vite';

/** @type {import('@sveltejs/kit').Config} */
const config = {
	preprocess: [
		vitePreprocess()
	],
	kit: {
		// adapter-auto only supports some environments, see https://kit.svelte.dev/docs/adapter-auto for a list.
		// If your environment is not supported or you settled on a specific environment, switch out the adapter.
		// See https://kit.svelte.dev/docs/adapters for more information about adapters.
		adapter: adapter(),
		alias: {
			'styled-system': './styled-system/*'
		}
	}
};

export default config;

**Comment by segunadebayo** [comment]
The merge-css function is an internal API and should not be used in the userland.

The compiler isn’t optimized to track the usage of that function.

If you’re trying to merge multiple css function calls, we’re recently improved the cx function that will help with this.

It’ll be out in the next release.

**Comment by tanangular** [comment]
Thanks you, for crystal clear explain.
