### ISSUE TITLE
Display dimensions in pixel units near rem units

### ISSUE THREAD

**Issue by Newbie012** [chakra-ui/panda#1225]
### Subject

Add pixel units to examples

### Description

I propose that the representation of measurements like spacing and font sizes be extended to also include pixel units just like in [Chakra](https://chakra-ui.com/docs/styled-system/theme#spacing). 

Many developers (myself included), tend to favor `px` units over `rem`. Often, it's more convenient for us to intuitively gauge size when presented in pixels, rather than involving the need for multiplication by 16.

**Comment by segunadebayo** [comment]
Good catch @Newbie012.

I've gone ahead to add the pixel value to the theme docs.

Should be live pretty soon.
