### ISSUE TITLE
TS for sva is not working

### ISSUE THREAD

**Issue by elite174** [chakra-ui/panda#1227]
### Description

```tsx
import { sva } from "../../../styled-system/css";

export const chipRecipe = sva({
  slots: ["root", "icon"],
  base: {
    root: {
      display: "flex",
      alignItems: "center",
      gap: "10px",
      width: "fit-content",
      height: "24px",
      paddingInline: "8px",
      borderRadius: "8px",
      cursor: "default",
    },
    icon: {
      width: "24px",
      height: "24px",
    },
  },
  variants: {
    view: {
      red: {
        root: {
          backgroundColor: "red",
        },
      },
    },
  },
});
```

panda config:
```ts
import { defineConfig } from "@pandacss/dev";

import { chipRecipe } from "./src/design-system/components/chip";

export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: ["./src/**/*.{ts,tsx}"],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {
      slotRecipes: {
        chip: chipRecipe,
      },
    },
  },

  // The output directory for your css system
  outdir: "styled-system",
  outExtension: "js",
});
```

I get: 
![image](https://github.com/chakra-ui/panda/assets/13636224/5672f0b8-6dca-4416-b9c5-96dff5e1f153)

### Link to Reproduction

-

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

0.11

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by elite174** [comment]
There are also infinite reloads for solid-js project (SPA)

**Comment by elite174** [comment]
![image](https://github.com/chakra-ui/panda/assets/13636224/604cd1d6-6a31-493a-9f39-4355b194aabf)

**Comment by segunadebayo** [comment]
Thanks for raising this issue. 

This shows we need to improve the docs somewhere.

- `sva` is a function you use directly in your app. It generates atomic slot recipes.
- `defineSlotRecipe` is the function to author slot recipes into the config.

In this case, replace `sva` with `defineSlotRecipe` and provide a `className` property as well.

t should work as expected.
