### ISSUE TITLE
When CSS property value is resolved from a helper function it only creates a class name but no actual CSS values are generated

### ISSUE THREAD

**Issue by tremppu** [chakra-ui/panda#1234]
### Description

When I try to resolve value for property with a function, I expect the value show since className is correct but that does not work. I feel that this kind of use of custom helper function should work since that is one of the benefits using CSS in JS. 

Simple example of css that is not working (see full example for real use case):
```jsx
const colorFn = () => 'hotpink';

const functionCss = css({
  background: colorFn(),
});

export const Component = () => {
  return (
    <div className={functionCss}>Function bg not working</div>
  )
}

// Generates
// <div class="bg_hotpink">Function bg not working</div>
// But class `bg_hotpink` is not generated / does not exist
```

Real use case for this could be something like:
```jsx
// Helper function for developer to calculate CSS clamp's min, target and max values with single parameter 
const clampCalculator = (sizeAt1920) => {
  const min = sizeAt1920 / 4;
  const target = Math.round((sizeAt1920 / 1920) * 10000) / 100;
  const max = sizeAt1920 * 2;
  return `clamp(${min}px,${target}vw,${max}px)`;
};

const clampCss = css({
  fontSize: clampCalculator(96),
});

export const Component = () => {
  return (
    <div className={clampCss}>Clamp not working</div>
  )
}
```

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-yebalm?description=The%20React%20framework%20for%20production&file=package.json,panda.config.mjs,app%2Flayout.jsx,app%2Fpage.jsx&title=Next.js%20Starter

### Steps to reproduce

1. Go to 'app/page.jsx'
2. See error

### JS Framework

Next.js @ latest

### Panda CSS Version

0.11.1

### Browser

Chrome 115

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @tremppu,

Panda cannot resolve dynamic values as mentioned [in the docs](https://panda-css.com/docs/guides/dynamic-styling).

The recommended approach is to use CSS variables.

```jsx
import { css } from '../styled-system/css';

const clampCalculator = (sizeAt1920) => {
  const min = sizeAt1920 / 4;
  const target = Math.round((sizeAt1920 / 1920) * 10000) / 100;
  const max = sizeAt1920 * 2;
  return `clamp(${min}px,${target}vw,${max}px)`;
};

const clampCss = css({
  fontSize: 'var(--fs)',
});

export default function Home() {
  return (
    <div className={css({ fontSize: '5xl', fontWeight: 'bold' })}>
      <div className={clampCss} style={{ '--fs': clampCalculator(96) }}>
        This font size should be clamped...
      </div>
    </div>
  );
}
```

**Comment by tremppu** [comment]
@segunadebayo In my opinion the [docs page for dynamic styling](https://panda-css.com/docs/guides/dynamic-styling) does not answer my question atm since it focuses on cases where CSS property's value is given as a react state or prop. In my case the value could be resolved without runnig anything during runtime since it's not inside of a component and in my opinion none of the examples try to resolve the value in a similar way. 

I can understand your solution. It works in simple cases but will cause pretty ugly code when a lot of helpers are required or variables need to change for breakpoints or different values are required inside of variants etc. 

To tackle this I made an utility and used it to create all of the clamped values.
```tsx
export default defineConfig({
  utilities: {
    extend: {
      calculateClamps: {
        className: 'clamped',
        transform(uglyString: string) {
          const properties = uglyString.split(';');
          return properties.reduce((acc, part) => {
            const [property, valueStr] = part.split(':');
            const value = Number(valueStr);
            const min = value / 4;
            const target = Math.round((value / 1920) * 10000) / 100;
            const max = value * 2;
            const result = `clamp(${min}px,${target}vw,${max}px)`;
            return { ...acc, [property]: result };
          }, {} as Record<string, unknown>);
        },
      },
    },
  }
})
// Usage
const clampedStyle = css({
  base: {
    calculateClamps: 'letterSpacing:5;fontSize:96',
  },
});
```

This helps but I would not say it's pretty and all of the clamp values need to be fitted into that string which gets hard to read. But it got me thinking - to make code cleaner do you think that it would be possible to get "utility like" way of resolving just the values for CSS properties? As utilities result into bunch of CSS properties with values. some kind of "resolvers / functions" could just work like functions do. In my head that kind of api would look like the following:

```tsx
export default defineConfig({
  functions: {
    extend: {
      calculateClamp: {
        className: 'clamped',
        transform(value: number) {
          const min = value / 4;
          const target = Math.round((value / 1920) * 10000) / 100;
          const max = value * 2;
          const result = `clamp(${min}px,${target}vw,${max}px)`;
          return result;
        },
      },
    },
  }
})
// Usage (CSS functions style)
const clampedStyle = css({
  base: {
    fontSize: 'calculateClamp(5)',
  },
});
// Or even just imports for TS support
import {calculateClamp} from 'styled-system/somewhere';
const clampedStyle = css({
  base: {
    fontSize: calculateClamp(5),
  },
});
```
