### ISSUE TITLE
Support TypeScript "moduleResolution": "node16"

### ISSUE THREAD

**Issue by omridevk** [chakra-ui/panda#1236]
### Description

Description
In [TypeScript 4.7](https://devblogs.microsoft.com/typescript/announcing-typescript-4-7), along the property "module": "node16" that enables ESM features in TypeScript, there are new values for the property "moduleResolution": "node16" and "nodenext".

### Problem Statement/Justification

The problem is that when using panda-css the generated code does not use "node16" imports in the ts definition files:
```
/* eslint-disable */
export * from './box'
export * from './flex'
export * from './stack'
export * from './vstack'
export * from './hstack'
export * from './spacer'
export * from './square'
export * from './circle'
export * from './center'
export * from './link-box'
export * from './link-overlay'
export * from './aspect-ratio'
export * from './grid'
export * from './grid-item'
export * from './wrap'
export * from './container'
export * from './divider'
export * from './float'
export * from './bleed'
export * from './visually-hidden'
```

All the imports should have file extensions to work with node16

### Proposed Solution or API

Update the codegen to add file extensions as well.

**Comment by cschroeter** [comment]
What are the benefits?

**Comment by omridevk** [comment]
Basically future proofing, this is how ESM will be handled in the future, a lot of projects are now moving to support this, as this is the way the industry is headed at the moment. 

'node16' or 'nodenext' for modern versions of Node.js. Node.js v12 and later supports both ECMAScript imports and CommonJS require, which resolve using different algorithms. These moduleResolution values, when combined with the corresponding [module](https://www.typescriptlang.org/tsconfig#module) values, picks the right algorithm for each resolution based on whether Node.js will see an import or require in the output JavaScript code.

Can be easily achieved:
- can be under a flag in panda.config.ts or even a flag passed to codegen.
- can automatically detected the tsconfig

**Comment by omridevk** [comment]
A tool like this shouldn't enforce the end-user to change their tsconfig in order for this to work.
As a workaround for now, i added "skipLibCheck" in my tsconfig, but I really want to avoid using that.

**Comment by omridevk** [comment]
sorry, the workaround doesn't work, as skipLibCheck only works for node_modules.

**Comment by omridevk** [comment]
I wouldn't mind creating a PR to address this.

**Comment by omridevk** [comment]
I have already started working on it :)

**Comment by segunadebayo** [comment]
If it works without having to detect the tsconfig, then that’s an ideal solution. 

Please go for it @omridevk

**Comment by omridevk** [comment]
not sure if would work without some kind of a flag.

**Comment by omridevk** [comment]
awesome!! sorry didn't get a chance to do it, thanks so much.

**Comment by omridevk** [comment]
@segunadebayo  can you please re-open, see the following error:
<img width="984" alt="CleanShot 2023-09-03 at 21 38 45@2x" src="https://github.com/chakra-ui/panda/assets/9701896/b0252550-202d-4a80-a537-fd0925181b9a">


d.ts files should only import types from '.ts' files or import "js". 
Can this be addressed as well? 
Thanks.

**Comment by omridevk** [comment]
<img width="1018" alt="CleanShot 2023-09-03 at 21 40 12@2x" src="https://github.com/chakra-ui/panda/assets/9701896/81f91ee8-47d7-46d2-9805-c84136d1a753">

**Comment by segunadebayo** [comment]
@omridevk please use the forceConsistentTypeExtension option as documented in the PR. This will emit .d.mts files

Unfortunately, Panda cannot emit ts files but I believe that option should meet your needs.

**Comment by omridevk** [comment]
I did used it.

**Comment by omridevk** [comment]
and I updated to panda/dev 0.13.0

**Comment by omridevk** [comment]
the problem is that the index.d.ts files should either do ` import type * from '.....mts'` or import type from '...js'
