### ISSUE TITLE
Conditions not working when defined in preset

### ISSUE THREAD

**Issue by brettinternet** [chakra-ui/panda#1238]
### Description

When I add color mode conditions to my preset, the styles don't use the selector defined here.

```js
definePreset({
  conditions: {
    light: '[data-color-mode=light] &',
    dark: '[data-color-mode=dark] &',
  },
})
```

However, when I define them in `defineConfig`, it does work. Should a preset allow defining conditions? If not then perhaps the type is wrong.

Side node, I think the panda playground has a memory leak. It keeps crashing for me.

### Link to Reproduction

https://play.panda-css.com/pL0SOSbiRE

### Steps to reproduce

1. create preset with `definePreset`
2. add preset to config `presets: [myPreset]`
3. observe CSS output which nests dark color mode under `.dark` class

### JS Framework

react (TS)

### Panda CSS Version

0.11.1

### Browser

116 (latest)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@brettinternet Use extend so it can override the default preset.
![CleanShot 2023-08-19 at 20 50 12@2x](https://github.com/chakra-ui/panda/assets/30869823/a5ff12ef-2190-497c-b01b-6293cd7e9840)
