### ISSUE TITLE
auto completion in astro.

### ISSUE THREAD

**Issue by Hunnnn77** [chakra-ui/panda#1239]
### Description

```tsx
- auto completion issue

css({
  key: value
})
```
1. both key, value work in TSX file
2. only value works in Astro file(key - object prop seems not working as auto completion) 

### JS Framework

AstroJs

### Panda CSS Version

0.11.1

### Browser

FireFox

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not an issue in Panda. It’s more of an issue in the Astro language server and how it resolves the declaration files.

Kindly transfer this to the Astro repo.
