### ISSUE TITLE
cssgen minification

### ISSUE THREAD

**Issue by jonambas** [chakra-ui/panda#1240]
### Description

Would be nice to have a minification option for the CLI command [`panda cssgen`](https://panda-css.com/docs/references/cli#panda-cssgen). Currently, running this command produces non-minified CSS.

### Problem Statement/Justification

This would be great for component library authors who wish to wish to [ship a static CSS file](https://panda-css.com/docs/references/cli#panda-cssgen).

### Proposed Solution or API

Via the CLI through a new flag: `panda cssgen --minify --outfile dist/styles.css`
Or through the existing [`minify` config option](https://panda-css.com/docs/references/config#minify)

**Comment by anubra266** [comment]
@jonambas https://panda-css.com/docs/references/cli#--minify

**Comment by jonambas** [comment]
@anubra266 That's for the wrong command, my question is about `panda cssgen` which doesn't minify.

That said `panda --minify` also doesn't seem to minify CSS. Please reopen 🙏

**Comment by adbutterfield** [comment]
I was just looking through issues because I noticed the same thing. `panda --minify` does not minify. Setting `minify: true` in `panda.config.ts` also does not minify.
