### ISSUE TITLE
Make package.json version generation deterministic

### ISSUE THREAD

**Issue by Pinpickle** [chakra-ui/panda#1249]
### Description

I'd like the `package.json` for `emitPackage` to be deterministic so that version control can better track when the design system has changed.

### Problem Statement/Justification

Setting `emitPackage` to true emits a `package.json` file with a version set. This comes from `performance.now`.

https://github.com/chakra-ui/panda/blob/75ba44deccc9424bb0ac54a6008b4d472af2ab6b/packages/generator/src/artifacts/pkg-json.ts#L11

I commit the `package.json` file to Git so `pnpm install` works. However, it changes frequently over the course of normal development due to the non-deterministic nature of performance.now.

I'd like for the `package.json` version only to change when the contents of the generated code would have changed. This is especially helpful for triggering builds with tools like Turborepo that only rebuild when dependencies have changed.

### Proposed Solution or API

Ideally, the version emitted would be `0.0.0-{hash}` where `{hash}` is some hash of all the files emitted by `panda codegen`. 

### Alternatives

I've implemented this in a script that runs after `panda codegen`. It gets the hash of all of the files in the emitted package and sets that to the version. I have noticed that there are other times that panda writes `package.json`, though.

Having some kind of hook that executes after `package.json` is written to, so I we can run scripts to edit it reliably.

**Comment by yandif** [comment]
Is it possible to provide a configuration to customize the generated package.json template?

**Comment by segunadebayo** [comment]
I've gone ahead to implement a new hook `generator:done`, you can use this hook to update the package json as needed.

```js
// panda.config.ts
defineConfig({
  //...
  hooks: {
      'generator:done': () => { 
      // do stuff like updating package.json
     }
  }
})
```

**Comment by Pinpickle** [comment]
@segunadebayo would it be possible to access the generated artifacts in this step? Otherwise we'll have to read them all from the file system (in this case to generate the hash from the generated files).
