### ISSUE TITLE
Dynamic styling with JSX Style Props not working for property "size"

### ISSUE THREAD

**Issue by pvandamme** [chakra-ui/panda#1260]
### Description

I want to pass a dynamic `size` property to a children component, when I pass the property as props, the width and height class names are correctly set to the desired component: `w_16 h_16` for `size={16}` but they are not added to the final css file.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-ngtdmr?file=src%2FCustomCircle.tsx

### Steps to reproduce

1. Go to the stackblitz link
2. You can see there is no Circle
3. Open your console
4. Search for the desired <div />
5. Look styles

### Panda CSS Version

0.11.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
Hey, 2 things here:

1 - you need to tell Panda that `CustomCircle` is using the `circle` pattern, you can do so in your panda.config

```ts
patterns: {
    extend: {
      circle: {
        jsx: ["Circle", "CustomCircle"],
      },
    },
  },
```

2 - there was an issue in our side related to the above fix
https://github.com/chakra-ui/panda/pull/1267

**Comment by pvandamme** [comment]
@astahmer Thanks for the fast answer, it looks like the fix isn’t working, i've updated my stackblitz as you recommended so u can check it out !

**Comment by segunadebayo** [comment]
The fix is not released yet @pvandamme. It should go out in a few hours and you can try it again.
