### ISSUE TITLE
Order of injection is wrong

### ISSUE THREAD

**Issue by OhadBaehr** [chakra-ui/panda#1275]
### Description

Injection order start from the highest component then the children instead of traversing the whole tree and injecting styles from the leafs to the root.

Made a reproduction snippet with a styling pattern I found rather intuitive and I think it would be a shame if this wouldn't be supported. 

### Link to Reproduction

.

### Steps to reproduce

```typescript
const buttonStyle = cva({
    base: {
        color: 'red',
        textAlign: 'center'
    },
    variants: {
        size: {
            small: {
                fontSize: '1rem'
            },
            large: {
                fontSize: '2rem'
            }
        }
    }
})

export const Button = ({ className, ...props }) => {
    return (
        <button className={cx(buttonStyle({ size: 'small' }), className)} {...props}>
            Click Me
        </button>
    )
}

export default function Home() {
  return (
    <main>
      <Button className={css({
        color: 'blue',
      })}>HIII</Button>
    </main>
  )
}
```

Should intuitively result in the color being blue but will always be red.

### JS Framework

React (TS)

### Panda CSS Version

0.13.0

### Browser

Google Chrome 93

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@OhadBaehr `cx` just concatenates strings, you'll notice that if you inspect the browser html.
Check out the right way here: https://play.panda-css.com/5fhsfmeSLy
Docs link at the top

**Comment by OhadBaehr** [comment]
Thanks, that completely solved my problem!
Is it in the docs somewhere?
