### ISSUE TITLE
Highlight NextJS custom fonts placements

### ISSUE THREAD

**Issue by kipprice** [chakra-ui/panda#1282]
### Subject

Custom Fonts

### Description

Hi PandaCSS team (love the library!)

I've spun up multiple projects that have styles powered by Panda, and I wanted to highlight a 'gotcha' that has bitten me multiple times. NextJS is my framework of choice, and overall, it is a breeze to set up with Panda. However, the boilerplate App Router project generated via `create-next-app` includes a default font setup that does not work with Panda (fonts are included in the `<body>` tag rather than the `<html>` tag). The [docs](https://panda-css.com/docs/guides/fonts#app-router) appropriately call out that the fonts should be in the `<html>` tag; however, I've found that it's easy to miss that specification as the default (but incorrect) code looks very similar at a glance.

This is what Next generates by default:
```tsx
...
const inter = Inter({
  subsets: ['latin'],
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <StrictMode>{children}</StrictMode>
      </body>
    </html>
  );
}
```

And the change that seems intuitive when not reading carefully (but will not load custom fonts):
```tsx
...
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${inter.variable}`}>
        <StrictMode>{children}</StrictMode>
      </body>
    </html>
  );
}
```

When in fact it should be:
```tsx
...
const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter'
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${inter.variable}`}>
      <body>
        <StrictMode>{children}</StrictMode>
      </body>
    </html>
  );
}
```

I would propose adding a callout to [this section](https://panda-css.com/docs/guides/fonts#app-router) highlighting that, by default, Next tries to load fonts in the body, but for panda to appropriately load fonts, they need to be swapped to the `<html>` element. I'm happy to open a PR to make this change.

Thanks for creating such a great library! It saves me literal hours every day :)

**Comment by jhegele** [comment]
@kipprice many, many thanks for this write up and I completely agree that it would be great to highlight this in the docs. I just spent an hour trying to debug why my fonts weren't loading properly and went through the docs at least 10 times double checking things. I **completely** missed that the fonts had been moved from `<body>` to `<html>`.

**Comment by segunadebayo** [comment]
Great suggestion @kipprice.

I've updated the docs as needed.
