### ISSUE TITLE
Hash not applied to CSS variables when using negative syntax

### ISSUE THREAD

**Issue by jonambas** [chakra-ui/panda#1294]
### Description

When I use a negative token value such as `marginLeft: '-sm',` along with `hash: true` set in config, I expect the class names produced by `panda cssgen` to be hashed. Instead, the non-hashed css variable is used.

```ts
// panda.config.ts
export default defineConfig({
  theme: {
    tokens: {
      spacing: {
        sm: { value: '1rem' },
        md: { value: '2rem' },
      },
    },
  },
  hash: true,
}
```

```ts
// CSS
const styles = css({
  padding: 'sm',
  marginLeft: '-sm',
});
```

```ts
// styled-system/styles.css
.fzBPom {
    padding: var(--jolVMp)
}

.dVvtuO {
    margin-left: calc(var(--spacing-sm) * -1) // This should referencing var(--jolVMp)
}
```

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-tp9rs7?file=styled-system%2Fstyles.css

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-tp9rs7?file=styled-system%2Fstyles.css
2. Let `npm install` and `panda codgen && panda cssgen` run
3. Open the `styled-system/styles.css` file
4. See the CSS generated

### Panda CSS Version

0.13.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @jonambas,

I just pushed a fix for this. I'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
