### ISSUE TITLE
`hideBelow` is responsive to incorrect breakpoints

### ISSUE THREAD

**Issue by hobbescodes** [chakra-ui/panda#1301]
### Description

When I use `hideBelow: 'md'` or `hideBelow="md"`, I expect the element to hide responsively on the `md` breakpoint (not inclusively, defaults defined [here](https://panda-css.com/docs/concepts/responsive-design#:~:text=Panda%20provides%20five%20breakpoints%20by%20default%3A)), but instead it responds to the breakpoint that is one level above (i.e. `hideBelow="md"` is responsive on the `lg` breakpoint).

### Link to Reproduction

https://play.panda-css.com/ZkLH0TJfET

### Steps to reproduce

1. Go to [reproduction link](https://play.panda-css.com/ZkLH0TJfET)
2. Select `Preview` view
3. Adjust `Preview` to the `lg` breakpoint value (`1024px`), and tinker back and forth around that breakpoint.
4. See error. It is responsive to the `lg` breakpoint even though `md` breakpoint (`768px`) is passed.

### Panda CSS Version

0.13.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by willTastyMakers** [comment]
I too am experiencing this issue, but  I have noticed even though I have it set to `md` =  768px , for displayBelow, the display will disappear at `lg` sometimes even before  randomly between `lg` and `xl` and it happens differently for laptop monitor vs desktop monitor.

**Comment by willTastyMakers** [comment]
Thanks for the update
