### ISSUE TITLE
CSS custom properties aren't escaped properly

### ISSUE THREAD

**Issue by theMosaad** [chakra-ui/panda#1311]
### Description

When I add a string key with symbols in `theme.extend.tokens.sizes` i.e. `'100%'`, I expect Panda to compile and allows me to use it in the css function as so
```jsx
<span 
  className={css({width: '100%'})}
>
...
</span>
```

Instead, it produces the unescaped CSS custom property `--sizes-100%` instead of `--sizes-100\%` which doesn't work. 

When I try to manually escape it like so `'100\%'`, it produces same output.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-ypxbmx?file=panda.config.ts,src%2FApp.tsx&terminal=dev

### Steps to reproduce

Inspect the CSS output of the reproduction to see CSS syntax errors for width not being applied.

### JS Framework

Vite (TS)

### Panda CSS Version

0.13.1

**Comment by segunadebayo** [comment]
You can use a double backslash as a workaround for now .`100\\%`
