### ISSUE TITLE
CSS not generated with a recipe.jsx regex match

### ISSUE THREAD

**Issue by mleralec** [chakra-ui/panda#1315]
### Description

Props passed to a styled-component generate classes but not CSS when the name of the component matches the regex of a recipe.jsx field. 

This following code works without **recipes** in the configuration. But, if you have a recipe with something like that: `jsx: [/Button.*/]`, the class `bg_pink` doesn't exist in the output CSS.

```tsx
type ButtonProps = HTMLStyledProps<"button">;
const StyledButton = styled("button", { base: { padding: "md" } });

const Button = ({ children, ...props }: ButtonProps) => (
  <StyledButton {...props}>{children}</StyledButton>
);

const TomatoButton = (props: ButtonProps) => (
  <Button backgroundColor="tomato" {...props} />
);

export const Test = () => {
  return (
    <div>
      {/* works: background-color: tomato */}
      <TomatoButton>Button</TomatoButton>
      {/* works: background-color: yellow */}
      <Button backgroundColor="yellow">Button</Button>
      {/* doesn't work, "bg_pink" class is present but no CSS generated  */}
      <TomatoButton backgroundColor="pink">Button</TomatoButton>
    </div>
  );
};

```

### Link to Reproduction

https://play.panda-css.com/O9kEjz3vuP

### Steps to reproduce

Open the reproduction link, remove the **buttonRecipe** of the configuration and it works.

### JS Framework

React (TS)

### Panda CSS Version

0.13.1

### Browser

Google Chrome 116

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by hmiller020414** [comment]
I am facing a similar issue with no relation to recipes or regex.

I've built a test example as follows.
```
export const TestBox = ({ cssProps }: { cssProps: SystemStyleObject }) => (
  <div className={css({ padding: 8, bgColor: 'orange', color: 'yellow' }, cssProps)}>
    <p>This is my box</p>
  </div>
);

<TestBox cssProps={{ position: 'absolute', top: '33px' }} />
```

The class `top_33px` is generated in the HTML, but the class `top_33px` does not exist in the output CSS.

**Comment by astahmer** [comment]
that's not related

> @astahmer I am facing a similar issue with no relation to recipes or regex.
> 
> I've built a test example as follows.
> 
> ```
> export const TestBox = ({ cssProps }: { cssProps: SystemStyleObject }) => (
>   <div className={css({ padding: 8, bgColor: 'orange', color: 'yellow' }, cssProps)}>
>     <p>This is my box</p>
>   </div>
> );
> 
> <TestBox cssProps={{ position: 'absolute', top: '33px' }} />
> ```
> 
> The class `top_33px` is generated in the HTML, but the class `top_33px` does not exist in the output CSS.
> 
> If this is corrected or expected behavior, can you please point me to the correct section of the documentation to read? Thanks!

that's not related, you need to either use `css` as prop (special case for convenience) or use `css.raw` when using another unknown property (ex: `rootProps`, `buttonProps` or yours: `cssProp`)
https://panda-css.com/docs/guides/dynamic-styling#alternative

see https://play.panda-css.com/ESEeM8tG4D

**Comment by hmiller020414** [comment]
Thank you very much! I appreciate the speedy response. .raw() works great for our use case!
