### ISSUE TITLE
Code generation seems to be picking up non-Panda styled components and generating invalid CSS

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/panda#1325]
### Description

I'm using both Chakra UI and Panda CSS in the same product right now, mostly because I want the RSC support from Panda but also some of the client side functionality of Chakra. It's a work in progress and a gradual transition, but Chakra is going to exist in the codebase for the foreseeable future.

But I've noticed a weird issue recently, it seems that Panda's code scanning is picking up semantic tokens from Chakra components and generating CSS. The problem is, these tokens don't exist in my Panda theme extensions, so it just drops the literal value there instead.

Example: https://github.com/Southclaws/storyden/blob/b5f7989c23e32c413c9356d218687d01e62e11a4/web/styled-system/styles.css#L92-L94

```css
  .max-w_container\.sm {
    max-width: container.sm;
  }
```

Here, `container.sm` is a token from Chakra. And it's only used twice:
1. https://github.com/Southclaws/storyden/blob/b5f7989c23e32c413c9356d218687d01e62e11a4/web/src/components/Navigation/Navpill/components/Menu.tsx#L15
2. https://github.com/Southclaws/storyden/blob/b5f7989c23e32c413c9356d218687d01e62e11a4/web/src/components/Toolpill/Toolpill.tsx#L46

Which are both "use client" components that _only_ use Chakra <Flex> components where `container.md` is a valid semantic token.

Now, my short term solution for this is simple: I can define `container.sm` as a token in Panda, or I can simply remove their usage from my two Chakra components and everything is fine.

### Link to Reproduction

https://github.com/Southclaws/storyden/blob/main/web/styled-system/styles.css#L92-L94

### Steps to reproduce

Chakra and Panda in the same project, with a `maxW="container.md"` prop, or any other prop where the name of the component and the prop is the same between Chakra and Panda (Flex and maxW for example)

### JS Framework

React (TS)

### Panda CSS Version

0.12.2

### Browser

Irrelevant - codegen issue

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by astahmer** [comment]
havent tried on your reproduction yet but this should be fixed with https://github.com/chakra-ui/panda/pull/1310 and has been released in 0.14.0 https://github.com/chakra-ui/panda/pull/1292 20mins ago

**Comment by Southclaws** [comment]
Ah perfect! Yes this is working now after updating, thank you!
