### ISSUE TITLE
panda codgen runs the server build of solid.js

### ISSUE THREAD

**Issue by navaru** [chakra-ui/panda#1335]
### Description

When loading a recipe that contains imports from `@ark-ui/solid`, `panda codegen` loads the server build version of solid, which doesn't provide the required exports.

```
✘ [ERROR] No matching export in "node_modules/.pnpm/solid-js@1.7.11/node_modules/solid-js/web/dist/server.js" for import "template"

    node_modules/.pnpm/@ark-ui+solid@0.10.1_solid-js@1.7.11/node_modules/@ark-ui/solid/tags-input/tags-input-control.mjs:1:62:
      1 │ ...spread, mergeProps as mergeProps$1, template } from 'solid-js/web';
```

When I manually remove the `node` exports from `node_modules/solid-js/package.json` it works as expected.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-z8khkc?file=src%2Frecipes%2Favatar.ts

### Steps to reproduce

run `panda codegen` in the terminal

### JS Framework

Solid (TS)

### Panda CSS Version

0.14

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @navaru,

This error shows that esbuild, the library we use internally to bundle the panda.config file is having a hard time resolving the anatomy imports as it goes through the module dependencies/files.

I'd recommend extracting that anatomy manually and using it in your code.

Thanks
