### ISSUE TITLE
Missing `strokeWidth` from `SystemProperties` type

### ISSUE THREAD

**Issue by rudeayelo** [chakra-ui/panda#1337]
### Description

I'm styling an SVG element and the `strokeWidth` property seems to be missing from the `SystemProperties` type definition that's generated by the `codegen` command:

![CleanShot 2023-09-08 at 12 09 23@2x](https://github.com/chakra-ui/panda/assets/140042/8cf70579-0252-470a-9542-e73db62f9b4d)

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-eqkrvv?file=src/App.tsx&terminal=dev

### Steps to reproduce

Write a `strokeWidth` property in a `cva`/`css` declaration and see the TS error popping up in the IDE.

I tried to reproduce in a StackBlitz container but TypeScript is not as picky there.

### JS Framework

React (TS)

### Panda CSS Version

0.9.0

### Browser

Not relevant

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @rudeayelo,

Kindly update the latest version. Svg properties are supported there.

Thanks
