### ISSUE TITLE
Slot Recipe doesn't apply rules when variant name has the same as a slot

### ISSUE THREAD

**Issue by navaru** [chakra-ui/panda#1341]
### Description

When a Slot Recipe has a slot and a variant with the same name the rules for the slot are not applied.

### Link to Reproduction

https://play.panda-css.com/PSgke8ZAkl

### Steps to reproduce

When calling the Button component with the `icon` attribute (`<Button icon></Button>`), the rule `recipe.variants.icon.true.icon` does not apply.

### Panda CSS Version

0.14

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @navaru,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
