### ISSUE TITLE
Generating invalid syntax "mediascreenand"

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/panda#1345]
### Description

I've hit an interesting new bug, I noticed a lot of styles suddenly stopped working in production. Particularly, one of my media query driven layouts that should hide and show the device-specific navigation component, which falls back to mobile.

Checking the actual css, I can see why the styles aren't loading, the syntax is not even valid CSS. Several instances of `@media screen and (...` have turned into `@mediascreenand(...` which is very odd.

Annoyingly, I can't reproduce this locally, it generates fine:

<img width="158" alt="image" src="https://github.com/chakra-ui/panda/assets/1636971/0d3c7e6f-9fed-4f8d-8a5c-ff897e14ea58">

However, the live site, built with the exact same Next.js, Panda, etc versions (I would assume, it's on Vercel so... who knows what they're doing)

<img width="291" alt="image" src="https://github.com/chakra-ui/panda/assets/1636971/16879d99-9f7b-4e53-9fb9-a054965529f9">

Perhaps a minification issue? But I've never seen this, either with Panda or any other CSS tooling.

### Link to Reproduction

https://demo.storyden.org/_next/static/css/1e6cc1a8cc0d24b0.css

### Steps to reproduce

Apologies I cannot get a proper repro working, but this bug is just so weird, no mention of it anywhere and searching for the phrase `mediascreenand` only surfaces a single GH issue on a seemingly unrelated project: https://github.com/jgm/pandoc/issues/2301

It could be a Next.js issue, so I'm mainly opening this here to try to rule out Panda first.

### JS Framework

Next.js

### Panda CSS Version

0.14.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@Southclaws your reproduction doesn't seem to contain this issue
![Uploading CleanShot 2023-09-10 at 21.35.21@2x.png…]()

**Comment by segunadebayo** [comment]
After digging into this slightly, it seems related to the CSS minification in Next.js (perhaps SWC). I can confirm that Panda generates the correct CSS.

Kindly move the issue to the Next repo for further investigation.

**Comment by Southclaws** [comment]
Thanks for ruling out Panda! That's odd that it suddenly rendered properly again, I haven't pushed any changes since I opened this issue. I'll pester the Next.js team anyway.
