### ISSUE TITLE
Atomic Recipes do not work when importing values from other files

### ISSUE THREAD

**Issue by navaru** [chakra-ui/panda#1349]
### Description

Don't know if this is a limitation or a bug, currently when using `sva` and importing values from other modules doesn't work.

```
import { checkboxAnatomy } from '@ark-ui/solid'
import { sva } from '../styled-system/css'

export const checkbox = sva({
	slots: checkboxAnatomy.keys(),
})
```

Tho' it works when defining recipes:

```
import { checkboxAnatomy } from '@ark-ui/solid'
import { defineSlotRecipe } from '@pandacss/dev'

export const checkbox = defineSlotRecipe({
	slots: checkboxAnatomy.keys(),
})
```

If this is a limitation, it would be useful to add a note in the documentation.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-4nh1aj?file=src%2Fsva.ts

### Panda CSS Version

0.14

**Comment by anubra266** [comment]
@navaru the whole of Panda works by static extraction, Panda reads your files, so it can't know the value of imported stuff
