### ISSUE TITLE
Memory leak with Next.js, especially after causing a build error

### ISSUE THREAD

**Issue by subvertallchris** [chakra-ui/panda#1359]
### Description

When I save my work frequently, I expect things to keep on compiling but it eventually crashes with an OOM error instead.

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-rduffh?file=app%2Fpage.module.css

### Steps to reproduce

Note: the Stackblitz environment doesn't seem to work. I copied/pasted code from local to there, maybe I missed something. It'll be best to do this from the sample repo, https://github.com/subvertallchris/panda-next-debug.

To reproduce the error:

*   Open your Activity Monitor or whatever tool you use to watch processes
*   Start next.js via \`npm run dev\`
*   Open your code editor to app/layout.tsx
*   Break the layout by removing a character from a closing HTML tag and saving the file
*   Fix the error, save the file
*   Repeat this process of break/fix/break/fix and watch as{" "} next-render-worker-app {" "} consumes more and more memory
*   Stop your server, disable the PostCSS plugin in{" "} postcss.config.cjs , remove the hidden{" "} .next directory {" "} and restart the server. Try to reproduce it. {"You'll"} see the process tick up a little bit but not much.

### JS Framework

Next.js 13 (TS)

### Panda CSS Version

0.14.0

### Browser

Chromium 116

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

In my work project, I'll hit 4GB and crash quickly. I can't say for sure if this is an issue with Next.js, Webpack, PostCSS, or some configuration, but I thought I'd start here. I've noticed this for well over a month across versions. It happens frequently as I save the project but something about errors seems to really exacerbate it.

**Comment by segunadebayo** [comment]
I looked into this today, and the issue lies in the intersection of Next.js and PostCSS.

No traces of the issue coming from Panda. Kindly open this for investigation with the Next.js team.

**Comment by subvertallchris** [comment]
Thanks for looking into it! I'll send it their way.
