### ISSUE TITLE
css.raw assigned to variable passed to child selector in another css.raw results in no style

### ISSUE THREAD

**Issue by osdiab** [chakra-ui/panda#1370]
### Description

Child selectors with `&` work, but when you refer to another `css.raw()` created style in a child selector, it doesn't.

### Link to Reproduction

https://play.panda-css.com/1S1unfZ5Xs

see that the `p` elements are getting it since i inlined it, but the `h2` style isn't being applied.

### Steps to reproduce

1. put one `childStyle` in a `css.raw()`
2. refer to it in a parent style with child selectors, like `"& p": childStyle`
3. see that the desired style fails to be applied
4. inline the same style
5. see that it works

### JS Framework

React (TS)

### Panda CSS Version

0.15.0

### Browser

Arc 1.7.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by osdiab** [comment]
I see; that's unfortunate though, as that makes style composition for child selectors different than for other circumstances.

What I'd like is to be able to do things like this:

```ts
// these styles can be reused in non-text-document circumstances, UI elements all over my app
export const hyperlinkStyles = cva({ /* ... */ });
export const textStyles = cva({ base: {}, variants: {type: {h1: ..., h2: ..., ... });

const paragraphSpacingCss = css.raw({ /* ... */ });

// this style is intended specifically for large bodies of text
export const proseCss = css({
  maxWidth: "80ch",
  "& a": hyperlinkStyles.raw(),
  "& p": css.raw(paragraphSpacingCss, textStyles.raw({type: "p"})),
  "& h1": css.raw(paragraphSpacingCss, textStyles.raw({type: "h1"})),
})
```

While I am able to achieve this instead by using plain objects and splatting them with `...` operator to combine styles, it's not really consistent with the newly introduced `css.raw()` stuff, which is a bummer.

Is this a hard limitation of how the compiler works? Would be cool if nested styling link this worked the same way that other styles do.

**Comment by segunadebayo** [comment]
I see your point @osdiab.

It's worth pointing out that the `.raw()` things **should be used as a compiler hint, not composition**. Extraction and style generation happen at the `.raw()` call point, which breaks the composition story.

We can go down the rabbit hole to get `.raw()` to work with composition within the `css` fn, but this will lead to a lot of complexity in the compiler code.

There are a couple of ways around this:
- Use the simpler approach @astahmer suggested above
- Refactor the code by moving the `& p` into the `css.raw` call
- Move all text-based styles to the `textStyles` in Panda as shown here:  https://panda-css.com/docs/theming/text-styles, and use those textStyles in your styles.

Thanks for understanding.

> In the future, we'll consider improving the compiler to handle this better.
