### ISSUE TITLE
Playground crashing when using `sva`

### ISSUE THREAD

**Issue by brendon1555** [chakra-ui/panda#1373]
### Description

When I attempt to use `sva` in the playground, a client-side exception occurs.
```
TypeError: Cannot read properties of undefined (reading 'map')
```
The crash appears to be happening here: https://github.com/chakra-ui/panda/blob/main/packages/shared/src/slot.ts#L10

Not sure if related, but I also cannot add `recipes` or `slotRecipes` to the config in the playground due to this TS error: `Expression produces a union type that is too complex to represent.`

### Link to Reproduction

https://play.panda-css.com/

### Steps to reproduce

1. Go to https://play.panda-css.com/
2. Start typing `const something = sva(`
3. As soon as you type that last `(`, the playground will crash.

### JS Framework

React (TS)

### Panda CSS Version

0.15.0

### Browser

Google Chrome 116.0.5845.188

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I pushed a fix for this @brendon1555.

About the type complexity, I'll look into that in a bit. Seems odd
