### ISSUE TITLE
Breakpoint breaking shortcuts on flex pattern

### ISSUE THREAD

**Issue by alimtunc** [chakra-ui/panda#1383]
### Description

When I use `direction: column` in a flex pattern like : 

```js
flex({
    sm: {
        direction: 'column'
   },
})
```

It won't work. It appears that panda passes it as is, instead of interpreting it as 'flex-direction'.

<img width="359" alt="Capture d’écran 2023-09-17 à 22 51 07" src="https://github.com/chakra-ui/panda/assets/18298759/9a25908e-205d-465d-8b8a-ec3291e0e06a">

### Link to Reproduction

https://play.panda-css.com/9J8fIRZuKR

### Steps to reproduce

Just use the responsive tool to break it and see that nothing happens

### Panda CSS Version

0.14.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@alimtunc `direction` is a custom attribute for the `flex` pattern. You can do 
```js
flex({ direction: { sm: 'column' })
```
Anywhere else, you have to use existing css attributes or custom ones you defined.
```js
flex({
    sm: {
        fkexDirection: 'column'
   },
})
```

**Comment by alimtunc** [comment]
@anubra266 Yes, I noticed that, but it seems counterintuitive to me that the pattern doesn't recognize the shortcut. Is this the intended behavior or an unintended consequence?
