### ISSUE TITLE
@types/react 18.2.22 breaks types of generated jsx components of patterns.

### ISSUE THREAD

**Issue by JuliusGudni** [chakra-ui/panda#1390]
### Description

Generated JSX components return a type error when used in a project with @types/react 18.2.22.

For example the following code: 
```
<Box bg="neutral.500" color="white" w="40%">
  <p>Hello World!</p>
</Box>
```

Produces the following type error:
```
Box' cannot be used as a JSX component.
  Its type 'FunctionComponent<Omit<HTMLStyledProps<"div">, never>>' is not a valid JSX element type.
```

Note: I do not have time at the moment to submit a reproduction repo (will add it to the issue tomorrow) - just wanted to have it "on file" in case someone else stumbles upon the same error.

### Link to Reproduction

x

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React(TS)

### Panda CSS Version

0.15.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
I've updated the dependencies to use the version listed above and I can't reproduce this.

Kindly send in a reproduction when you can and I'll re-open
