### ISSUE TITLE
`styled` function breaks existing props of wrapped components

### ISSUE THREAD

**Issue by brendon1555** [chakra-ui/panda#1396]
### Description

When I wrap a [Radix Popover Portal](https://www.radix-ui.com/primitives/docs/components/popover) in the Panda `styled` function, the `container` prop of the Portal breaks. It has replaced the type with `'ConditionalValue<string[] | Container | undefined>'` and stopped the prop from working. I'm guessing this is because `styled` is adding the jsx props for styling the styled component, but I would expect that a wrapped component should't have its functionality broken by wrapping it.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-vrbilj?file=src%2FApp.tsx

### Steps to reproduce

1. Go to the stackblitz referenced above.
2. View the `App.tsx` file
3. Look at the type of the `container` prop on the `PopoverPortal` and `PopoverPortalPanda` components.
4. Also observe that the portal is not placed within the container, as if the container prop was not provided.

### JS Framework

React (TS)

### Panda CSS Version

0.15.1

### Browser

N/A Occurs in IDE

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @brendon1555,

This is because `container` is a valid CSS property for styling container queries. See: https://developer.mozilla.org/en-US/docs/Web/CSS/container

I'd recommend that you don't use the styled factory for this purpose. We intend to implement `shouldForwardProp` pretty soon as an escape hatch for issues like this.

You can style the Portal using the `css` function + className.

**Comment by brendon1555** [comment]
Fair enough. I will avoid wrapping the radix primitives with `styled` for now, and look forward to `shouldForwardProp`. In this case it was just saving me from needing to handle the className prop directly, passing in a `sva` and using a context wrapper in the real usage.

**Comment by astahmer** [comment]
working on the `shouldForwardProp` [here](https://github.com/chakra-ui/panda/pull/1405)
