### ISSUE TITLE
media queries don't work in template-literal syntax

### ISSUE THREAD

**Issue by mmkal** [chakra-ui/panda#1406]
### Description

When a CSS attribute is set on the main style definition for a class, and then overridden in a nested media query, the nested media query should "win" when the media query hits, and "lose" when it doesn't.

Instead, the two generated classes seem to have the same specificity and as far as I can tell the winner is arbitrary. I made an example locally and an identical one on play.panda-css.com and the results were flipped.

### Link to Reproduction

https://play.panda-css.com/0d1LhWvrXE - try adjusting the width and note that the div doesn't change colour. (side-note: the draggable middle bar seems a little buggy so easiest way is clicking the mobile view icon and adjusting the rectangle)

### Steps to reproduce

1. Use `'template-literal'` syntax and the react jsx factory
2. Create a component like this:
```tsx
const Test = styled.div`
  width: 500px;
  height: 500px;
  background: red;
  @media (min-width: 700px) {
    background: blue;
  }
`
```
4. Render like `<Test>abc</Test>`
5. Adjust the width of the window
6. Notice that the background colour doesn't change as you do.

### JS Framework

React (TS)

### Panda CSS Version

0.15.1

### Browser

Google Chrome Version 116.0.5845.179 (Official Build) (arm64)

### Operating System

- [X] macOS

### Additional Information

You can see in chrome dev tools the `background: red` winning over `background: blue` where it should lose:

<img width="683" alt="image" src="https://github.com/chakra-ui/panda/assets/15040698/bcdcb5ce-203a-4bbd-8fe1-2ef69acbb50c">

~Seems to me adding a second selector of some kind would fix the specificity problem. e.g. if I add `div.` to the beginning of the selector in dev tools it starts working.~. The problem is there isn't actually a media query for the second selector.

---

Interestingly though, locally red beat blue, but when I deployed to vercel and when I used the panda playground it was just always blue, whether or not the window was over 700px. So there might be a couple of things wrong?

---

Another note: this problem doesn't seem to apply to the `object-literal` syntax.

**Comment by mmkal** [comment]
Looking closer, it seems like a media query isn't generated at all.

object-syntax:

<img width="335" alt="image" src="https://github.com/chakra-ui/panda/assets/15040698/c1f5e8ec-4d6d-44d1-bdd7-f24dfde08528">

template-syntax:

<img width="335" alt="image" src="https://github.com/chakra-ui/panda/assets/15040698/a89deda9-d0eb-4e4c-85b0-50a8ab125514">

Which would explain both problems - the winner is just arbitrary and never changes.

Also, just for a reference here's the same thing working fine in styled-components: https://codesandbox.io/s/styled-component-playground-forked-l9yhq4?file=/src/index.js

**Comment by segunadebayo** [comment]
Thanks for reporting this @mmkal

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
