### ISSUE TITLE
Runtime conditions on style props doesn't update DOM on JSX components (VueJS)

### ISSUE THREAD

**Issue by Vincent-HD** [chakra-ui/panda#1426]
### Description

When I use a generated JSX component and use a runtime condition on style props from a reactive value such as `computed()`, the class isn't updated in the DOM

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-8nw6ph?file=src%2FApp.vue

### Steps to reproduce

Declare a reactive value:
eg:
```Typescript
const counter = ref(0);
setInterval(() => counter.value++, 1000);
```
Then use it inside a styled or pattern JSX component
```html
<styled.div :bgColor="counter % 2 == 0 ? 'green.400' : 'red.400'">
  {{ counter }} is even
</styled.div>
<Flex :bgColor="counter % 2 == 0 ? 'green.400' : 'red.400'">
  {{ counter }} is even
</Flex>
```

### JS Framework

Vue (TS)

### Panda CSS Version

0.15.1

### Browser

Chrome 115

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Note that using `css({})` seems to work properly on native html elements

![vivaldi_oM4KWrr3IC](https://github.com/chakra-ui/panda/assets/61592570/24896a16-1637-467b-906e-b795c5c4619c)

**Comment by Vincent-HD** [comment]
After a really quick look into the code, it seems that it's possibly related to cache, once the component has been rendered once, it's being cached here:
https://github.com/chakra-ui/panda/blob/1ac2011bace0bcf7f1f5c33ca3a11858fa62ba52/packages/generator/src/artifacts/vue-jsx/jsx.ts#L68C1-L70C12
So even if components props has changed, `styledFn(el)` never gets called again and therefor the appropriate class isn't being applied.
I'm not sure at all, I'm far from understanding the codebase, but caching only based on element tags isn't it specific enough ?
(hot reload seems to work after removing caching)

**Comment by Vincent-HD** [comment]
After a really quick look into the code, it seems that it's possibly related to cache, once the component has been rendered once, it's being cached here:
https://github.com/chakra-ui/panda/blob/1ac2011bace0bcf7f1f5c33ca3a11858fa62ba52/packages/generator/src/artifacts/vue-jsx/jsx.ts#L68C1-L70C12
So even if components props has changed, `styledFn(el)` never gets called again and therefor the appropriate class isn't being applied.
I'm not sure at all, I'm far from understanding the codebase, but caching only based on element tags isn't it specific enough ?
(hot reload seems to work after removing caching)

**Comment by segunadebayo** [comment]
Hi @Vincent-HD,

Thanks for such a detailed issue and investigation.

Indeed, it's related to the cache, and removing it solves the problem. Working on fix

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
