### ISSUE TITLE
Unable to extend config utilities after 0.15.2 update

### ISSUE THREAD

**Issue by brendon1555** [chakra-ui/panda#1430]
### Description

My existing utilities config is throwing TS errors after updating to 0.15.2.
`Object literal may only specify known properties, and '$size' does not exist in type 'PropertyConfig'. ts(2322)`

Here is the utilities config
```ts
utilities: {
    extend: {
        $size: {
            values: "sizes",
            transform: (value: string) => ({
                width: value,
                height: value,
            }),
        },
    },
},
```

### Link to Reproduction

https://play.panda-css.com/OisuwgnIk5

### Steps to reproduce

1. Add a custom utility

### Panda CSS Version

0.15.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This does appear to still function ok if you ignore the error, so seems to only be a typing issue.

**Comment by astahmer** [comment]
my bad, sorry about that, yes it's just a type error
