### ISSUE TITLE
`Application error` on docs website

### ISSUE THREAD

**Issue by lukemartin** [chakra-ui/panda#1432]
### Description

When visiting https://panda-css.com/docs/overview/getting-started, the page loads but then immediately errors with the following:

> Application error: a client-side exception has occurred (see the browser console for more information).

Console output:

```
main-e11f1dbb6b49991c.js:1 A client-side exception has occurred, see here for more info: https://nextjs.org/docs/messages/client-side-exception-occurred
K @ main-e11f1dbb6b49991c.js:1
fn @ main-e11f1dbb6b49991c.js:1
componentDidCatch @ main-e11f1dbb6b49991c.js:1
a.componentDidCatch.t.callback @ framework-89e36c2d3cfab578.js:9
lW @ framework-89e36c2d3cfab578.js:9
uX @ framework-89e36c2d3cfab578.js:9
e @ framework-89e36c2d3cfab578.js:9
(anonymous) @ framework-89e36c2d3cfab578.js:9
oU @ framework-89e36c2d3cfab578.js:9
ox @ framework-89e36c2d3cfab578.js:9
x @ framework-89e36c2d3cfab578.js:33
T @ framework-89e36c2d3cfab578.js:33
framework-89e36c2d3cfab578.js:9 Uncaught Error: Minified React error #423; visit https://reactjs.org/docs/error-decoder.html?invariant=423 for the full message or use the non-minified dev environment for full errors and additional helpful warnings.
    at i (framework-89e36c2d3cfab578.js:9:120803)
    at oD (framework-89e36c2d3cfab578.js:9:99097)
    at framework-89e36c2d3cfab578.js:9:98964
    at oO (framework-89e36c2d3cfab578.js:9:98971)
    at oE (framework-89e36c2d3cfab578.js:9:95723)
    at ox (framework-89e36c2d3cfab578.js:9:94278)
    at x (framework-89e36c2d3cfab578.js:33:1364)
    at MessagePort.T (framework-89e36c2d3cfab578.js:33:1894)
i @ framework-89e36c2d3cfab578.js:9
oD @ framework-89e36c2d3cfab578.js:9
(anonymous) @ framework-89e36c2d3cfab578.js:9
oO @ framework-89e36c2d3cfab578.js:9
oE @ framework-89e36c2d3cfab578.js:9
ox @ framework-89e36c2d3cfab578.js:9
x @ framework-89e36c2d3cfab578.js:33
T @ framework-89e36c2d3cfab578.js:33
3main-e11f1dbb6b49991c.js:1 Error rendering page:  Error: Cancel rendering route
    at c (main-e11f1dbb6b49991c.js:1:11783)
    at main-e11f1dbb6b49991c.js:1:11735
    at new Promise (<anonymous>)
    at ea (main-e11f1dbb6b49991c.js:1:11712)
    at main-e11f1dbb6b49991c.js:1:10326
```

All other pages seem to be working correctly, eg:

* https://panda-css.com/docs/overview/why-panda
* https://panda-css.com/docs/installation/cli

Strangely, there are no errors when running a dev or production build locally.

### Link to Reproduction

https://panda-css.com/docs/overview/getting-started

### Steps to reproduce

1. Go to https://panda-css.com/docs/overview/getting-started
1. See error

### JS Framework

n/a

### Panda CSS Version

0.15.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
yeah I noticed that, not sure what's happening yet as I can't reproduce the error locally.
the error only happens with that Getting started pages, other pages (like https://panda-css.com/docs/overview/why-panda) are fine

**Comment by astahmer** [comment]
it should be back, was solved by upgrading next 🤷 
https://github.com/chakra-ui/panda/commit/d6c67b739b7675febcfef51d422c4b8801d69e7a

**Comment by lukemartin** [comment]
Weird 🤔

Thanks for getting it sorted! ✌️
