### ISSUE TITLE
Add minimal example

### ISSUE THREAD

**Issue by ejhammond** [chakra-ui/panda#1452]
### Subject

Minimal example

### Description

Suggestion to build up a minimal example from scratch. See #1449 where I struggled all day to get a minimal setup working.

- Start with an ejected config
- Add a token
- Add a utility to associate the token with a particular css property
- Add a short-name for that property
- Extend "@pandacss/preset-base" to get utility mappings for free
- Extend "@pandacss/preset-panda" to get a default set of tokens for free

**Comment by segunadebayo** [comment]
Thanks for sharing what you would like to see in the docs.

I've gone ahead and added a minimal setup guide to the docs.

We'll improve this doc as we go.
