### ISSUE TITLE
vue: event listeners not working on components created with styled factory

### ISSUE THREAD

**Issue by technorav3nn** [chakra-ui/panda#1455]
### Description

when using `styled` factory like this: 

```ts
import { styled } from "$styled-system/jsx";
import { button } from "~~/styled-system/recipes";

export const Button = styled("button", button);
```

and in ur vue code:
```vue
<script setup lang="ts">
    import { Button } from "../components/ui/button";
</script>

<template>
    <Button @click="console.log(1123)" variant="solid">Hello</Button>
</template>
```
i expected the console.log to be ran in the @click event but it isn't

### Link to Reproduction

https://stackblitz.com/edit/github-ionerh?file=app.vue

### Steps to reproduce

1. open stackblitz
2. open preview in new tab
3. open devtools go to console
4. click first button, doesnt work (no console logs)
5. click second button, does work and console logs (doesnt use `styled` factory)

### JS Framework

Vue (TS and Nuxt)

### Panda CSS Version

0.15.4

### Browser

Chrome 118

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

when `styled-system/jsx/factory.mjs` is generated, at this exact line:
```js
const [forwardedProps, _variantProps, _styleProps, htmlProps, elementProps] = splittedProps.value;
```
console logging `forwardedProps` gives undefined, which im pretty sure is unintended

**Comment by segunadebayo** [comment]
Good catch @technorav3nn,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
