### ISSUE TITLE
translateY & translateX not working

### ISSUE THREAD

**Issue by NiklasPor** [chakra-ui/panda#1462]
### Description

Hey all, great package. I tried to use `translateX` & `translateY` properties, they only set `--translate-y`, but this value isn't used anywhere, also not if `transform` is set to `auto`.

The regular `translate` property works, because it's directly mapped to the `translate` CSS property.

 ```jsx
         <span className={css({
          transform: "auto",
          translateX: "150px",
        })}>Hello from Panda</span>
 ```

### Link to Reproduction

https://play.panda-css.com/T0Z3z3G-XT

### Steps to reproduce

1. Use `translateY` or `translateX` anywhere (check playground)
2. Nothing visible happens

### Panda CSS Version

0.15.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@NiklasPor It's translate, not transform
```
        <span className={css({
         translate: "auto",
         translateX: "150px",
       })}>Hello from Panda</span>
```

**Comment by NiklasPor** [comment]
Thanks, coming from other frameworks I expected it to be different. Should we document that somewhere, or was I just not able to find?
