### ISSUE TITLE
Imperfect recipes tree-shaking

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/panda#1463]
### Description

I just created a Vite project,
then created two recipes:
- Button
- Chip

After that, I used the `Button` recipes in `App.tsx` file.
By running the `npx vite-bundle-visualizer`, following result created:

![image](https://github.com/chakra-ui/panda/assets/22872117/9a765e7a-0018-40c5-be1d-d6c474ee795a)

As can be seen, the `Chip` and `Button` recipes are placed inside the bundle.
I wonder why this happens. The correct behaviour would be purging and removing `Chip` recipe from the bundle since only `Button` component is used in the app.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-n4krty

### Steps to reproduce

1. Create a project and setup PandaCSS
2. Create two recipes and add them to the config
3. Use only one of them in App
4. Build and analyze the bundle size.set up

### JS Framework

React (TS)

### Panda CSS Version

^0.15.4

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @theMasix

I just pushed a fix for this. Here's what it looks like now:
<img width="1719" alt="CleanShot 2023-10-01 at 20 13 00@2x" src="https://github.com/chakra-ui/panda/assets/6916170/106f5596-d951-4620-9ec1-a207cc851667">

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.

**Comment by theMasix** [comment]
Any update on the package release? Is it fixed?

**Comment by anubra266** [comment]
@theMasix Will be released today
