### ISSUE TITLE
preset colors are overwritten after using token

### ISSUE THREAD

**Issue by oil-oil** [chakra-ui/panda#1470]
### Description

When I add tokens to the configuration, using the preset colors in the recipe doesn't work, and I can't seem to reproduce it in the playground because using the token variable after adding tokens doesn't work, contrary to what I've tried locally.

Successfully add the token in the local environment:
![image](https://github.com/chakra-ui/panda/assets/57465570/80904b41-8341-4acd-afa0-39eaf0e42b78)

![image](https://github.com/chakra-ui/panda/assets/57465570/790315a8-8966-4426-8b43-5393f72000af)

In the playground: 
![image](https://github.com/chakra-ui/panda/assets/57465570/f6105155-c7b7-438a-8f92-83952b9999a6)

![image](https://github.com/chakra-ui/panda/assets/57465570/1a737a43-c4f4-4426-b524-1557f89ec589)

I'm using it in a vue project, and this is my dependency information:

```json
"@pandacss/dev": "^0.15.4",
"@vitejs/plugin-vue": "^4.2.3",
"@vitejs/plugin-vue-jsx": "^3.0.2",
"eslint-config-custom": "workspace:*",
"tsconfig": "workspace:*",
"typescript": "^5.0.2",
"vite": "^4.4.5",
"vite-plugin-dts": "^2.3.0",
"vue-tsc": "^1.8.5"
```

### Link to Reproduction

https://play.panda-css.com/G0DJQm2KtA

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

ts

### Panda CSS Version

0.15.4

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by oil-oil** [comment]
I try to update my config from 
```
{
theme: {
      tokens: {
        colors: {
          primary: { value: '#2563eb' }
        }
      }
  }
}
```
to
```diff
{
theme: {
+    extend: {
      tokens: {
        colors: {
          primary: { value: '#2563eb' },
        }
      }
+    }
  }
}
```

This solves my problem of both configuring the token and preserving the original presets, which is perhaps an expected performance, but I wonder if it needs to be emphasized in the documentation.

**Comment by segunadebayo** [comment]
Good catch. We'll update the docs as needed.
