### ISSUE TITLE
Scale number values appends px values for number values

### ISSUE THREAD

**Issue by NiklasPor** [chakra-ui/panda#1472]
### Description

When I tried to use the `scale: 0.5` property to scale something to it's half, it did not work. But other longer syntax worked:

Does **not** work (appends `px`):
- `<Box scale={0.5} />`
<img width="132" alt="image" src="https://github.com/chakra-ui/panda/assets/13211347/5218923d-30e9-4599-8474-06372753c275">

Does work:
- `<Box scale="0.5 0.5" />`
- `<Box scale="0.5" />` (but in the playground I needed to reload the page, because the class name was equal)
- `<Box scale="auto" scaleY="0.5" scaleX="0.5" />`

(Playground examples are with the `css()` syntax, but the problem is the same.)

### Link to Reproduction

https://play.panda-css.com/ACOXFG-BMw

### Steps to reproduce

1. Go to playground
2. See that `scale: 0.5` does nothing and appends `px` falsely.
3. Switch to `scale: '0.5 0.5'` and it works.

**Important:** If you first use the string variant of 0.4 the class will be already generated (and cached in the playground) and you'll have to reload to see the change.

### Panda CSS Version

0.15.4

### Browser

117

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I checked the source below, but could not find where the `px` is coming from.

https://github.com/chakra-ui/panda/blob/08ed849a32ab0f9ad8fda0cf101d56c14960940a/packages/preset-base/src/utilities/transforms.ts#L22

**Comment by lucassodresa** [comment]
And even the `x` and `y` of `translate` and `scale` property is not working properly. It has been used in the css with the prefix `--`

**Example**
<img width="143" alt="image" src="https://github.com/chakra-ui/panda/assets/38632174/7785786f-b57a-48b7-89a1-b6099dc62648">

`--scale-x` is not a css property it should be `scaleX`

it seems some issue with the css generator

**Comment by NiklasPor** [comment]
> And even the `x` and `y` of `translate` and `scale` property is not working properly. It has been used in the css with the prefix `--`
> 
> **Example** <img alt="image" width="143" src="https://user-images.githubusercontent.com/38632174/273033717-7785786f-b57a-48b7-89a1-b6099dc62648.png">
> 
> `--scale-x` is not a css property it should be `scaleX`
> 
> it seems some issue with the css generator

If you'd want to use `scaleX` or `translateX`, you'd have to also set the base property (`scale` or `translate` in this case) to `auto`. This would result in styles like this:

```tsx
css({
   translateX: "140px",
   translate: "auto",
})
```
        

![image](https://github.com/chakra-ui/panda/assets/13211347/e98f706b-69c6-4456-a8cf-a4c85015630e)

This doesn't look connected to the original `px` issue to me 👀

**Comment by segunadebayo** [comment]
Good catch @NiklasPor,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
