### ISSUE TITLE
Predefined pattern components break when altering jsxStyleProps

### ISSUE THREAD

**Issue by Jonas-C** [chakra-ui/panda#1497]
### Description

When trying out the built-in pattern components I encountered empty classes without really understanding why. Turns out this is caused by me setting `jsxStyleProps: 'minimal'` whilst setting up Panda. Is this a bug, or just a side effect of reducing the available features of panda?

### Link to Reproduction

https://stackblitz.com/edit/vite-react-ts-9zokss?file=src%2FApp.tsx

### JS Framework

React (TS)

### Panda CSS Version

0.15.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
https://panda-css.com/docs/references/config#:~:text=When%20set%20to%20%27minimal%27%2C%20only%20the%20css%20prop%20is%20allowed

**Comment by Jonas-C** [comment]
I understand why it happens, but I find it a little odd to still allow usage of the jsx components if they're non-functioning. It's unreasonable to assume that the reader knows how built-in patterns are generated. If they cannot be generated correctly with `jsxStyleProps: minimal`, they shouldn't be generated at all.
