### ISSUE TITLE
Semantic tokens with conditions don't have the condition rule when the syntax is "template-literal"

### ISSUE THREAD

**Issue by adiosneo** [chakra-ui/panda#1505]
### Description

When the syntax in the config is set to `'template-literal'` the generated tokens don't have the rule conditions - `@at-rules` or class rules like `.dark`.
In the example, I set up the following token configuration:
```
theme: {
    tokens: {
      colors: {
        red: {
          value: '#f00',
        },
        yellow: {
          value: '#ff0',
        }
      }
    },
    semanticTokens: {
      colors: {
        reddd: {
          value: {
            base: '{colors.red}',
            _osDark: '{colors.yellow}',
            _dark: '{colors.yellow}',
          }
        }
      }
    }
  },
```
and the output is:
```
@layer tokens {
    :where(:root, :host) {
  --colors-red: #f00;
  --colors-yellow: #ff0;
  --breakpoints-sm: 640px;
  --breakpoints-md: 768px;
  --breakpoints-lg: 1024px;
  --breakpoints-xl: 1280px;
  --breakpoints-2xl: 1536px;
  --sizes-breakpoint-sm: 640px;
  --sizes-breakpoint-md: 768px;
  --sizes-breakpoint-lg: 1024px;
  --sizes-breakpoint-xl: 1280px;
  --sizes-breakpoint-2xl: 1536px;
  --colors-reddd: var(--colors-red)
}

{
  --colors-reddd: var(--colors-yellow)
}

{
  --colors-reddd: var(--colors-yellow)
}
  }
```

The same issue occurs on my local machine.

### Link to Reproduction

https://play.panda-css.com/5s6jS2t2Zn

### Steps to reproduce

1. Go to reproduction example
2. Open devtools
3. Check the `previewCss` property' value in the object in console

### JS Framework

React (TS)

### Panda CSS Version

0.15.5

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I've just added support for conditions in the template-literal mode. This would make semantic tokens work as expected.

We'll release an update shortly. If the issue persists after upgrading, I'll re-open it.
