### ISSUE TITLE
Theme variables for dialog backdrop not working

### ISSUE THREAD

**Issue by NiklasPor** [chakra-ui/panda#1506]
### Description

When I tried to use the `_backdrop` selector, I expected the styling to correctly work, but theme variables do not seem to work correctly.

### Not working 
```tsx
<dialog
  className={css({
    _backdrop: {
      // Theme variables do not work:
      bg: 'red.200',
    },
  })}
>
```

### Working
```tsx
<dialog
  className={css({
    _backdrop: {
      // Default CSS colors work
      bg: 'aquamarine'
    },
  })}
>
```

### Link to Reproduction

https://play.panda-css.com/-iiFJfhL2Z

### Steps to reproduce

1. Go to https://play.panda-css.com/-iiFJfhL2Z
2. Click on 'Open modal'
3. See that background style is not applied
4. Comment in the plain css value `bg: aquamarine`
5. Click on 'Open modal'
6. See that backgorund style is applied

### JS Framework

React (TS) / Qwik

### Panda CSS Version

0.15.5

### Browser

117.0.5938.149 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
https://kilianvalkhof.com/2023/css-html/backdrop-doesnt-inherit-from-anywhere/

**Comment by NiklasPor** [comment]
Ah didn't know that, maybe we can either extend the docs or remove support for the selector 🤔

**Comment by anubra266** [comment]
@NiklasPor I was looking into the possibility of making it work with `cssVarRoot` in the config.



![CleanShot 2023-10-09 at 21 48 46@2x](https://github.com/chakra-ui/panda/assets/30869823/1e16b2b0-4423-4232-902d-ef60e22cbf36)

Then thought of something like `cssVarRoot:":root, :host, ::backdrop"`
But panda currently doesn't handle that well. It just picks off the last selector in the list. Maybe if that is changed in panda, then this approach is best.

**Comment by anubra266** [comment]
@NiklasPor I was looking into the possibility of making it work with `cssVarRoot` in the config.



![CleanShot 2023-10-09 at 21 48 46@2x](https://github.com/chakra-ui/panda/assets/30869823/1e16b2b0-4423-4232-902d-ef60e22cbf36)

But `::backdrop` doesn't seem to work within `:where` or `:is`

Then thought of something like `cssVarRoot:":root, :host, ::backdrop"`
But panda currently doesn't handle that well. It just picks off the last selector in the list. Maybe if that is changed in panda, then this approach is best.
