### ISSUE TITLE
Passing type into a recipe or cva instead of infer from them

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/panda#1509]
### Description

The only guide in the document tells us that there is a way to infer types from `cva` or `defineRecipe` and not pass types into them. I think there is a need to accept types from the outer scope and as a single source of truth for types of variants.

We already have the props (variants) type, Is there a way to use them as a validation type in recipes?

### Problem Statement/Justification

The problem is we can not use our pre-defined types as a source of truth for our PandaCSS cva or recipes and it may end up with type inconsistencies.

### Proposed Solution or API

`cva` or `defineRecipe` should accept type:

```tsx
const Button = cva<ButtonTypes>({})
// OR
const Button = defineRecipe<ButtonTypes>({})
```

**Comment by astahmer** [comment]
not sure I understand the purpose, can you show your use-case through a complete example ?
