### ISSUE TITLE
Bad documentation of tokens usage in template literals

### ISSUE THREAD

**Issue by adiosneo** [chakra-ui/panda#1516]
### Subject

Token Usage

### Description

The example https://panda-css.com/docs/theming/usage#styled-components in the documentation shows this usage of tokens:
```js
const Button = styled.button`
  background: ${token('colors.blue.200')};
`;
```
but this doesn't work and even the Typescript says that the tag function expects only one argument, so the string without expression.

The correct example should be:
```js
const Button = styled.button`
  background: token(colors.blue.200);
`;
```

**Comment by segunadebayo** [comment]
Hi @adiosneo,

That example refers to using Panda with a runtime css-in-js like emotion or styled-components. In that sense, it's not a bad example.

Of course, to get it working with the `styled` factory in Panda, you need to use the string equivalent.

Thanks for bringing it up though.
