### ISSUE TITLE
TypeScript types for `as` missing (or undocumented feature)

### ISSUE THREAD

**Issue by NiklasPor** [chakra-ui/panda#1517]
### Description

When I tried to use `as` in Qwik (or React) on a styled element from Panda, it works, but the typing system is not supporting it. I'm wondering whether the TypeScript types are just missing, or this feature isn't intended.

Anyway, I'd love to use it for classic cases as buttons which point to links and vice versa.

When you run this in the playground:
```tsx
import { Box, Center } from 'styled-system/jsx';

export const App = () => {
  return (
    <Center h="full">
      <Box as="button" bg="gray.100" p="8" rounded="xl">
        <span>🐼</span>
        <span>Hello from Panda</span>
      </Box>
    </Center>
  );
};
```

You're actually receiving a rendered button:
![image](https://github.com/chakra-ui/panda/assets/13211347/1d76d347-b208-4bf7-a939-2d53eb81bb24)

So it already works at least in Qwik & React.

### Link to Reproduction

https://play.panda-css.com/9kibqzikwG

### Steps to reproduce

1. Go to https://play.panda-css.com/9kibqzikwG
2. See that `as` is highlighted red
3. Open the element inspector and take a look at the gray box
4. See that the `Box` is correctly rendered as a `button`:

![image](https://github.com/chakra-ui/panda/assets/13211347/1d76d347-b208-4bf7-a939-2d53eb81bb24)

### JS Framework

React (TS) / Qwik (TS)

### Panda CSS Version

0.15.5

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I found these tests, referencing this feature:
https://github.com/chakra-ui/panda/blob/36252b1d285a0981d65c117f5ac71a7a3cae7bdd/packages/parser/__tests__/jsx-pattern.test.ts#L12

**Comment by astahmer** [comment]
this is intended, the `as` prop is too problematic type-wise, the `asChild` is the recommended approach (although it's not *yet* built-in Panda)

see this related discussion:
https://github.com/chakra-ui/panda/discussions/1060#discussioncomment-6482659

**Comment by NiklasPor** [comment]
Alright, sorry I didn't find the discussion when I was looking for it. I also experienced the TypeScript slowdown (and fan running high) with other typings for the prop. I'll for now simply stay with sharing the recipe and reusing it for differently styled elements 👍 

E.g.

```tsx
export const fancyButtonStyles = cva({...});

export const FancyButton = styled("button", fancyButtonStyles)
export const FancyButtonLink = styled("a", fancyButtonStyles)
```

Still a little bummer for the `Box` and `Center` components. But I'll close this for now, the discussion should be enough to keep open.

**Comment by astahmer** [comment]
tbh I personally feel that sprinkling a few `@ts-ignore` or `@ts-expect-error` above the `as={xxx}` is completely fine, as it's just a type issue and using an alternative could be cumbersome in some places
