### ISSUE TITLE
extended styled components don't have enough specificity

### ISSUE THREAD

**Issue by mmkal** [chakra-ui/panda#1519]
### Description

When I extended a styled-component using template-literal syntax, I expected the specificity of the extended component to "beat" the base component's, but it didn't.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-u2ucps?file=src%2FApp.tsx

### Steps to reproduce

1. Create a styled component like `` const One = styled.div` background: blue; color: green ` ``
2. Create another like `` const Two = styled(One)` color: red ` ``
3. Use the second one
4. See that the generated classNames have the same specificity so the rendered color is (I think) arbitrary

### JS Framework

React (TS)

### Panda CSS Version

0.15.5

### Browser

Google Chrome Version 117.0.5938.92 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I don't know exactly how this should be working, and unfortunately in my repro I couldn't get it to actually have a visual bug - the styles do apply correctly. But they _don't_ apply correctly in my work's project - the "base" component styles beat the "extended" component and it looks wrong.

You can see how that could happen if you right-click and "Inspect element" in the stackblitz repro:

<img width="839" alt="image" src="https://github.com/chakra-ui/panda/assets/15040698/cff0dd45-b651-4525-a858-f17a2670550e">

Note how there are two classes that define `justify-content`, and they both have the same specificity. I think to fix panda would need to _not_ apply the style-class from the base component, or make the selector in the generated styledsheet use both classes for the extended one. Not knowing much about panda internals, I'm not sure though.

**Comment by mmkal** [comment]
My current workaround is to do this:

```tsx
import { styled } from '../styled-system/jsx';

const One = styled.div`
  display: flex;
  width: 300px;
  border: 1px solid black;
  justify-content: center;
`;

const Two = styled(One)`
  &[class] {
    justify-content: flex-start;
  }
`;
```

Which feels very silly, and it will be impractical to do everywhere. But it works because it boosts the specificity for the extended component.

**Comment by brendon1555** [comment]
I ran into the same issues. Seems all recipes have equal specificity so it comes down to order in the css output. I ended up creating a couple of tools to help with the current implementation for atomic classes: 
- https://github.com/brendon1555/panda-preset-unique-utilities
- https://github.com/brendon1555/panda-cx-deduplicator

But these will only help if you add the custom `cx` function to the base component, so not as simple as your example.
eg (using object syntax as thats all I've personally used): 
```jsx
import { cx } from "@brendon1555/panda-cx-deduplicator";
import { css } from "../styled-system/css";
import { styled } from "../styled-system/jsx";

const One = ({
    className,
    ...rest
}) => (
    <styled.div
        className={cx(css({ justifyContent: "center" }), className)}
        {...rest}
    />
);
const Two = styled(One, { base: { justifyContent: "flex-start" } });
```
My class deduplicator also comes with some caveats which might make it not applicable to you given your examples. eg. Can't have hashing enable for panda...

**Comment by mmkal** [comment]
@brendon1555 thanks that looks useful with the object syntax. We're looking into migrating an existing codebase from styled-components to panda so we're following https://panda-css.com/docs/migration/styled-components - so need the intersection of styled-components and panda features to work for us to choose to migrate to panda. We're hoping not to need to migrate every component, just the few that use styled-components only features like dynamic prop interpolation.

**Comment by segunadebayo** [comment]
Working on a PR for this, here's a preview of the result

![CleanShot 2023-10-18 at 22 04 31@2x](https://github.com/chakra-ui/panda/assets/6916170/4a07d237-f4f8-4019-a566-fac07c971ef3)

**Comment by mmkal** [comment]
Nice! (Looks like the fix is to remove the class for the overriden property from the base component?)

I'd be happy to test it out on the repo I found this bug in, so let me know if that'd be helpful and you plan to do a prerelease to npm of https://github.com/chakra-ui/panda/pull/1543. If not I'll just wait for that PR.
