### ISSUE TITLE
Extraneous incorrect classNames added overriding textStyle cva

### ISSUE THREAD

**Issue by cwrichardson** [chakra-ui/panda#1522]
### Description

If you create a cva that sets textStyle and then override it in a JSX component, additional, incorrect classNames are added to the output, e.g., `0:textStyle_2 1:textStyle_x 2:textStyle_l`.

### Link to Reproduction

https://play.panda-css.com/WuS42lQpQA

### Steps to reproduce

Go to the reproduction link and use dev-tools to inspect the generated html for the third line ("This is an h1 with textStyle").

### JS Framework

NextJS (JS)

### Panda CSS Version

0.15.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I marked the Panda version as 0.15.3, which is when it first appeared; but it is still present in 0.15.5.
Special thanks to @astahmer for creating the minimal reproduction.

**Comment by segunadebayo** [comment]
Good catch @cwrichardson.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
