### ISSUE TITLE
Broken style generation for recipe variants on sveltekit

### ISSUE THREAD

**Issue by benjaminpreiss** [chakra-ui/panda#1567]
### Description

I am using recipes that I inject via a preset into the panda config.

The problem is, that the styles of the recipe are only generated partially (except when I hardcode them).

So, my recipe is called `button_buttonWrapper()`.

Calling it like this `button_buttonWrapper({ destructive, hierarchy, size })` does not work, while calling it like this `button_buttonWrapper({ destructive, hierarchy, size: "sm" })` does.

### Link to Reproduction

https://stackblitz.com/~/github.com/benjaminpreiss/untitled-ui-components?initialPath=/buttons

### Steps to reproduce

Run ...
1. `pnpm install`
2. `pnpm dev`
3. `pnpm prepare`
4. `pnpm dev`

Then have a look at the preview on the right (should render the /buttons page).
You'll see that most of the button variants have no padding applied.

Go to `/src/lib/components/ButtonWrapper` and hardcode the size in the `class`: `button_buttonWrapper({ destructive, hierarchy, size: "sm" })`

Only now will the sm styles be generated successfully.

### JS Framework

SvelteKit (TS)

### Panda CSS Version

^0.17.0

### Browser

Brave Browser Version 1.57.62 Chromium: 116.0.5845.180 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
this is by design, Panda works by finding styles usage in your code through a static analysis step
see this page https://panda-css.com/docs/guides/dynamic-styling

You can use `config.staticCss` to generate styles that aren't statically extractable in your code (`config.include`)
https://panda-css.com/docs/guides/dynamic-styling#using-static-css
