### ISSUE TITLE
Breakpoint inconsistency

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/panda#1571]
### Description

I am styling a sidebar to make it responsive. On small screens, I want to hide the navigation, position the sidebar on the top of the screen and display a hamburguer button. I faced some inconsistencies in the way panda handles the breakpoints

![Screenshot from 2023-10-24 09-45-28](https://github.com/chakra-ui/panda/assets/62773200/e67d2e88-cf08-40ff-9ed1-12d6ec8d2fc0)

![Screenshot from 2023-10-24 09-45-37](https://github.com/chakra-ui/panda/assets/62773200/0ba717d1-5461-4779-9488-35ba792318b7)

![Screenshot from 2023-10-24 09-45-46](https://github.com/chakra-ui/panda/assets/62773200/71a1719c-dd76-4861-a139-563df4debb3e)

Notice how on 1023px the sidebar is located in the top of the screen and the navigation is hidden. On 1024px the sidebar is located in the left and the navigation is still hidden. The navigation only appears again on 1025px. 

I presume the inconsistency lies in the way panda handles `lg: {}` and `hideBelow: "lg"`

### Link to Reproduction

https://github.com/FilipePfluck/Bookwise

### Steps to reproduce

1. Clone the repository
2. Run `npm run dev`
3. Check the breakpoints
4. See the inconsistency

### JS Framework

React (TS)

### Panda CSS Version

0.15.1

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by astahmer** [comment]
related https://github.com/chakra-ui/panda/discussions/1523

**Comment by Princesso** [comment]
+1 to this issue. I am facing the same issue.
