### ISSUE TITLE
Atomic recipe variants with enums does not work

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/panda#1572]
### Description

Hello there,

When I try to use enums as a variant value, the class name is properly generated on the JSX side, but the CSS is not.

The issue is occuring in both sva and cva.

If I replace the enum with the string value, everything works as expected.

### Link to Reproduction

https://play.panda-css.com/4A7xKO7CnE

### Steps to reproduce

You can see on the playground link that the JSX is containing the class name but there are no styles attached to it.

### JS Framework

React (TS)

### Panda CSS Version

0.16.0

### Browser

Google Chrome 118

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by astahmer** [comment]
the fix would be to use an object instead of an enum
const Size = {
  S: 's',
  L: 'l',
};

**Comment by fseglard** [comment]
Thanks @astahmer for the workaround.
Is this a limitation of PandaCSS or can we expect to have the enum support at some point?

**Comment by astahmer** [comment]
coming next version probably

**Comment by hjoelh** [comment]
just ran into this, could it be prevented somehow (perhaps with the eslint plugin) if its not going to be supported?
