### ISSUE TITLE
Empty token causes playground to crash

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/panda#1576]
### Description

When I enter an empty token `""` within the config of the Panda playground, the app crashes.

![grafik](https://github.com/chakra-ui/panda/assets/1846056/46db4725-3cea-4916-9ac5-33b431a60a31)

### Link to Reproduction

https://play.panda-css.com/

**Comment by segunadebayo** [comment]
I just pushed a fix for this. Should be live pretty soon
