### ISSUE TITLE
Typo in the doc for background section

### ISSUE THREAD

**Issue by satarovbekzhan** [chakra-ui/panda#1580]
### Subject

Fix typo in bg section

### Description

There is a typo in https://panda-css.com/docs/utilities/background

`bgGradient` and `background-image` deosn't match

![image](https://github.com/chakra-ui/panda/assets/42301364/9916d4ca-9898-4c2f-ad6c-55a04ff2879d)

**Comment by segunadebayo** [comment]
This is not a typo. The bg-gradient property does indeed map to the background image CSS property.
