### ISSUE TITLE
No longer able to add variants to a `styled()` component that extends a `styled()` component

### ISSUE THREAD

**Issue by brendon1555** [chakra-ui/panda#1609]
### Description

Until a recent update this worked fine, but you can no longer add variants in a StyledComponent that extends a StyledComponent. The variant props just get passed onto the element without being captured by panda.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-xeyjea?file=src%2FApp.tsx

### Steps to reproduce

1. Create a StyledComponent with `styled()`
2. Create a second StyledComponent, with variants, passing the first component as the first arg.
3. Try and apply the variant via a jsx prop.
4. Check styles, console and dom

### JS Framework

React (TS)

### Panda CSS Version

0.17.3

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

This appears to have been introduced with 0.17.0 with the styled element composition changes.

**Comment by segunadebayo** [comment]
Good catch, @brendon1555.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
