### ISSUE TITLE
template-literal syntax: comma-separated selectors don't work when multiline

### ISSUE THREAD

**Issue by mmkal** [chakra-ui/panda#1631]
### Description

When I write a styled component like this, it should work but it doesn't:

```tsx
import { styled } from 'styled-system/jsx';

const Test = styled.div`
  background: pink;
  & span,
  & p {
    color: blue;
  }
`;
```

### Link to Reproduction

https://play.panda-css.com/2hKLfSTPoS

### Steps to reproduce

1. Create a styled component
2. Include an inner block with two selectors, separated by a comma
3. Put the two selectors on different lines
4. Observe that they aren't applied

### JS Framework

React (TS)

### Panda CSS Version

17.0.5

### Browser

Google Chrome Version 117.0.5938.92 (Official Build) (x86_64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

If you write the component with the selectors on a single line, it works fine (try adjusting it in the playground or see [this link](https://play.panda-css.com/C1eUHbgPiD)):

```tsx
import { styled } from 'styled-system/jsx';

const Test = styled.div`
  background: pink;
  & span, & p {
    color: blue;
  }
`;
```

This is important to fix because [prettier](https://npmtrends.com/@pandacss/dev-vs-prettier) auto-corrects from the formatting that works to the formatting that doesn't. (Also, anyone migrating from styled components will likely get bitten by this).

**Comment by segunadebayo** [comment]
Good catch @mmkal. Working on the fix in the linked PR
