### ISSUE TITLE
Panda doesn't generate CSS variables for colorPalette

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/panda#1657]
### Description

I'm developing a component library. as we talked about in https://github.com/chakra-ui/panda/issues/1494#issuecomment-1751735448 and https://github.com/chakra-ui/panda/discussions/1611#discussioncomment-7423816, I had to use `colorPalette` and set its color as the `color` prop comes in.

Now here is the Button component

```tsx
// Button.tsx
import { button as buttonRecipe } from '@ui/styled-system/recipes';
import { ButtonProps } from './button.types';
import { cx, css } from '@ui/styled-system/css';

const Button = ({
  children,
  color = 'primary',
  fullWidth = true,
  iconDirection = 'start',
  loading = false,
  rounded = false,
  size = 'md',
  variant = 'contained',
  disabled = false,
  icon,
}: ButtonProps) => {
  const buttonClasses = buttonRecipe({
    color,
    variant,
    iconDirection,
    loading,
    size,
    rounded,
    fullWidth,
    disabled,
  });

  return (
    <button
      data-has-icon={icon}
      className={cx(
        css({
          colorPalette: color,
        }),
        buttonClasses
      )}
    >
      {children}
    </button>
  );
};

export default Button;
```

And here is the usage

```tsx

// App.tsx
import Button from './components/button';

function App() {
  return (
    <Button variant='contained' color='secondary' size='md' fullWidth={false}>
      Test
    </Button>
  );
}

export default App;
```

I noticed that the Panda only generates the variable `color-palette_*` for the default color in the `Button` component (currently `primary`). Then the rendered in `App.tsx` that has the "secondary" color, won't have correct color.

I think it's a bug and all variables for colorPalette should be generated (at least on-demand!). **I renamed the `Button`'s `color` prop to `colorPalette` (I thought it might be a static analyzer issue) but it didn't work as expected and solve the issue.**

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-fkoob6?terminal=dev

### JS Framework

React (TS)

### Panda CSS Version

0.0.0-dev-20231107203501

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @theMasix,

This is by design. The compiler cannot resolve this dynamic assignment:

```jsx
css({
     colorPalette: color,
}),
```

Use the static CSS config option to pre-generate the color palettes you need on demand. You should also consider moving those default values in the button to defaultVariants in the button recipe.

It would be best to test a simpler example to verify that it works as expected. To reopen this issue, please attach minimal reproduction using the playground.

Here's a working contrived examples: https://play.panda-css.com/1EGhWf_YoE

**Comment by theMasix** [comment]
Thanks @segunadebayo for your help.

I have some questions now:

1. Can the compiler assign the right styles if I generate `color-palette_*` variables statically? (Does passing `color` as `colorPalette` cause any issue?)

2. How can I generate these color palettes statically? I couldn't find anything related to generating the colorPalette in your provided example or [Static Generator Doc](https://panda-css.com/docs/guides/static)
