### ISSUE TITLE
panda/studio ark version causes "proxyState is not iterable" error

### ISSUE THREAD

**Issue by fluoxe7ine** [chakra-ui/panda#1679]
### Description

Hi!
I've tried to use pandacss + ark ui to build my own ui kit. My installed version of @ark-ui/react is 1.0.1, but when I am trying to import any component, my console shows an error:
 
![Screenshot 2023-11-15 at 14 50 28](https://github.com/chakra-ui/panda/assets/31725157/264c844e-5817-49e5-a3fa-118e8da668cf)

I've looked in my yarn.lock and saw that panda/studio package requires @ark-ui/react@0.9.0. When downgrading my ark version to 0.9.0, everything works fine.

Using npm instead of yarn also solves the issue.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-7rdwrf?file=src%2FApp.tsx

### Steps to reproduce

1. Go to stackblitz
2. Look at the App.tsx file and try to comment/uncomment Checkbox import
3. Look at the console and check that error appears.

### JS Framework

React (TS)

### Panda CSS Version

0.18.2

### Browser

Arc 1.11.0 Chromium Engine Version 117.0.5938.149

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
We don't use Ark UI in the studio; I wonder why we even have it here.

I've gone ahead to remove it. This issue will no longer exist from the next release.

> Generally speaking the way to fix this is to ensure the same version of Ark is used
