### ISSUE TITLE
Allow font variables to be defined not only on the html element

### ISSUE THREAD

**Issue by BorisZubchenko** [chakra-ui/panda#1687]
### Description

As stated in the [docs](https://panda-css.com/docs/guides/fonts):
> for panda to appropriately load fonts, update the code to attach the `className` to the `<html>` element.

This creates an issue for Storybook, because we work with stories and decorators there. When I was using Tailwind, the class was attached to a decorator.

I found the [following](https://github.com/storybookjs/storybook/issues/1672#issuecomment-1520635802) workaround but unfortunately class names are dynamic (e.g. `__variable_e66fe9`) so we can't define them in an HTML file.

### Problem Statement/Justification

See Description

### Proposed Solution or API

N/A

**Comment by segunadebayo** [comment]
Hi @BorisZubchenko,

This is a documentation issue. Ideally, the recommendation should be to ensure the element that holds the token CSS variables matches the element with the font's className.

To attach the fonts to the body element, you must update the `cssVarsRoot` to something like `body` in your panda config so the variables can be scoped correctly.
