### ISSUE TITLE
Issues with TypeScript exactOptionalPropertyTypes

### ISSUE THREAD

**Issue by BorisZubchenko** [chakra-ui/panda#1688]
### Description

When `exactOptionalPropertyTypes` flag enabled, ts2379 occurs (e.g.  Type 'undefined' is not assignable to type '"small" | "medium").

### Link to Reproduction

provide-a-template

### Steps to reproduce

1. In tsconfig.json, set compilerOptions#exactOptionalPropertyTypes to true
2. Paste the following code:
```tsx
import { type RecipeVariantProps, cva, cx } from 'styled-system/css'

export const editor = cva({
  defaultVariants: {
    size: 'md',
  },
  variants: {
    size: {
      lg: { fontSize: 'md', p: '3.5' },
      md: { fontSize: 'md', p: '3' },
      sm: { fontSize: 'sm', p: '2.5' },
      xl: { fontSize: 'md', p: '4' },
    },
  },
})

export default function Editor({
  className,
  size,
  ...props
}: EditorProps & RecipeVariantProps<typeof editor>) {
  return (
    <Editor
      className={cx(editor({ size }), className)}
      {...props}
    />
  )
}
```
3. Receive an error at the editor({ size }): Type 'undefined' is not assignable to type '"sm" | "md"....'

### JS Framework

React (TS)

### Panda CSS Version

0.18.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

See https://github.com/nextui-org/tailwind-variants/issues/115

**Comment by segunadebayo** [comment]
Hi @BorisZubchenko,

Thanks for bringing our attention to this and adding more context.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after the release, I'll re-open it.
