### ISSUE TITLE
Conditional variants do not work as expected

### ISSUE THREAD

**Issue by bertuccellimatteo** [chakra-ui/panda#1738]
### Description

When using any conditional variant such as _even on a component, the variant is not being applied

### Link to Reproduction

https://play.panda-css.com/iWiRLawpC4

### Steps to reproduce

1. Check out the reproduction link
2. The divs with "2"  and "4" children should have backgroundColor: gray

### JS Framework

React (TS)

### Panda CSS Version

0.19.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch @bertuccellimatteo,

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by bertuccellimatteo** [comment]
> Good catch @bertuccellimatteo,
> 
> I just pushed a fix for this. We'll release an update shortly.
> 
> If the issue persists after upgrading, I'll re-open it.

Thanks, keep up the great work!

**Comment by land-cap** [comment]
Hi, unfortunately it still does not work as expected at least in this specific case.

This is a config recipe with a variant with two options:

```typescript
export const buttonRecipe = defineRecipe({
  className: 'button',
  base: {
    alignItems: 'center',
  },
  defaultVariants: {
    variant: 'solid',
  },
  variants: {
    variant: {
      solid: {
        background: 'colorPalette.default',
        colorPalette: 'accent',
        _hover: {
          background: 'colorPalette.emphasized',
        },
      },
      ghost: {
        colorPalette: 'gray',
        _hover: {
          background: 'colorPalette.a2',
        },
      },
    },
  },
});

// usage
<button className={button({ variant: { base: 'solid', lg: 'ghost' } })}>button</button>;

```

It is expected that for the `lg` viewport, the styles for `ghost` variant would win and override styles for `solid` but it seems that specificity is arbitrary and some styles are not overridden.
