### ISSUE TITLE
jsx factory 'children' defaultProp is not being passed to the created component

### ISSUE THREAD

**Issue by bertuccellimatteo** [chakra-ui/panda#1748]
### Description

The rendered component should contain the `children` passed into jsx factory `defaultProps`

### Link to Reproduction

https://play.panda-css.com/hVPCIKrFbn

### Steps to reproduce

1. Check the reproduction link

### JS Framework

React (TS)

### Panda CSS Version

0.20.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for catching this @bertuccellimatteo.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
