### ISSUE TITLE
docs: inconsistent ordering for utilities section

### ISSUE THREAD

**Issue by aboudard** [chakra-ui/panda#1779]
### Subject

Documentation / Utilities

### Description

The Utilities menu of the documentation is inconsistent, it changes on selection of an item with no logic.

https://panda-css.com/docs/utilities/background

![image](https://github.com/chakra-ui/panda/assets/767767/ec80b5cf-46f9-4837-b1b8-5ffc0b8bbca4)
![image](https://github.com/chakra-ui/panda/assets/767767/4841152e-d932-4ad2-ba7d-9296a345bd90)
![image](https://github.com/chakra-ui/panda/assets/767767/06ab38d5-15d2-42f6-ad79-a3ab19044499)

I watched in the /website section of the repo and didn't find the reason of this behavior.

Obiously, the content of the menu should not change when we select an item.

**Comment by segunadebayo** [comment]
This is a bug in Nextra, the docs framework we use for the documentation.

There are no actions we can take on our end to fix this. I will keep an eye on the Nextra repo to know when this is fixed.

Thanks for reporting it.

**Comment by aboudard** [comment]
Alright, this is consistent with my research, I thought I completely missed the configuration of the menu, and I did not understand ! Thanks for the clarifications, even if this is a bit concerning :)
