### ISSUE TITLE
Webpack HMR on windows shows warning due to invalid dependency path

### ISSUE THREAD

**Issue by refty10** [chakra-ui/panda#1783]
### Description

I have started a new project with next.js app router.
However, when I start the project, I get the following warn output.
The same warn is also output when a hot read is run.

```
PS E:\node\panda-css-in-next-webpack-warning-on-windows> npm run dev

> panda-css-in-next-webpack-warning-on-windows@0.1.0 dev
> next dev

   ▲ Next.js 14.0.3
   - Local:        http://localhost:3000

(node:76620) ExperimentalWarning: The Fetch API is an experimental feature. This feature could change at any time
(Use `node --trace-warnings ...` to show where the warning was created)
 ✓ Ready in 4.9s
 ○ Compiling / ...
🐼 info [hrtime] Extracted in (10.30ms)
 ⚠ ./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/styles/globals.css
Invalid dependencies have been reported by plugins or loaders for this module. All reported dependencies need to be absolute paths. 
Invalid dependencies may lead to broken watching and caching.     
As best effort we try to convert all invalid values to absolute paths and converting globs into context dependencies, but this is deprecated behavior.
Loaders: Pass absolute paths to this.addDependency (existing files), this.addMissingDependency (not existing files), and this.addContextDependency (directories).
Plugins: Pass absolute paths to fileDependencies (existing files), missingDependencies (not existing files), and contextDependencies (directories).
Globs: They are not supported. Pass absolute path to the directory as context dependencies.
The following invalid values have been reported:
 * "E:/node/miyagawa-hc/node_modules/@pandacss/dev/dist/index.mjs"
 * "E:/node/miyagawa-hc/panda.config.ts"

Import trace for requested module:
./src/styles/globals.css.webpack[javascript/auto]!=!./node_modules/next/dist/build/webpack/loaders/css-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[2]!./node_modules/next/dist/build/webpack/loaders/postcss-loader/src/index.js??ruleSet[1].rules[12].oneOf[12].use[3]!./src/styles/globals.css
./src/styles/globals.css
```

For this project, I have created a Github repository with the same status.

https://github.com/refty10/panda-css-in-next-webpack-warning-on-windows

I also tried launching the same project on mac OS.
But the above warn did not occur.
Therefore, I believe that this WARN occurs only on windows.

### Link to Reproduction

https://stackblitz.com/~/github.com/refty10/panda-css-in-next-webpack-warning-on-windows (As Stackblitz is not on Windows,  the issue is not reproduced on this link.)

### Steps to reproduce

1. set up `node -v = 18.10.0` environment in windows 11.
2. Run `git clone https://github.com/refty10/panda-css-in-next-webpack-warning-on-windows.git` .
3. Run `npm run dev`
4. Project is hot read and panda-css outputs static files
5. Warn will be printed.

### JS Framework

Next(TS)

### Panda CSS Version

0.20.1

### Browser

Vivaldi: 6.4.3160.47 (Stable channel) (64-bit) 

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I believe the webpack plugin configuration does not take windows into account.

Also, as a stopgap measure, I tried setting webpack's logging-level to error and panda-css's logging-level to error, but the warn is still output.

**Comment by refty10** [comment]
> can you try setting your [`config.outExtension`](https://panda-css.com/docs/references/config#outextension) to "js"

Thanks for the reply.
I have tried your advice.
I added `outExtension: 'js'` to `panda.config.ts` and still get the same Warning.
CSS content is changed and a warning is output as before when a hot read occurs.

**Comment by astahmer** [comment]
sorry to hear that. It looks like a webpack (used by nextjs) specific issue, maybe css-loader has a hard time with CSS `@layer` ? I'm not sure we can do anything about it

maybe using this ignore comment can help ? https://webpack.js.org/loaders/css-loader/#disable-url-resolving-using-the--webpackignore-true--comment
or maybe opting out of layers could help https://www.npmjs.com/package/@csstools/postcss-cascade-layers

**Comment by refty10** [comment]
> sorry to hear that. It looks like a webpack (used by nextjs) specific issue, maybe css-loader has a hard time with CSS `@layer` ? I'm not sure we can do anything about it
> 
> maybe using this ignore comment can help ? https://webpack.js.org/loaders/css-loader/#disable-url-resolving-using-the--webpackignore-true--comment or maybe opting out of layers could help https://www.npmjs.com/package/@csstools/postcss-cascade-layers

Thanks for the reply.
I added `webpackIgnore: true` to global.css.

```
//src\styles\globals.css

/* webpackIgnore: true */
@layer reset, base, tokens, recipes, utilities;
```
But there is no change, the Warning is still output.

---

How to install this.
https://www.npmjs.com/package/@csstools/postcss-cascade-layers

I could not figure out how to configure panda-css with this plugin.
Perhaps not using global.css and putting @layers in config instead?
It would be great if you could show a sample.

**Comment by BorisZubchenko** [comment]
Having the same issue for a fresh project. `@csstools/postcss-cascade-layers` doesn't seem like a solution since it changes the CSS output.
