### ISSUE TITLE
Fractional width/height in tokens

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/panda#1794]
### Subject

Tokens

### Description

I want to use a fractional width in a semantic token with a breakpoint, so far I've tried this:

```
sizes: {
          sidebarWidth: {
            value: {
              md: "1/3",
              lg: "1/4",
            },
          },
        },
```

But this generates css with literally "1/3" and "1/4" which is invalid css.

<img width="248" alt="image" src="https://github.com/chakra-ui/panda/assets/1636971/711fffc4-b20d-43b9-bea3-e77d6f4463c1">

I also tried `{1/3}` and `{widths.1/3}` but none seem to work.

**Comment by anubra266** [comment]
@Southclaws 
https://panda-css.com/docs/theming/tokens#semantic-tokens:~:text=%F0%9F%92%A1-,To%20reference%20a%20value%20in%20a%20semantic%20token%2C%20use%20the%20%7B%7D%20syntax.,-For%20example%2C%20assuming

**Comment by anubra266** [comment]
@Southclaws The main issue you're facing is that `1/3` does not exist as a token. So you can't reference it in semantic tokens

**Comment by astahmer** [comment]
this could work like this
https://play.panda-css.com/p4D-kUEGhw

**Comment by Southclaws** [comment]
> The main issue you're facing is that 1/3 does not exist as a token

This is what I thought, is it some kind of internal token? I wonder because it works when used on its own as a width.

**Comment by astahmer** [comment]
this is a custom [utility](https://panda-css.com/docs/customization/utilities), defined in the built-in base preset, Abraham sent a link to the source
