### ISSUE TITLE
`recipe.raw` doesn't generate styles in Storybook

### ISSUE THREAD

**Issue by theMasix** [chakra-ui/panda#1801]
### Description

Based on these resources, I should use `recipe.raw` in Storybook to help generator to generate corresponds styles in Storybook:
 - [Official Document](https://panda-css.com/docs/guides/dynamic-styling#alternative)
 - #1057
 - #1746 

An example:
```ts
export const Primary: Story = {
  args: buttonRecipe.raw({
    color: 'primary',
  }),
};
```

It doesn't work!

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-nwgxrx?file=src%2Fcomponents%2Fbutton.stories.ts

### Steps to reproduce

1. Clone the reproduction
2. Run `pnpm storybook`
3. See the `Large` story of `Button` component that is not working

### JS Framework

React (TS)

### Panda CSS Version

0.21.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
seems like you didn't include your `stories` inside of your `config.include`
https://panda-css.com/docs/installation/storybook#configure-the-content

**Comment by theMasix** [comment]
Hey @astahmer . Thanks for your response. My stories are placed inside `components` dir. So everything is included in `config.include` param.

**Comment by astahmer** [comment]
ah yes sorry, since the stackblitz is missing some storybook files it cannot run and I tried to quickly guess

after downloading the repro, running storybook init and trying things I found the issue
seems like we don't currently handle aliases with `.raw()`

---

as a temporary workaround you can do it like this:

```diff
// button.stories.ts
- import { button as buttonRecipe } from '@ui/styled-system/recipes';
+ import { button } from "@ui/styled-system/recipes";

// ...
// More on writing stories with args: https://storybook.js.org/docs/writing-stories/args
export const Primary: Story = {
-  args: buttonRecipe.raw({
+  args: button.raw({
    color: "primary",
  }),
};

export const Secondary: Story = {
-  args: buttonRecipe.raw({
+  args: button.raw({
    color: "secondary",
  }),
};

export const Large: Story = {
  args: button.raw({
    size: "lg",
  }),
};

export const Small: Story = {
-  args: buttonRecipe.raw({
+  args: button.raw({
    size: "sm",
  }),
};
```


---

FWIW, I think you could dynamically generate all the stories and pre-generate every recipe variants with `config.staticCss`

I have a (currently private) repo doing something like:

```ts
import { Button } from '@pacha/components'
import { Stack } from '@pacha/styled-system/jsx'
import { button } from '@pacha/styled-system/recipes'
import type { Meta, StoryObj } from '@storybook/react'

const variantMapToStorybookSelect = (variantMap: Record<string, string[]>) => {
	const controls = {} as Record<string, any>
	Object.entries(variantMap).forEach(([key, value]) => {
		controls[key] = { control: 'select', options: value }
	})

	return controls
}

const argTypes = variantMapToStorybookSelect(button.variantMap)

const meta = {
	title: 'Components/Button',
	component: Button,
	argTypes,
	args: {
		children: 'Hello 🐼!',
	},
	tags: ['autodocs'],
} satisfies Meta<typeof Button>

export default meta
type Story = StoryObj<typeof meta>

export const Default: Story = { args: {} }

export const Variants: Story = {
	render: () => {
		return (
			<Stack gap="2">
				{Object.entries(button.variantMap).map(([key, value]) => {
					return (
						<div key={key}>
							{key}
							<Stack direction="row" key={value} gap="2">
								{value.map((variant) => {
									return (
										<Button colorPalette="blue" variant={variant} key={variant}>
											{variant}
										</Button>
									)
								})}
							</Stack>
						</div>
					)
				})}
			</Stack>
		)
	},
}
```

it looks like this
![Screenshot 2023-12-11 at 10 04 01](https://github.com/chakra-ui/panda/assets/47224540/36db2ab1-61f7-427d-ae50-8cdb3a97446b)

**Comment by theMasix** [comment]
Thanks for your investigations and efforts. It solved my issue.

It seems we should consider it a bug and find a way to fix it (so the alias shouldn't rune the Panda functionality).

Also, thanks for suggesting this the new way to write storybook stories.

**Comment by astahmer** [comment]
definitely a bug and i'll probably work on it sometimes this week ! thanks for catching this
