### ISSUE TITLE
Regression: Template literal codegen includes invalid imports

### ISSUE THREAD

**Issue by AkeemMcLennon** [chakra-ui/panda#1805]
### Description

In v0.20.1 onwards, the "template-literal" syntax no longer generates a valid `styled-system/jsx/index.js` file. 

In v0.19.0, the contents of the file are 

```typescript
export * from './factory.js';
```

However, in v0.20.1 onwards, the file includes extra exports that don't get generated as part of the `template-literal` configuration. 

```typescript
export * from './factory.js';

export * from './box.js';
export * from './flex.js';
export * from './stack.js';
export * from './vstack.js';
export * from './hstack.js';
export * from './spacer.js';
export * from './square.js';
export * from './circle.js';
export * from './center.js';
export * from './link-box.js';
export * from './link-overlay.js';
export * from './aspect-ratio.js';
export * from './grid.js';
export * from './grid-item.js';
export * from './wrap.js';
export * from './container.js';
export * from './divider.js';
export * from './float.js';
export * from './bleed.js';
export * from './visually-hidden.js';
```

### Link to Reproduction

https://play.panda-css.com/iV5sVMvNCr

### Steps to reproduce

1. Delete the existing `styled-system`
2. Update `panda.config.ts` with the value `  syntax: "template-literal",`
3. Run `panda codegen`

### JS Framework

React (TS)

### Panda CSS Version

0.21.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Thanks for reporting this @AkeemMcLennon

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
