### ISSUE TITLE
`static-css.d.ts` is not being generated in the `styled-system/types` folder

### ISSUE THREAD

**Issue by bertuccellimatteo** [chakra-ui/panda#1815]
### Description

Typescript typecheck fails because in `styled-system/types/recipe.d.ts` RecipeRule is imported from a non-existing file (`styled-system/types/static-css.d.ts`)

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-xzduax?file=styled-system%2Ftypes%2Frecipe.d.ts

### Steps to reproduce

1. Open the reproduction link
2. Go to styled-system/types
3. static-css.d.ts is not present
4. styled-system/types/recipe.d.ts is referencing the non-existing file

### Panda CSS Version

0.21.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Good catch @bertuccellimatteo

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
