### ISSUE TITLE
No CSS generated in Panda 0.22.0

### ISSUE THREAD

**Issue by cschroeter** [chakra-ui/panda#1827]
### Description

When I update from `0.21.0` to `0.22.0` no CSS is generated.

### Link to Reproduction

https://github.com/cschroeter/park-ui/pull/121

### Steps to reproduce

1. Checkout Park UI
2. Update Panda to v `0.22.0`
3. Run `pnpm website dev` 

### JS Framework

React (TS)

### Panda CSS Version

0.22.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

[Preview](https://park-ui-website-git-feat-panda-0-22-0-cschroeter.vercel.app/)

<img width="726" alt="grafik" src="https://github.com/chakra-ui/panda/assets/1846056/e274151c-72d8-4fb8-a83e-c294769dffc6">

**Comment by smarlhens** [comment]
Hey there 👋🏻 , I also have the issue in `0.22.x` in my Vue project using postcss. I'll try to create a repro repo today.
