### ISSUE TITLE
_disabed doesn't work properly

### ISSUE THREAD

**Issue by Kimzify** [chakra-ui/panda#1857]
### Description

according to documentation, the `_disabled` condition should work with `data-disabled` attribute. but `_disabled` styles are rendering in both `data-disabled={true}` and `data-disabled={false}`. Just by passing  `data-disabled={undefined}`, it stops rendering _disabled styles. 

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-fma4fa?file=src%2FApp.tsx

### Steps to reproduce

1. define data-disabled attribute
3. define _disabled style condition
4. check data-disabled={true} and data-disabled={false}. in both the _disabled is rendered. 
5. See the error

### JS Framework

TS

### Panda CSS Version

0.22.0

### Browser

chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@Kimzify To css there's a difference between `<div data-disabled />` and `<div data-disabled="true" />` in your html

`data-disabled={true}` in jsx will compile to `data-disabled="true"` in your html BTW.

Now the equivalent of `<div data-disabled />` is `<div data-disabled="" />` i.e. A value of empty string.

So the right way to use `boolean` data attributes is to either pass empty string or undefined.

```html
<div data-disabled={isDisabled ? "" : undefined} />
<div data-active={isActive ? "" : undefined} />
<div data-selected={isSelected ? "" : undefined} />
```
