### ISSUE TITLE
Vite HMR issue since 0.22.0

### ISSUE THREAD

**Issue by christofferbergj** [chakra-ui/panda#1883]
### Description

Since `v0.22.0`, there seems to be a bug with PandaCSS + Vite dev server. 
I am unsure if it's Vite, Panda, or a combination, but downgrading to `v0.21.0` resolves the issue. 

**Issue:** 
Whenever I change a file, a style or anything that triggers a Hot Module Reload, the initial few HMRs are fast but become increasingly slower with every update. 

After 10-20 HMR, the browser hangs, trying to load the `index.css` file that contains the Panda layer rules. 

I've tried anything I could think of, downgrading several packages, including Vite, disabling Mock Service Worker and numerous other things, but downgrading to Panda `v.0.21.0` resolves the issue. 

I cannot serve a concrete reproduction of the issue, but I hope you have enough context to possibly debug what happened after `v0.21.0` or find that this is entirely unrelated to PandaCSS. 

**Project relevant deps:**
* Vite 5.0.10
* Turborepo 1.11.2
* Typescript 5.3.3

### Steps to reproduce

N/A. 

### JS Framework

React (TS)

### Panda CSS Version

0.22.0

### Browser

Chrome latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![CleanShot 2023-12-27 at 21 46 02@2x](https://github.com/chakra-ui/panda/assets/10507071/68b2783e-58a6-42ce-95f0-aa86762198f7)

**Comment by astahmer** [comment]
hey, we're aware there was a perf regression for the HMR, we're actively working on it here
https://github.com/chakra-ui/panda/pull/1860
