### ISSUE TITLE
Bug?: .gitignore not updated when going through Remix guide

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chakra-ui/panda#1909]
### Description

I'm working on a reference implementation of onboarding https://github.com/philly-js-club/philly-js-club-website to Panda CSS. Very excited about it!

I went through the guide at https://panda-css.com/docs/installation/remix and ended up with the whole `styled-system/` directory checked into source control. Which was surprising given that https://panda-css.com/docs/references/config#gitignore indicates `gitignore`'s default value is `true` to add `styled-system/` to `.gitignore`.

The only reference to `.gitignore` on the Remix page is:

> This step ensures that the panda output directory is regenerated after each dependency installation. So you can add the output directory to your `.gitignore` file and not worry about it.

...which feels to me as an implication we _can_ add the entry to the file - not an indication it will or won't be.

### Link to Reproduction

https://github.com/philly-js-club/philly-js-club-website/pull/85/commits/599ae4a53595460daf3a4b586c3d8cef9eecf1a8

### Steps to reproduce

1. Check out https://github.com/philly-js-club/philly-js-club-website/pull/85/commits/599ae4a53595460daf3a4b586c3d8cef9eecf1a8 locally
2. Go through the Remix getting started guide again
3. note that the `.gitignore` file _isn't_ updated

_(sorry that it's not a Stackblitz repo!)_

### JS Framework

Remix (TS)

### Panda CSS Version

0.24

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@JoshuaKGoldberg I'm not sure I understand what issue you're facing

**Comment by JoshuaKGoldberg** [comment]
Sorry for being unclear! What I'm saying is, I expected the getting-started guide to add at least the following to my `.gitignore`:

```diff
+ styled-system
```

...but it didn't. Which was surprising for two reasons:
* Getting started guides I've experienced before generally have you `.gitignore` any built output _if_ that's the intended way to use the framework.
* The `panda.config.ts` config value for adding to `.gitignore` is described as defaulting to `true`, so I'm surprised it wasn't done for me.

**Comment by anubra266** [comment]
Thanks for clarifying @JoshuaKGoldberg; @astahmer has opened a PR that fixes this. #1914

**Comment by JoshuaKGoldberg** [comment]
Thanks for the quick fix! 🙌
