### ISSUE TITLE
Bug?: Styles not being applied to <body> in Remix

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chakra-ui/panda#1917]
### Description

I'm trying to add styling to the `<body>` tag in a Remix site's `app/root.tsx`. But they're not being applied. Other components and pages are working. I suspect this is a bug: either that it's not working but should, or not giving an informative error but should?

### Link to Reproduction

https://github.com/philly-js-club/philly-js-club-website/tree/0ee0599ef29fa6b013a96989998f277e5345f119

### Steps to reproduce

1. Check out https://github.com/philly-js-club/philly-js-club-website/tree/0ee0599ef29fa6b013a96989998f277e5345f119
2. `pnpm i`, `pnpm codegen --watch`, and `pnpm dev`
3. Open localhost:3000
4. Observe the lack of colors on the body element

Apologies for not using the requested playground or Stackblitz - this wasn't reproducing on either of the suggested links.

### JS Framework

Remix (TS)

### Panda CSS Version

0.24.0

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Screenshot of Chrome showing the Philly JS Club site with black text on a white background. Browser devtools are open showing the body element given a class starting with bg_background.](https://github.com/chakra-ui/panda/assets/3335181/adcbbbf1-ddec-4f3e-98d3-54ca2f6ac374)

**Comment by segunadebayo** [comment]
Hi @JoshuaKGoldberg

Glad to see you exploring Panda 😀.

This is not a bug. I looked at your PR and noticed that you only included “app/routes” and “app/components” in your panda config. Meaning the root.tsx will be skipped by Panda

Maybe switching to app/**/*.ts,tsx might be better?

**Comment by JoshuaKGoldberg** [comment]
D'oh, thanks! 100% user error 😄. I'll file a separate issue about dev tooling giving a complaint in this case.
