### ISSUE TITLE
No indication why textStyles aren't being applied in Remix project

### ISSUE THREAD

**Issue by JoshuaKGoldberg** [chakra-ui/panda#1928]
### Description

Similar to #1917 -> #1925, I've managed to craft a situation where Panda isn't applying some styles as I'd expected. I've probably done something wrong. But I can't figure out where.

It'd be nice if Panda could give some complaint here about how I've misconfigured it. Also... what _is_ the misconfiguration?

### Link to Reproduction

https://github.com/philly-js-club/philly-js-club-website/tree/1df96ebfa39966b65c4b36c13ace1f86b6c6d646

### Steps to reproduce

1. `pnpm i` and `pnpm dev`
2. Open localhost:3000
3. See that the _Next Jawn_ h3 on the homepage isn't underlined

I tried a few variations of similar changes in https://stackblitz.com/edit/vitejs-vite-cq5rda?file=src%2FApp.tsx,panda.config.ts&terminal=dev and they all worked there. But I haven't found the right combination to work in this Remix app.

### JS Framework

Remix (TS)

### Panda CSS Version

0.24.0

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This exposes an improvement we could make in Panda.

The text style value should be a css style object (without token references). Here's a refactored version of the text styles you have in your branch.

```ts
import { defineTextStyles } from '@pandacss/dev'

export const textStyles = defineTextStyles({
  body: {
    value: {
      fontSize: 'medium',
      fontWeight: 'light',
      lineHeight: 'medium',
    },
  },
  large: {
    value: {
      fontSize: 'large',
      fontWeight: 'large',
    },
  },
  larger: {
    value: {
      fontSize: 'larger',
      fontWeight: 'larger',
    },
  },
  medium: {
    value: {
      fontSize: 'medium',
      fontWeight: 'medium',
    },
  },
  smaller: {
    value: {
      fontSize: 'smaller',
      fontWeight: 'smaller',
    },
  },
  underline: {
    value: {
      textDecoration: 'underline',
    },
  },
})
```

In future versions, we'll ensure the token reference syntax works as well since it might be the intuitive thing to do sometimes.

**Comment by JoshuaKGoldberg** [comment]
Cool, thanks for the help!

> @[segunadebayo](https://github.com/segunadebayo) segunadebayo closed this as [completed](https://github.com/chakra-ui/panda/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3Acompleted) [3 hours ago](https://github.com/chakra-ui/panda/issues/1928#event-11388622777)

Err, is there a tracking issue for ensuring the token reference syntax works? I'd meant this as a dev tooling feature request 😅

**Comment by segunadebayo** [comment]
@JoshuaKGoldberg Totally understood that

Please see the attached PR.

**Comment by JoshuaKGoldberg** [comment]
Awesome thanks!
