### ISSUE TITLE
[Studio] ReferenceError: React is not defined

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/panda#1935]
### Description

Hi!

When using the `panda studio` command, I cannot access to the Panda Studio anymore. This error is displayed:

![image](https://github.com/chakra-ui/panda/assets/131656883/223fbf01-7260-45d9-b3e1-053625977130)

After some digging, the Panda Studio was working fine until the v0.22.0 release.

### Link to Reproduction

https://codesandbox.io/p/devbox/pandacss-studio-react-error-gtpt98

### Steps to reproduce

1. Open the reproduction link
2. Run in the terminal the `yarn panda:studio` command (or directly `yarn panda studio`)
3. Notice the error: `ReferenceError: React is not defined`

### JS Framework

React (TS)

### Panda CSS Version

0.24.1

### Browser

Google Chrome 119

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by anubra266** [comment]
@fseglard Do you still have this issue? I can't reproduce it in the latest version

**Comment by fseglard** [comment]
@anubra266 Yes, I still have the issue with the latest version (0.26.2). I've updated the codesandbox: https://codesandbox.io/p/devbox/pandacss-studio-react-error-gtpt98

**Comment by kristojorg** [comment]
I also have this issue in latest (`"@pandacss/studio": "^0.27.3"`)

**Comment by jagregory** [comment]
Also have this issue with 0.27.3. I'm using vite if that's important.
