### ISSUE TITLE
recipe compoundVariants responsive

### ISSUE THREAD

**Issue by mahanfakhimi** [chakra-ui/panda#1941]
### Description

When compoundVariants are added to a Recipe, it loses its responsive property and values cannot be passed in a responsive manner.

 //Type '{}' is not assignable to type '"BRAND" | "BRAND_GRAY" | "STRONG" | "TEXT_STRONG" | "OBVIOUS" | "SUBTLE" | undefined
  
  // In this case it is good
  export type AvatarVariantProps = {
  [key in keyof AvatarVariant]?: ConditionalValue<AvatarVariant[key]> | undefined;
};

//But this problem occurs when compoundVariants are added
export type ButtonVariantProps = {
  [key in keyof ButtonVariant]?: ButtonVariant[key] | undefined;
};

And ConditionalValue type is not applied

### JS Framework

React (TS)

### Panda CSS Version

0.24.2

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@mahanfakhimi Please add a playground reproduction that showcases the issue

**Comment by segunadebayo** [comment]
This is by design @mahanfakhimi.

Recipes with compound variants cannot be applied responsively. I believe it's mentioned in the docs as well.

Consider rendering two versions of the same element and show/hide based on breakpoints, or build the responsiveness into the recipe variants.
