### ISSUE TITLE
Unable to detect changes for import file

### ISSUE THREAD

**Issue by leesiongchan** [chakra-ui/panda#1942]
### Description

When I make changes to the recipe, I expected new changes (styling) to take effect immediately (hot reload) but nothing happened instead.

<img width="547" alt="image" src="https://github.com/chakra-ui/panda/assets/324418/5e64cb3a-e308-4e5a-bfa3-814d5b4625f3">

However, if I import file with extension `.js`, it works as expected. (The source file is `.ts` extension)

### Link to Reproduction

https://github.com/leesiongchan/test-panda

### Steps to reproduce

1. Clone the repository
2. pnpm i && pnpm storybook
3. Try make changes to src/theme/button-recipe.ts
4. See if your new changes take effect

### JS Framework

React (TS) + Storybook (Vite)

### Panda CSS Version

0.24.2

### Browser

Microsoft Edge 120.0.2210.91

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Running in WSL

**Comment by fcisio** [comment]
This bug has reappeared (I'm on 0.27.3).

The 0.27.2 update seems like a likely culprit.

The `.js` fix mentioned above still works.
