### ISSUE TITLE
`css prop` will not work after updating to v0.26.2.

### ISSUE THREAD

**Issue by wancup** [chakra-ui/panda#1990]
### Description

The css prop for merging styles (as described in the documentation at https://panda-css.com/docs/concepts/merging-styles#merging-within-jsx-component) is not working. Instead, it works when using css.raw.

```typescript
<CustomComponent css={{ bg: 'blue' }} /> // <- Not working.
<CustomComponent css={css.raw({ bg: 'green' })} /> // <- Working
```

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-c3ywk5?file=src%2FApp.tsx

### Steps to reproduce

1. Create custom components using the `css prop`.
2. Merge the styles of the `css prop` and the default style in the custom component using the `css function`.
3. Pass the `css prop` from the parent component without using `css.raw`.
4. The specified style in the parent component does not get applied.

### JS Framework

React(TS)

### Panda CSS Version

0.26.2

### Browser

Google Chrome  120.0.6099.216

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
From a quick debugging, this is happening because the `jsxFramework` flag is not set.

Please set `jsxFramework: react` or similar to enable the compiler to parse JSX. 

> In the previous versions, this was an oversight, and we recently made the compiler align with the intended design.

**Comment by wancup** [comment]
It's now working fine with the `jsxFramework` config. Thank you for helping!
