### ISSUE TITLE
Access textStyle from token function

### ISSUE THREAD

**Issue by soheilnikroo** [chakra-ui/panda#1998]
### Description

When I want to access my `textStyle` from the token function like `colors`, for example `token(colors.primary)`, it doesn’t support `textStyle`, for example `token(textStyle.h1)`.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-pandacss-rac-fxu8np?file=src%2FApp.tsx

### Steps to reproduce

See the `text.tsx` in `components` folder

### JS Framework

React (TS)

### Panda CSS Version

0.20.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @soheilnikroo,

This is by design. Text styles and layer styles are considered “style compositions” that contains a group of css properties.

In Panda, we don’t consider them as primitive design tokens since they don’t have css variables connected to them.

You can apply text styles like so:
css({ textStyle: “headline1” })

**Comment by soheilnikroo** [comment]
@segunadebayo, Thank you for your response. However, my issue goes beyond just setting textStyle to headline1. I have a prop in my component for changing textStyle. I want to have something like this token (`textStyle.${variant}`). I also updated the codebase for better understanding.

**Comment by segunadebayo** [comment]
Got it @soheilnikroo.

Here's a detailed implementation of the Text component you're looking to create. [See the code here](https://stackblitz.com/edit/vitejs-pandacss-rac-rjlvov?file=src%2Fcomponents%2Ftext.tsx,src%2Frecipes%2Ftext.ts,panda.config.ts,src%2FApp.tsx
)

**Define textStyles in config to unify typography styles**. I simplified the text styles a bit more

```ts
import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  // ...
  theme: {
    extend: {
      textStyles: {
        headline1: {
          description:
            'In the type scale, headlines span from a range of 1 through 6. Headlines are the largest text on the screen, reserved for short, important text or numerals.',
          value: {
            fontWeight: '300',
            fontSize: { _ltr: '5.5625rem', _rtl: '5.8125rem' },
            lineHeight: '7rem',
            letterSpacing: '-0.015em',
          },
        },
        headline2: {
          description: 'Oversized headlines in website.',
          value: {
            fontWeight: '300',
            fontSize: '3.625rem',
            lineHeight: '4.5rem',
            letterSpacing: '-0.005em',
          },
        },
      },
    },
  },
  // The output directory for your css system
  outdir: 'styled-system',
});

```


**Build out a text atomic recipe**. Notice how I introduced the "level" prop that maps to the respective text style, you can change it to "variant" if you want.

```ts
import { cva, type RecipeVariantProps } from 'styled-system/css';

export const text = cva({
  base: {
    color: 'red',
  },
  variants: {
    level: {
      h1: {
        textStyle: 'headline1',
      },
      h2: {
        textStyle: 'headline2',
      },
    },
  },
});

export type TextVariantProps = RecipeVariantProps<typeof text>

```

**Build out a text component**
Leverage the splitVariantProps function to separate text recipe props from other react props easily.

```tsx
import { text, type TextVariantProps } from '../recipes/text';

export type TextProps = TextVariantProps & { children: React.ReactNode }

export const Text = (props: TextProps) => {
  const [recipeProps, restProps] = text.splitVariantProps(props);
  return <p className={text(recipeProps)} {...restProps} />;
};

```

**Use the text component in your app**. I've added `dir=ltr|rtl` to the root element, you can build a RTL toggle around this root element

```tsx
import { Text } from './components/text';

function App() {
  return (
    <div dir="ltr">
      <Text level="h1">This text should have headline1 textStyle</Text>
    </div>
  );
}

export default App;
```
