### ISSUE TITLE
Recipes and patterns are not extracted from JSX files when using TS path mappings

### ISSUE THREAD

**Issue by abarani** [chakra-ui/panda#2011]
### Description

From version 0.26.0 recipes and patterns are not correctly extracted by the JSX file parser when using TypeScript path mappings.

This is a regression in v0.26.0, v0.25.0 is working correctly.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-h15awr?file=src%2FApp.tsx

### Steps to reproduce

1. Add a path mapping to the `styled-system` directory in *tsconfig.json*
2. Try to import the default `flex` pattern using the path mapping created before and use it inside a JSX component

The `flex` pattern is not present in the generated CSS

### JS Framework

React

### Panda CSS Version

0.27.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

https://github.com/chakra-ui/panda/blob/fcca63d3a6b97b025da1f83aafeec46b07df3234/packages/core/src/import-map.ts#L90

Here `resolvedMod` is an absolute path but `mod` is a relative one. If `mod` starts with "./" the `includes` fails even if both paths are the same.

https://github.com/chakra-ui/panda/blob/ef44917f77e6d6a61ca863757a76c924eb9bd688/packages/core/src/file-matcher.ts#L96

Here `o.mod.includes` fails as `o.mod` is a path mapping, `o.importMapValue === mod` fails too as `o.importMapValue` is an absolute path and `mod` is a relative one.

Both files are not present in v0.25.0 so I assume this is a major refactor.

**Comment by abarani** [comment]
Possible fix:

```diff
diff --git a/packages/core/__tests__/import-map.test.ts b/packages/core/__tests__/import-map.test.ts
index b20cdf35..b613356b 100644
--- a/packages/core/__tests__/import-map.test.ts
+++ b/packages/core/__tests__/import-map.test.ts
@@ -38,7 +38,7 @@ describe('import map', () => {
     // ts paths
     expect(
       ctx.imports.match({ mod: 'anydir/css', alias: 'css', name: 'css' }, function resolveTsPath(mod) {
-        return { 'anydir/css': 'styled-system/css' }[mod]
+        return { 'anydir/css': ctx.runtime.path.resolve('styled-system/css') }[mod]
       }),
     ).toBeTruthy()
   })
diff --git a/packages/core/src/file-matcher.ts b/packages/core/src/file-matcher.ts
index d917cecc..c3b6b2fe 100644
--- a/packages/core/src/file-matcher.ts
+++ b/packages/core/src/file-matcher.ts
@@ -1,3 +1,4 @@
+import { resolve } from 'node:path'
 import { memo } from '@pandacss/shared'
 import type { ImportMapOutput } from '@pandacss/types'
 import type { Context } from './context'
@@ -93,7 +94,7 @@ export class FileMatcher {
 
   private createMatch = (mod: string, keys: string[]) => {
     const mods = this.imports.filter((o) => {
-      const isFromMod = o.mod.includes(mod) || o.importMapValue === mod
+      const isFromMod = o.mod.includes(mod) || o.importMapValue === resolve(mod)
       const isOneOfKeys = keys.includes(o.name)
       return isFromMod && isOneOfKeys
     })
diff --git a/packages/core/src/import-map.ts b/packages/core/src/import-map.ts
index b823b8e9..3166d0db 100644
--- a/packages/core/src/import-map.ts
+++ b/packages/core/src/import-map.ts
@@ -1,3 +1,4 @@
+import { resolve } from 'node:path'
 import { isString, mapEntries } from '@pandacss/shared'
 import type { ImportMapInput, ImportMapOutput } from '@pandacss/types'
 import type { Context } from './context'
@@ -87,7 +88,7 @@ export class ImportMap {
       // that might be a TS path mapping, it could be completely different from the actual path
       const resolvedMod = resolveTsPath?.(result.mod)
 
-      if (resolvedMod?.includes(mod)) {
+      if (resolvedMod && resolvedMod === resolve(mod)) {
         result.importMapValue = resolvedMod
         return true
       }
```

I'm not opening a PR as I'm not sure about the `node:path` import as it is not used throughout the code base.

**Comment by astahmer** [comment]
you can add `importMap: '@/test',` in your `panda.config` and the issue is gone, that way your're in control of the module specifier and not relying on the automatic inference
