### ISSUE TITLE
HMR bug upon theme change (Remix)

### ISSUE THREAD

**Issue by fcisio** [chakra-ui/panda#2025]
### Description

This is a new repro for the #1021 issue.

HMR seems to work in most cases except one:
- ✅ Watched file change (ex: /app/routes/_index.tsx)
- ✅ Change in the CSS index file (that contains the layers)
- ❌ Change in the panda config / theme (see screen recording)
  - regardless of whether `panda codegen` is run with `--watch` or not

> As mentioned in the previous issue, the bug was fixed but reappeared in version 0.24.0.
> Version 0.23.0 is the latest without this bug.

---

--> [Here is a repro repo](https://github.com/fcisio/remix-panda-hmr-repro)

Follow the screen recording for steps to reproduce.

https://github.com/chakra-ui/panda/assets/46095852/e5f09d34-39d9-4b7f-9ddb-ce3d0f6fe697

### Link to Reproduction

https://github.com/fcisio/remix-panda-hmr-repro

### Steps to reproduce

1. `yarn`
2. `yarn dev`
3. [should work] Go to `app/index.css` and toggle the commented body style
4. [should work] Go to `app/routes/_index.tsx` and change the value in `className={css({ bgColor: "primary" })}`
5. [should issue] Go to `panda.config.ts` and change the value in `primary: { value: "green" }`
6. Notice the styles have disappeared

### JS Framework

Remix (TS)

### Panda CSS Version

0.27.2

### Browser

Google Chrome 120.0.6099.216

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by fcisio** [comment]
> most likely related to #2011 we'll find a way to make that behavior automatic, in the meantime, you can use the same fix: set your `importMap` to your tsconfig alias -> `importMap: "@",`

Thanks @astahmer! The `importMap` does fix the issue!

I'll be on the lookout for the automatic behavior, but in the meantime, it might be worth it to add a special mention in the docs or something.

**Comment by segunadebayo** [comment]
I've updated the docs in https://github.com/chakra-ui/panda/pull/2028 to include this alternative approach
