### ISSUE TITLE
defineKeyframes type error

### ISSUE THREAD

**Issue by Pixfloage** [chakra-ui/panda#2027]
### Description

![CleanShot 2024-01-18 at 12 13 38](https://github.com/chakra-ui/panda/assets/12548918/ce443b10-4915-431d-91fc-4b5d82c6f48b)

Using `defineKeyframes` there is no way to actually create a keyframe. On Next.js the page won't compile. Even on the [demo playground page](https://play.panda-css.com/) it's not working correctly. 

### Link to Reproduction

https://play.panda-css.com/pA1XjsCaYS

### Steps to reproduce

1. Create a new keyframe using `defineKeyframes`, from scratch or copy from the Panda docs 
2. See the type error immediately where <type> is not assignable to type CssProperties

### JS Framework

Next TS

### Panda CSS Version

0.27.2

### Browser

Chrome 120

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Pixfloage** [comment]
Defining the keyframe inside `panda.config.ts` is a workaround

```
  theme: {
    extend: {
      keyframes: {
        shine: {
          '0%': {
            transform: 'translateX(-100%)'
          },
          '100%': {
            transform: 'translateX(100%)'
          }
        }
      }
    },
  },
  ```

But obviously something's up with `defineKeyframes`

**Comment by astahmer** [comment]
I don't think it's broken, you should mirror the same format as you did in the theme.extend.keyframes, e.g wrapping in an object named with the keyframe that you want to create a config for

❌:
```ts
export const fadein = defineKeyframes({
  '0%': { opacity: '0' },
  '100%': { opacity: '1' }
})

```

✅:
```ts
const keyframes = defineKeyframes({
  fadeIn: {
    '0%': { opacity: '0' },
    '100%': { opacity: '1' },
  },
})
```

defineKeyframes should only be used at build-time, e.g either in the config file itself or somewhere that will then be imported in the config file, it is not meant to be used at runtime

https://play.panda-css.com/pA1XjsCaYS/OA3AAkGJbJ

**Comment by Pixfloage** [comment]
Awesome! 
Makes sense, this part wasn't clear, thank for the example.
However, the [documentation](https://panda-css.com/docs/customization/config-functions#definekeyframes) probably need some updating in this case!

**Comment by anubra266** [comment]
@Pixfloage It's already explained in the [previous section](https://panda-css.com/docs/customization/theme#keyframes)
