### ISSUE TITLE
Themed recipes does not support the usage of `.raw()`

### ISSUE THREAD

**Issue by omerman** [chakra-ui/panda#2057]
### Description

A pre-defined theme recipe doesnt support `.raw()` function

### Link to Reproduction

https://play.panda-css.com/Fv5FHQUeL1

### Steps to reproduce

There are two buttons, one that gets the style and one that doesnt.

### Panda CSS Version

latest

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Hi @omerman,

This is by design. Themed recipes and their `.raw(...)` return a `string`, not a style object, so you can't pass it to the `css` function.

In future versions, we might consider throwing an error when using `.raw()` for themed recipes. It should only be used for atomic recipes.

**Comment by omerman** [comment]
TBH I dont understand why it will create a bloated js, as this is the the way the entire system works (when using recipes not as part of the theme, which is 99% of the code) in order to work around it I will export standard SVA/CVA instead.. 

Thanks
