### ISSUE TITLE
Compiling with vite/rollup produces warnings about the __PURE__ annotations

### ISSUE THREAD

**Issue by jagregory** [chakra-ui/panda#2063]
### Description

When compiling with Vite, Rollup produces warnings about the placement of the `@__PURE__` comments in is-valid-prop.mjs when JSX is enabled.

```shell
styled-system/jsx/is-valid-prop.mjs (9:20) A comment

"/* @__PURE__ */"

in "styled-system/jsx/is-valid-prop.mjs" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
styled-system/jsx/is-valid-prop.mjs (13:29) A comment

"/* @__PURE__ */"

in "styled-system/jsx/is-valid-prop.mjs" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
```

According to an [issue in the Vite repo](https://github.com/vitejs/vite/issues/14716) and [a related issue](https://github.com/intlify/vue-i18n-next/issues/1599) these comments aren't in the right place to be effective. The `__PURE__` comments need to be placed where the functions are called, to denote those calls are pure, and not on the definition of the function which is always considered pure.

I think these comments can be removed?

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-rple3z?file=src%2FApp.tsx

### Steps to reproduce

1. Run `vite build`

### JS Framework

React (TS)

### Panda CSS Version

0.27.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

Vite version 5.0.12

**Comment by segunadebayo** [comment]
Good catch @jagregory.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by binajmen** [comment]
Hi @segunadebayo,

FYI, I'm still having the warnings:
```
src/styled-system/jsx/box.mjs (7:19) A comment

"/* @__PURE__ */"

in "src/styled-system/jsx/box.mjs" contains an annotation that Rollup cannot interpret due to the position of the comment. The comment will be removed to avoid issues.
```

**Comment by imsfc** [comment]
The problem persists.

**Comment by cdegrel** [comment]
It is possible to open this issue? Because the problem still exists.
