### ISSUE TITLE
Merging css props with `css` function doesn't work as the example shows

### ISSUE THREAD

**Issue by jagregory** [chakra-ui/panda#2070]
### Description

The [example docs for merging styles](https://panda-css.com/docs/concepts/merging-styles#merging-within-jsx-component) show that you use the `css` function to merge predefined styles with styles from a `css` prop:

```typescript
const cardStyles = css({
  bg: 'red',
  color: 'white'
})
 
function Card({ title, description, css: cssProp }) {
  return (
    // merge the `cardStyles` with the `cssProp` passed in
    <div className={css(cardStyles, cssProp)}>
      <h1>{title}</h1>
      <p>{description}</p>
    </div>
  )
}
```

But when I try to do this in a TypeScript project, the `css` function complains that the `cardStyles` type is of `string` and doesn't work. The only way I can get it to work is to change it to `className={cx(cardStyles, css(cssProp))}`. I don't know if this is a me issue or a docs issue 😄 

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-4mfewb?file=src%2FApp.tsx

### Steps to reproduce

1. Open App.tsx
2. See the two component examples
3. See in the preview that only the CardWorking component renders as expected

### JS Framework

React (TS)

### Panda CSS Version

0.27.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is most likely a docs error @jagregory.

`cardStyles` should be defined with `css.raw` which preserves the style object.

```jsx
const cardStyles = css.raw({
  bg: 'red',
  color: 'white',
});


function CardWorking({ title, description, css: cssProp }: CardProps) {
  return (
    <div className={css(cardStyles, cssProp)}>
      <h1>{title}</h1>
      <p>{description}</p>
    </div>
  );
}
```

We'll update the docs shortly.
