### ISSUE TITLE
Multi-Theme Tokens not working as expected

### ISSUE THREAD

**Issue by alycda** [chakra-ui/panda#2085]
### Description

When I create an alternate theme via conditions per the docs: https://panda-css.com/docs/guides/multiple-themes
I expected to see the primary color change when I added `data-theme=kids` to a wrapper div
But the primary theme color displayed instead of the override for `_kids`

### Link to Reproduction

https://play.panda-css.com/UlCu972naX

### Steps to reproduce

1. Go to the config tab and observe the `conditions` (base and "kids")
2. observe the semantic tokens specifying the primary color override for "kids" theme
3. Go to the Code tab and observe the `data-theme="kids"` in the wrapper div
4. See that the primary color remains "yellow" instead of purple, with and without the data-theme attribute on the wrapper div

### JS Framework

React (TS)

### Panda CSS Version

0.28.0

### Browser

Google Chrome Version 118.0.5993.70 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I looked for more clarity in the docs but couldn't find additional examples/information here: https://panda-css.com/docs/customization/conditions

**Comment by astahmer** [comment]
a few things are wrong in your config:

- you don't need a `base` custom condition with an empty value, [it's automatically provided in the `css()` fn](https://panda-css.com/docs/concepts/conditional-styles#nested-condition)
- [the `&` character was missing in your custom `kids` condition](https://panda-css.com/docs/customization/conditions) (we should emphasise this in the linked page)
- [you can use `DEFAULT` in the config `semanticTokens` to specify the value when not using a condition](https://panda-css.com/docs/theming/tokens#token-nesting)
- [your semanticToken is named the same as the one defined in token, `primary`, ideally avoid clashing names and use a new one](https://panda-css.com/docs/theming/tokens#semantic-tokens)
- you didn't wrap your semanticToken `primary` in a  `{ value: xxx }` key

```ts
import { defineConfig } from '@pandacss/dev';

export const config = defineConfig({
  conditions: {
    kids: '&[data-theme=kids]',
  },
  theme: {
    tokens: {
      colors: {
        primary: { value: '#FFF200', description: 'yellow.500' },
        secondary: { value: '#7334F4', description: 'purple.500' },
      }
    },
    semanticTokens: {
      colors: {
        main: {
          value: {
            DEFAULT: '{colors.primary}',
            _kids: '{colors.secondary}'
          }
        }
      }
    }
  },
});
```
![Screenshot 2024-01-25 at 10 54 04](https://github.com/chakra-ui/panda/assets/47224540/99b67863-9a17-4658-9ca3-b597f11cc91f)

---

we will add config validation exactly to avoid this kind of issues

**Comment by alycda** [comment]
Thankyou! My apologies for misunderstanding the documentation, fixed here: https://play.panda-css.com/5p5p9cbz2y
