### ISSUE TITLE
Pattern properties with correct naming are not taken into account into custom component

### ISSUE THREAD

**Issue by fseglard** [chakra-ui/panda#2116]
### Description

Hi!

I'm having a headhache trying to figure out how to customize a pattern properties from within a custom component.

Following the documentation [here](https://panda-css.com/docs/guides/dynamic-styling#property-renaming), I should be able to pass the pattern properties only if they have the same naming, but that's not the case actually.

I'm not sure if it's a regression or if I'm missing something.

### Link to Reproduction

https://play.panda-css.com/fcoU7ghh5d

### Steps to reproduce

In the PandaCSS Playground, I simply use the code example from the documentation. You can see that's the custom component with custom props is not working as expected since the related CSS is not properly generated.

### JS Framework

React (TS)

### Panda CSS Version

0.29.1

### Browser

Google Chrome 119

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by astahmer** [comment]
you need to specify which components are going to re-use that pattern internally, same limitation/solution as recipes
https://play.panda-css.com/fcoU7ghh5d/_DE_SwQlU9

https://panda-css.com/docs/concepts/recipes#advanced-jsx-tracking
we do need to update the patterns doc to mention that ! thank you for making us notice that

**Comment by fseglard** [comment]
Ahhh thanks @astahmer!

It works like a charm :heart:
