### ISSUE TITLE
Storybook HMR issues with recipe import

### ISSUE THREAD

**Issue by kiruushaaa** [chakra-ui/panda#2137]
### Description

[Storybook] When I edit `Button.recipe.ts` that is imported into main `panda.config.ts`, I expected HMR to happen, but it have not.

When trying the same for `avatarRecipe` that locates inside `panda.config.ts`, everything works as expected (HMR works, styles are being replaced)

### Link to Reproduction

https://github.com/kinguru-io/kinguru-next/tree/reproduce/nextjs-storybook-panda-imported-recipes

### Steps to reproduce

1. Clone a repo [reproduce/nextjs-storybook-panda-imported-recipes](https://github.com/kinguru-io/kinguru-next/tree/reproduce/nextjs-storybook-panda-imported-recipes)
3. Checkout the branch `reproduce/nextjs-storybook-panda-imported-recipes`
4. Install dependencies `npm install`
5. Run the storybook `npm run storybook`
6. Try to edit `Button.recipe.ts` `[src/components/uikit/Button]`
7. Try to edit `avatarRecipe` defined within the `panda.config.ts`

### JS Framework

Next TS

### Panda CSS Version

0.29.*

### Browser

Chrome 121, Safari 17.*

### Operating System

- [X] macOS
- [ ] Windows
- [X] Linux

### Additional Information

I assume cloning the repo locally is the only way since stackblitz stucks on the dependency installation.

PS. I tried adding `dependencies` (0.29.*) to the main panda config, but It seems to be useless since the system sees `**.recipe.ts` file changes with that property or not

**Comment by astahmer** [comment]
can you try [with the CLI](https://panda-css.com/docs/installation/cli) instead of using the postcss plugin ?

**Comment by kiruushaaa** [comment]
> can you try [with the CLI](https://panda-css.com/docs/installation/cli) instead of using the postcss plugin ?

Yeah, it works without the postcss plugin. I've got it running like that:
```shell
STORYBOOK_DEV=true npx storybook dev -p 6006 --ci & npx panda --watch
```
`postcss.config.cjs`
```javascript
module.exports = {
  plugins: {
    '@pandacss/dev/postcss': process.env.STORYBOOK_DEV === 'true' ? false : {}
  },
}
```
BUT 😅
But it takes approx 5-6 sec on my intel mac to reload (2-3 seconds panda takes to regenerate css). This is much better than nothing, but yeah, it takes too long. I guess this might be the solution for someone using similar setup but with really cool hardware.

Anyway, is it really possible to resolve that somehow for HMR to work with storybook + postcss?

**Comment by segunadebayo** [comment]
Hi @kiruushaaa

I just pushed a fix for this in [0dd45b6](https://github.com/chakra-ui/panda/commit/0dd45b6a40c5862e197baca1de497fbce46241aa). We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.

**Comment by astahmer** [comment]
> But it takes approx 5-6 sec on my intel mac to reload (2-3 seconds panda takes to regenerate css).

can you run `pnpm panda --cpu-prof` and send me the resulting generated `panda-xxx.cpuprofile` ? 
you can send it to me directly on the discord server

**Comment by segunadebayo** [comment]
> BUT 😅 But it takes approx 5-6 sec on my intel mac to reload (2-3 seconds panda takes to regenerate css). This is much better than nothing, but yeah, it takes too long. I guess this might be the solution for someone using similar setup but with really cool hardware.

I just tested out the CLI using the same commands outlined above and it's not as slow you reported. It's actually pretty fast.

![CleanShot 2024-02-05 at 16 52 13@2x](https://github.com/chakra-ui/panda/assets/6916170/823813bf-f9b9-4019-8800-ef0bfbde5173)

> The PostCSS Plugin should work in the next release, though. So you're good.

**Comment by kiruushaaa** [comment]
@astahmer @segunadebayo yeah, I assume that's because of checking all the files, including those not using panda. Anyway, postcss plugin works faster comparing to cli with the same file includes.

Nevertheless thank you all guys! Really appreciating your help!

**Comment by kiruushaaa** [comment]
hi @segunadebayo

Tested with the `0.30.1`. HMR works fine for imported recipes even without spare `dependencies` array. And yeah, it is 3x faster comparing to cli on my device
