### ISSUE TITLE
CSS shorthand properties with multiple tokens/values not working

### ISSUE THREAD

**Issue by mike-shtil-loop** [chakra-ui/panda#2160]
### Description

When defining properties like `padding: 5 10` (tokens), I expect the element to have `5` paddingBlock and `10` paddingInline, but instead no padding is applied.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-bmzemj?file=src/main.tsx,package.json,src/index.tsx&terminal=dev

### Steps to reproduce

1. To any element, add `css({padding: '5 10'})` (with at least one of the values being a token)
2. Observe the resulting styling does not apply padding

### JS Framework

React, Solid

### Panda CSS Version

0.30.1

### Browser

Arc 1.28.0 (45831)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

The behavior is the same for other shorthands like `margin`, `border`, when token values are involved.

Values such as `padding: '10 10'` generate the invalid `.p_10_10 { padding: 10 10; }`.

I managed to side-step the issue with the following custom utilities, but would expect this to be supported out of the box. Am I missing something?

```ts
utilities: {
  extend: {
    margin: fixTokenInterpolation({ className: 'm', values: 'spacing', property: 'margin' }),
    padding: fixTokenInterpolation({ className: 'p', values: 'spacing', property: 'padding' }),
    borderRadius: fixTokenInterpolation({ className: 'rounded', values: 'radii', property: 'borderRadius' }),
  }
}



function fixTokenInterpolation({ className, values, property }: { className: string; values: string; property: string }) {
  return {
    className,
    values,
    transform: (value: string, { token }: { token: any }) => {
      const normalizedValues = value
        ?.split(' ')
        .map((v: string) => (v.startsWith('$') ? token(`${values}.${v}`) : v)) // I prefix all tokens with $; some other regex/heuristic is needed for the common case
        .join(' ');

      return {
        [property]: normalizedValues,
      };
    },
  };
}

```

**Comment by astahmer** [comment]
I don't think this is something that we want to support by default, a user-land implementation like yours is perfect for this !
https://play.panda-css.com/P-dQWXAz0Y
I'm glad you found a solution for your use-case with a custom utility 

---
an alternative would be to use the token references syntaxes (you can choose any of those)
https://panda-css.com/docs/theming/usage#composite-values
https://play.panda-css.com/P-dQWXAz0Y/Lab9WDjto1

**Comment by mike-shtil-loop** [comment]
@astahmer appreciate the quick response!

I respect the decision of course and appreciate all of the hard work going into Panda!

Just as a point of reference, we're evaluating Panda now as a substitute for Stitches which supports multi-token with no issues.

Also, given this issue https://github.com/chakra-ui/panda/discussions/2165#discussion-6193052 seems the future direction is to spread shorthands into their components anyway, where surely each token needs to be interpolated.
