### ISSUE TITLE
studio CLI does not parse output directory

### ISSUE THREAD

**Issue by jesse-olympus** [chakra-ui/panda#2166]
### Description

The outdir parameter of the studio cli build command is parsed as a boolean instead of a string. It needs the `<outdir>` tag in the definition

### Link to Reproduction

https://play.panda-css.com/

### Steps to reproduce

1. `pnpm panda studio --build --outdir dist`

### Panda CSS Version

0.30.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by soyeloso** [comment]
The repo does not seem to allow any contribution at this point (I could not create a new branch), but the fix is the following :
![Screenshot 2024-02-08 at 13 34 53](https://github.com/chakra-ui/panda/assets/6860219/a475412a-3b1a-45dc-9351-71a70133b1b6)
