### ISSUE TITLE
_disabled is not priorized over other conditions in "styled" function

### ISSUE THREAD

**Issue by Jim-salies** [chakra-ui/panda#2195]
### Description

I wrote a button with specific colors when disabled but color still change when I click or hover it.

I tried to put disabled colors in base, in each variant, in a specific variant : 'disabled' => 'true' => ...style...

in all case, disabled is not priorized over other conditions.

### Link to Reproduction

https://play.panda-css.com/ClAEBFvgXo

### JS Framework

React

### Panda CSS Version

0.30.2

### Browser

Google Chrome 121.0.6167.161

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@Jim-salies the disabled styles take preference in your attached sample

![CleanShot 2024-02-12 at 16 32 09@2x](https://github.com/chakra-ui/panda/assets/30869823/ba774c96-0ac8-4d1a-a5b5-ddf7bf42224a)

**Comment by Jim-salies** [comment]
@anubra266 juste by hovering I get the following : 
<img width="573" alt="image" src="https://github.com/chakra-ui/panda/assets/62254668/d1d52cba-553f-4342-b2d3-caa50a7dcf0b">

**Comment by anubra266** [comment]
@Jim-salies, this is not a panda behaviour, it's css.
https://jsfiddle.net/k38w5xh6/

you'll have to do something like `:disabled:not(:hover)`

**Comment by astahmer** [comment]
you can use a runtime condition for that
https://play.panda-css.com/ClAEBFvgXo/X3M0GMtGVl

**Comment by Jim-salies** [comment]
I just started to use panda so I may be wrong but to keep using `styled` instead of cva + an aditionnal component, I modified conditions like this : 
```
{
    extend: {
      focus: '&:not(:disabled):is(:focus, [data-focus])',
      active: '&:not(:disabled):is(:active, [data-active])',
      focusWithin: '&:not(:disabled):focus-within',
      hover: '&:not(:disabled):is(:hover, [data-hover])',
    },
  }
  ```
  
  Anyway, it's finally working thanks a lot!
