### ISSUE TITLE
Some string `content` values in `globalCss` generate unexpected CSS output

### ISSUE THREAD

**Issue by amandaguthrie** [chakra-ui/panda#2197]
### Description

When I generate global CSS for the `content` property with string values:

- `content: ""` generates `content: 0;` instead of `content: "";`
- `content: " "` generates `content: 0;` instead of `content: " ";`
- `content: '•',` generates `content: •;` instead of `content: "•";`
- `content: "string"` generates `content: string;` instead of `content: "string";`

What do appear to be working - strings that use CSS utilities like `linear-gradient()` or `url()`.

### Link to Reproduction

[Repro](https://codesandbox.io/p/devbox/panda-css-0-23-staticcss-in-recipe-config-repro-forked-4tl7p9?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqv5ei590007356lwegild9x%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqv5ei580002356lnls845c5%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqv5ei580004356l5r2usng2%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqv5ei580006356l7lgmlmtg%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqv5ei580002356lnls845c5%2522%253A%257B%2522id%2522%253A%2522clqv5ei580002356lnls845c5%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580001356lsf5odb5a%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqv5ei580001356lsf5odb5a%2522%257D%252C%2522clqv5ei580006356l7lgmlmtg%2522%253A%257B%2522id%2522%253A%2522clqv5ei580006356l7lgmlmtg%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580005356l7tdg2pos%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522type%2522%253A%2522SANDBOX_INFO%2522%252C%2522id%2522%253A%2522clqv78kr9020m356lo5nvtrcd%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqv78kr9020m356lo5nvtrcd%2522%257D%252C%2522clqv5ei580004356l5r2usng2%2522%253A%257B%2522id%2522%253A%2522clqv5ei580004356l5r2usng2%2522%252C%2522activeTabId%2522%253A%2522clqv5nto200j3356lh3q7iyb6%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqv5ei580003356ltv91yurn%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522id%2522%253A%2522clqv5nto200j3356lh3q7iyb6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clsjwh58y0052dii39yhb2iea%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

I got an error trying to repro in the playground so a CodeSandbox is linked.

1. Go to `src/lib/theme/css/globalCss.ts` for the global CSS definition.
```typescript
export const globalCss = defineGlobalStyles({
  'input[type="checkbox"]': {
    '&:checked': {
      _before: {
        content: '•',
      },
      _after: {
        content: " "
      }
    }
  },})
```
2. Run `npm panda cssgen`
3. Open `styled-system/styles.css`
```css
  input[type="checkbox"]:checked::before {
    content: •;
}

  input[type="checkbox"]:checked::after {
    content: 0;
}
```

Note that the generated content from a string is not wrapped in quotes, or in the case of " " is a 0.

### JS Framework

TS - Have seen it in two projects with different setups. One is Svelte, the other is no framework - developing a preset.

### Panda CSS Version

0.30.2

### Browser

Google Chrome 121.0.6167.161

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@amandaguthrie in css `content` is usually within quotes `''` https://developer.mozilla.org/en-US/docs/Web/CSS/content
So to use it in css-in-js, it's not `content: ""` it's `content: "''"` or `content: "'•'"` or `content: "' '"`
