### ISSUE TITLE
Styles not loading from 0.27.3 (likely Windows related)

### ISSUE THREAD

**Issue by MeanBoyCousin** [chakra-ui/panda#2201]
### Description

When upgrading to 0.27.3 or above, I expect that when booting my NextJS app the styles are applied. However, no styles seem to be applied.

### JS Framework

NextJS 14

### Panda CSS Version

0.27.3+

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

```sh
diff --git a/node_modules/@pandacss/core/dist/index.js b/node_modules/@pandacss/core/dist/index.js
index cde18a1..88600ad 100644
--- a/node_modules/@pandacss/core/dist/index.js
+++ b/node_modules/@pandacss/core/dist/index.js
@@ -802,9 +802,9 @@ var ImportMap = class {
         return true;
       }
       const resolvedMod = resolveTsPath?.(result.mod);
-      const absMod = [this.context.config.cwd, mod].join("/");
-      if (resolvedMod?.includes(absMod)) {
-        result.importMapValue = resolvedMod;
+
+      if (resolvedMod?.includes(mod)) {
+        result.importMapValue = resolvedMod
         return true;
       }
     }
```

Reverting this [specific change made in this PR](https://github.com/chakra-ui/panda/pull/2028/files#diff-0211732aa34f781be72f8b42ed6da718ecbbac395f059cf10254211c81ec581eL88-L93) fixes the issue for me and lets me upgrade to the latest version.

**Comment by astahmer** [comment]
are you using tsconfig path aliases ? can you use `importMap` as described [here](https://panda-css.com/docs/guides/debugging#hmr-does-not-work-when-i-use-tsconfig-paths) ?

**Comment by MeanBoyCousin** [comment]
Yeah, I did try this. Unless I was configuring it wrong, it didn't solve the problem. For the below setup, what is the configuration?

```json
// tsconfig.json

"paths": {
  "@/*": ["./src/*"],
  "tv/*": ["./public/trading_view/*"],
}
```

**Comment by astahmer** [comment]
if you are importing Panda stuff like `import { css } from '@/styled-system/css'` then the matching `importMap` is `importMap: "@/styled-system"`

**Comment by MeanBoyCousin** [comment]
Amazing, thank you very much. I clearly did not spend enough time reading that documentation!
