### ISSUE TITLE
Potential `lightningcss` regression in v0.31.0

### ISSUE THREAD

**Issue by DanC5** [chakra-ui/panda#2211]
### Description

Upon upgrading from `0.30.2` to `0.31.0`, my team noticed that the cascade layers were not being set properly in our generated output css file. We ultimately found that including `lightningcss: true` in our config file was causing the issue.

Screenshot of our output file on `0.31.0` with `lightningcss: true` included...

![image](https://github.com/chakra-ui/panda/assets/43552931/9bf9595e-bc0e-48c2-af51-917f4d1857a6)

Screenshot of our output file on `0.31.0` with `lightningcss: true` removed...

![image](https://github.com/chakra-ui/panda/assets/43552931/6b3c5be7-626d-4227-9657-ba394551377b)

All versions prior to `0.31.0` appear to properly set the layers with `lightningcss: true`.

Thanks!

### Link to Reproduction

https://play.panda-css.com/jouRJ3q_pN

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

0.31.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This seems related to lightningcss messing with the CSS's order during the optimizing phase.

<img width="1728" alt="CleanShot 2024-02-17 at 21 28 54@2x" src="https://github.com/chakra-ui/panda/assets/6916170/75b44253-547f-4139-b824-71fa18ce73f4">

<br><br>

I recommend using a hook to correct this for now.

```jsx
// panda.config.ts
export default defineConfig({
  // ...
  hooks: {
    'cssgen:done'({ content, artifact }) {
      if (artifact !== 'styles.css') return content
      const rule = '@layer reset, base, tokens, recipes, utilities'
      return content.startsWith(rule) ? content : `${rule};\n\n${content}`
    },
  },
})
```

There is not a regression in Panda. We'll consider opening an issue in the lightningcss repo.
