### ISSUE TITLE
`WebkitBoxOrient` is not a valid key in `SystemStyleObject`

### ISSUE THREAD

**Issue by etlovett** [chakra-ui/panda#2213]
### Description

In order to do line clamping in CSS, we [need to use](https://developer.mozilla.org/en-US/docs/Web/CSS/-webkit-line-clamp) `-webkit-line-clamp` with `-webkit-box-orient: 'vertical'`, but `WebkitBoxOrient` is not a valid key in `SystemStyleObject`. The fix might be as simple as adding it to this list? https://github.com/chakra-ui/panda/blob/78145d890e1bb5d0e1c6beb5a62b02bb0ccab42c/packages/is-valid-prop/src/index.ts#L3-L4

### Link to Reproduction

https://play.panda-css.com/dN8_NImNgf

### Steps to reproduce

1. Load the playground
2. Observe the TS error

### Panda CSS Version

v0.31.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
In the mean time @etlovett 
https://play.panda-css.com/dN8_NImNgf/1KIHvpCTBM

**Comment by etlovett** [comment]
> In the mean time @etlovett https://play.panda-css.com/dN8_NImNgf/1KIHvpCTBM

Ah! I didn't realize that Panda had an alias for this. Another valid solution is to just put a `// @ts-expect-error` on it for now since Panda does produce the correct CSS for the property.

**Comment by segunadebayo** [comment]
The `WebkitBoxOrient` property is now considered obsolete, hence the reason it doesn't show up in the `csstype` library we use and in the list of css properties you mentioned (which is pulled directly from MDN)

See more here:
https://webkit.org/css-status/

![CleanShot 2024-02-16 at 23 02 27@2x](https://github.com/chakra-ui/panda/assets/6916170/52c8df5c-cebf-4be6-87a1-765c888f7b93)

Alternatives (as suggested by ChatGPT)

<img width="517" alt="CleanShot 2024-02-16 at 23 05 40@2x" src="https://github.com/chakra-ui/panda/assets/6916170/762a5c2d-b367-4880-a121-bed3e0fe9af5">

**Comment by etlovett** [comment]
@segunadebayo I agree that `-webkit-box-orient` is obsolete as a standalone property. Unfortunately it must still be used in conjunction with `-webkit-line-clamp`, which is the only way to trigger line clamping today. (Indeed, this is how Panda's `lineClamp` property works!) So for anyone who doesn't use Panda's `lineClamp`, `WebkitBoxOrient` is a requirement.

**Comment by anubra266** [comment]
@etlovett If it's a requirement for you, you can add it to your project this way:
https://play.panda-css.com/eFnPOnmBpu?tab=config
