### ISSUE TITLE
Opacity modifier typing error for strictTokens

### ISSUE THREAD

**Issue by BorisZubchenko** [chakra-ui/panda#2219]
### Description

When `strictTokens` is set to `true`, using opacity modifiers like `red.500/40` produces a TypeScript error:
![image](https://github.com/chakra-ui/panda/assets/31354262/c1cbd83a-4403-44dc-bb6c-2ce81769f357)

### Link to Reproduction

see additional information

### Steps to reproduce

1. `strictTokens: true`
2. `css({ bg: 'red.500/40' })`
3. `TS2820: Type 'red.500/40' is not assignable to type PropOrCondition<'bg', ColorToken> | undefined. Did you mean 'red.500'?`

### JS Framework

React (TS)

### Panda CSS Version

0.31.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

I can't give you a link to a reproduction because opacity modifiers don't work at all for reproductions:
![image](https://github.com/chakra-ui/panda/assets/31354262/dcc83df3-78f5-48a6-9666-11b87629e098)
Notice that the background is **transparent**.

**Comment by segunadebayo** [comment]
This is by design. We'll update the docs for the opacity modifier.

Opacity modifiers are considered a "design escape hatch" to quickly prototype UIs.
