### ISSUE TITLE
[TOKENS] SVG asset is not closed properly

### ISSUE THREAD

**Issue by ioulian** [chakra-ui/panda#2237]
### Description

When using svg assets, there is an `Unclosed bracket` error triggered.
 
There is a typo in the generation of svg assets in this file: https://github.com/chakra-ui/panda/blob/f41999357aa9bb48b6b692bc627eef7b54725d58/packages/token-dictionary/src/transform.ts#L126C74-L126C75 . The single quote must be inside the `url('<data>)'` function, now the closing quote is outside it:

Current:
```
`url('${svgToDataUri(value)})'`
```

Proposed fix:
```
`url('${svgToDataUri(value)}')`
```

The other issue is that the generated svg uses single quotes and it's also escaped by single quotes thus making css invalid. The quotes inside the svg must be double quotes. I've modified the function to this and it works:

```
`url('${svgToDataUri(value).replaceAll("'", '"')}')`
```

However, for the second proposed fix, maybe this is not the best option, maybe use double quotes for the `url("")` function itself?

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-nahgho?file=panda.config.ts&terminal=dev

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-nahgho?file=panda.config.ts&terminal=dev
2. See error in the terminal `<css input>:415:35: Unclosed bracket`

### JS Framework

React TS, Next.js

### Panda CSS Version

0.32.0

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

### Additional Information

![Screenshot 2024-02-22 at 10 38 53](https://github.com/chakra-ui/panda/assets/1311270/fcff8ff2-6052-48e8-b920-3cbef83f8955)

<img width="897" alt="Screenshot 2024-02-22 at 10 08 10" src="https://github.com/chakra-ui/panda/assets/1311270/d1ac86c4-c1c4-4e69-8d42-ff63690108e9">

**Comment by segunadebayo** [comment]
Good catch @ioulian.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
