### ISSUE TITLE
SVG Assets not correctly escaped

### ISSUE THREAD

**Issue by ioulian** [chakra-ui/panda#2248]
### Description

Continuation for this bug report: #2237 (thanks for fast fix for the build error)

SVG asset that is generated is not correctly escaped: `url('data:image/svg+xml,%3csvg width='12' height='8' viewBox='0 0 12 8' fill='%233C4346' xmlns='http://www.w3.org/2000/svg'%3e%3cpath d='M1.41 0.59L-2.62268e-07 2L6 8L12 2L10.59 0.59L6 5.17L1.41 0.59Z' /%3e%3c/svg%3e')`

Url function should have double quotes (or svg should have double quotes). Even if you define the svg with double quotes, they get transformed to single quotes.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-nahgho?file=src%2FApp.tsx,panda.config.ts&terminal=dev

### Steps to reproduce

1. Go to https://stackblitz.com/edit/vitejs-vite-nahgho?file=src%2FApp.tsx,panda.config.ts&terminal=dev
2. Inspect paragraph (hello world) 
3. Scroll down to @layer tokens > --assets-select-indicator
4. See not correctly escaped svg

### JS Framework

React

### Panda CSS Version

0.32.1

### Browser

All

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

![Screenshot 2024-02-24 at 13 10 01](https://github.com/chakra-ui/panda/assets/1311270/83f260df-9f8c-40d0-b949-fe447519d3ef)

When manually changing url to double quotes, this is the expected result:

![Screenshot 2024-02-24 at 13 14 04](https://github.com/chakra-ui/panda/assets/1311270/0ae53c90-7500-459f-96b3-e072453fcc70)

**Comment by segunadebayo** [comment]
I've updated the code to use double quotes. Good catch (again)

We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
