### ISSUE TITLE
_dark nested in _backdrop will output wrong class name, and caused trivial problem

### ISSUE THREAD

**Issue by emogua** [chakra-ui/panda#2252]
### Description

When I write css like this: (just test codes)
`
	const dialogStyles = css.raw({
		_backdrop: {
			opacity: 0.8,
			backgroundColor: {
				_dark: '#000'
			}
		}
	});
`
I can get the generated css snippet results in chrome:
`
.backdrop\:dark\:bg_\#000::backdrop.dark,.dark .backdrop\:dark\:bg_\#000::backdrop {
    background-color: #000;
}
`

I think `.backdrop\:dark\:bg_\#000::backdrop.dark` will make the rest class `,.dark .backdrop\:dark\:bg_\#000::backdrop` invalid.

Because when I modify `::backdrop.dark` to '::backdrop', it will work if I add a class 'dark' to the parent element or just body

So `.dark` should expected not to be added after ::backdrop pseudo class

### Link to Reproduction

https://play.panda-css.com/uk8pJ1bxQc

### Panda CSS Version

0.32.1

### Browser

chrome 122

### Operating System

- [ ] macOS
- [x] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This isn't a bug per say, it's related to how the `_dark` selector is defined.

Currently, it maps to `.dark &, &.dark` making it unusable when combining with pseudo elements.

I recommend updating the `_dark` selector like so:

```jsx
import { defineConfig } from '@pandacss/dev';

export const config = defineConfig({
  conditions: { extend: { dark: ".dark &" } },
  // ...
});
```

Here's the diff: https://play.panda-css.com/uk8pJ1bxQc/0c27LgQno7

**Comment by emogua** [comment]
Got it, thanks
