### ISSUE TITLE
Utilities generate wrong CSS when usage with presets

### ISSUE THREAD

**Issue by mverissimo** [chakra-ui/panda#2272]
### Description

I'm trying to create a utility inside a preset, but when I use an wrong CSS is generated, look:

![image](https://github.com/chakra-ui/panda/assets/371844/9bd01357-2b2a-449b-9e76-3999743d4da1)

The css generate is the utility name instead the propertie, this happens only the default preset is imported.

### Link to Reproduction

https://play.panda-css.com/6j6LSILpP1

### Steps to reproduce

With presets (don't work)

1. Go to config and look the utilities
2. Go to generate CSS

Without presets (work)

1. Go to config and move the utilities to defineConfig
2. Go to generate CSS

### JS Framework

React

### Panda CSS Version

v0.32.1

### Browser

Google Chrome 122.0.6261.70 (Official Build) (64-bit)

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@mverissimo Are you able to reproduce this in any project. There seems to be an issue on the playground.

**Comment by segunadebayo** [comment]
I can confirm this works locally. It's indeed a playground issue.

@anubra266 Kindly follow up with a fix in the playground when you have time.

![CleanShot 2024-02-27 at 16 06 22@2x](https://github.com/chakra-ui/panda/assets/6916170/b5964c00-fff7-4ec0-a925-dd1218effca5)

@mverissimo A temporary workaround in the playground is to assign `br` as a shorthand for `borderRadius`

```jsx
const preset = definePreset({
  utilities: {
    extend: {
      borderRadius: {
        shorthand: ["br"]
      }
    }
  },
});
```

https://play.panda-css.com/6j6LSILpP1/DMX5mJ1Cy-
