### ISSUE TITLE
_after property not working as intended.

### ISSUE THREAD

**Issue by XPD-Kasun** [chakra-ui/panda#2277]
### Description

When I used _after pseudo element to add content to a div to `::after`, the CSS is not generated for the `::after` class. Following was tried in the playground.
```
export const App = () => {
  return (
    <div className={center({ h: 'full' })}>
      <div className={css({ _after: { content: 'test', display: 'block' } })}>
        After pseudo element
      </div>
    </div>
  );
};
```
This will create `after:content_test after:d_block` as the class name for div with text "After pseudo element". When I manually add `::after` using inspector, I noticed that 2 `::after` pseudo elements have been generated but were not applied.
```
.after\:content_test::after {
    content: test;
}

.after\:d_block::after {
    display: block;
}
```
In this case after have been generated but, the _after properties are scattered through multiple atomic classes.

Expected behavior is to merge the properties and create a single ::after pseudo element for the class. (Maybe it can introduce another generated class name and add ::after for it.)

### Link to Reproduction

https://play.panda-css.com/7nE0OFKX0I

### Steps to reproduce

1. Go to ['playground link'](https://play.panda-css.com/7nE0OFKX0I)
2. Inspect the generated code for _after in the inspector.

### JS Framework

React TS

### Panda CSS Version

0.33.0

### Browser

Chrome 122

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @XPD-Kasun,

Please wrap `content` with an extra quote

```jsx
css({ _after: { content: '"test"', display: 'block' } })
```

https://play.panda-css.com/7nE0OFKX0I/vKHxYD13k2

**Comment by XPD-Kasun** [comment]
Yes, this works. Kindly thank you for clarification. 🙂.
