### ISSUE TITLE
Semantic tokens break tokens completely

### ISSUE THREAD

**Issue by levrik** [chakra-ui/panda#2284]
### Description

As soon as I define semantic tokens, no tokens are getting generated at all anymore.

### Link to Reproduction

https://play.panda-css.com/9BmZl2s3es

### Steps to reproduce

Open the Panda CSS playground. Both paragraphs are black. You can see that no CSS is generated in the `tokens` layer.
Remove the semantic tokens section from the config. The first paragraph will turn `red`.

### Panda CSS Version

0.33.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@levrik You're using the wrong syntax
https://play.panda-css.com/9BmZl2s3es/23O7eJnLxi?tab=config

**Comment by levrik** [comment]
@anubra266 wtf. I'm so sorry. No idea how I missed that despite several cross checks.

**Comment by astahmer** [comment]
> @anubra266 wtf. I'm so sorry. No idea how I missed that despite several cross checks.
> 
> but maybe also a chance to improve error reporting here.

indeed ! did that here https://github.com/chakra-ui/panda/pull/2289

**Comment by levrik** [comment]
awesome. thanks @astahmer.
