### ISSUE TITLE
cva not extracting css in 0.33.0

### ISSUE THREAD

**Issue by they-they-they** [chakra-ui/panda#2303]
### Description

When i creating cva component + styled it should work as described in documentation examples
https://panda-css.com/docs/concepts/recipes#atomic-recipe-or-cva

that way works fine in  0.32.0 but not working in  0.33.0

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-vlvabu?file=src%2FApp.tsx

### Steps to reproduce

1. Install 0.33.0 (works fine in 0.32.0) 
2. Create test component
```
import { cva } from '../styled-system/css'
import { styled } from '../styled-system/jsx'
 
const buttonStyle = cva({
  base: {
    color: 'red',
    textAlign: 'center'
  },
  variants: {
    size: {
      small: {
        fontSize: '1rem'
      },
      large: {
        fontSize: '2rem'
      }
    }
  }
})
 
const Button = styled('button', buttonStyle)

export const Root = styled("button", rootStyle);
```
5. info says css is extracted but no css generated

### JS Framework

react

### Panda CSS Version

0.33.0

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

### Additional Information

WSL2 Ubuntu 22.04

**Comment by anubra266** [comment]
@they-they-they 
```diff
- return <Button variant="solid">button</Button>;
+ return <Button visual="solid">button</Button>;
```
