### ISSUE TITLE
backgroundImage doesn't work with template string as value

### ISSUE THREAD

**Issue by avegatolber** [chakra-ui/panda#2308]
### Description

When I try to use `backgroundImage` and set it to template string value it doesn't work. 

Example:

```ts
import reactSvg from '../assets/img/react.svg'

<div
     className={css({
     border: "1px dashed black",
     width: "200px",
     height: "100px",
     backgroundImage: `url(${reactSvg})`,
     })}
/>
```
But if i do the same with native style it works

### Link to Reproduction

https://codesandbox.io/p/sandbox/panda-css-background-image-bug-6x524y

### Steps to reproduce

1. Import an image
2. Use `backgroundImage` property with `css` and use template string to put the imported image as url

### JS Framework

React (TS)

### Panda CSS Version

0.15.4

### Browser

Chrome

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@avegatolber Panda css is not a runtime library, it works by static extraction, so there's no way for panda to know the value of runtime stuff like that.

Do this instead:
![CleanShot 2024-03-04 at 20 12 30@2x](https://github.com/chakra-ui/panda/assets/30869823/5511b99c-bf02-4e9d-8033-1294ddda8c06)
