### ISSUE TITLE
Color opacity modifier syntax (blue.300/70) in token references doesn't work with conditions

### ISSUE THREAD

**Issue by benoitdeziel** [chakra-ui/panda#2318]
### Description

When I define a color semantic token with the color opacity modifier syntax, I expect to be able to use conditions (light/dark) in my config.

### Link to Reproduction

https://play.panda-css.com/x5SDGwNwSr

### Steps to reproduce

Define a semantic token in the config with conditions and use it as a color

### Panda CSS Version

0.34.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
nice catch & thanks for the minimal repro 🙏  will be fixed with https://github.com/chakra-ui/panda/pull/2319
