### ISSUE TITLE
Duplicated classes in extended components

### ISSUE THREAD

**Issue by ivanbanov** [chakra-ui/panda#2330]
### Description

Extending a component seems to be working fine when it's just 1 level, extending an extended component leads to duplicated classes.

### Link to Reproduction

https://stackblitz.com/edit/github-lhhzk8-dkevkj?file=src%2Fapp.tsx,panda.config.ts

### Steps to reproduce

```ts
// bg_blue.light
const Box = styled('div', {
  base: { background: 'blue.light' },
});

// bg_red.light
const ExtendedBox = styled(Box, {
  base: { background: 'red.light' },
});

// bg_blue.light bg_red.light
const ExtendedBox2 = styled(ExtendedBox, {
  base: { background: 'red.light' },
});
```

resulting in

<img width="174" alt="image" src="https://github.com/chakra-ui/panda/assets/2953018/1c3f1f46-b92d-41e6-a080-597eb4588b72">

### JS Framework

react

### Panda CSS Version

0.34.1

**Comment by astahmer** [comment]
hm, I remember this being an issue but I thought I had fixed it [here](https://github.com/chakra-ui/panda/pull/2192)

looking at your stackblitz, it seems fine ? 
<img width="1698" alt="image" src="https://github.com/chakra-ui/panda/assets/47224540/ce4647c1-1a8c-411e-8cd9-c0bb49fa9e03">

do I need to do anything else ?

**Comment by ivanbanov** [comment]
Sorry the example was not ideal, I updated the link.
The problem relies on extended components that may use an already extracted class, which will give more specificity to that class, and then the element will have the wrong style.

In the link the div with wrong classes should be
```diff
// ExtendedBox2
- bg_red.light text_[white] bg_blue.light text_[white]
+ bg_blue.light text_[white]

// ExtendedDiv2
- bg_blue.light text_[white] bg_red.light text_[white]
+ bg_red.light text_[white]
```
<img width="256" alt="image" src="https://github.com/chakra-ui/panda/assets/2953018/55b8c6b1-e0b5-4d52-b8e7-cc0f9f641319">
