### ISSUE TITLE
Unclear what CSS values are valid for `border` when `strictPropertyValues` is enabled

### ISSUE THREAD

**Issue by etlovett** [chakra-ui/panda#2335]
### Description

I don't know if this is a bug in Panda or just something I'm not understanding about the way `strictPropertyValues` works, but with that option enabled I can't find any value for `border` that does not produce a TS error except `none`.

See the playground at https://play.panda-css.com/I3PANm4dyQ, where I've taken the default playground, added `strictPropertyValues: true,` to the config, and then tried adding various `border*` properties. I've tried using VSCode's "go to definition" to explore the typedefs for the `border*` properties, but the typedefs produced by Panda are complicated enough that I haven't been able to figure out where the actual typedef is.

Without any border tokens defined in my config, what values are valid for `border*` properties besides `none`? When I don't have border tokens defined and I'm not using `strictTokens: true`, shouldn't all values be valid for `border*` properties? Or what am I misunderstanding about the intended behavior here?

Thanks!

### Link to Reproduction

https://play.panda-css.com/I3PANm4dyQ

### Steps to reproduce

1. Turn on `strictPropertyValues: true,` in the config
2. Add `border*` properties
3. Observe typechecking result

### Panda CSS Version

0.34.1

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
you're right, we made a mistake by including those properties
`strictPropertyValues` should restrict any CSS property that has a syntax with predefined values to those values only

`border` can be complex like `1px solid blue` so it shouldn't be restricted
`borderStyle` however can still be restricted

https://github.com/chakra-ui/panda/pull/2336

**Comment by etlovett** [comment]
Ah, ok, great. Thanks for the quick fix!

**Comment by etlovett** [comment]
@astahmer As one potential follow-up, FYI I just noticed that `borderStyle` is not currently in `StrictableProps` but has the same restricted subset of values, since it's the shorthand for the `border*Style` properties that are currently in `StrictableProps`. The one nuance is that it can have multiple values, e.g. `border-style: none solid dotted dashed;`.

**Comment by astahmer** [comment]
adding that to the list would prevent such use-case `none solid dotted dashed` so I guess it's better not to ?

**Comment by etlovett** [comment]
Ah, ok. I guess I was thinking the TS type could be something like this:
```
BorderStyle | `${BorderStyle} ${BorderStyle}` | `${BorderStyle} ${BorderStyle} ${BorderStyle}` | `${BorderStyle} ${BorderStyle} ${BorderStyle} ${BorderStyle}`
```

But maybe that's not workable for some reason? It does require a relatively new TS version to support template literal types.

**Comment by s97712** [comment]
I don't know if the issue is related, and border still only accepts'none 'for now.
` css({ border: "node" }) `

**Comment by s97712** [comment]
The definition of borders in the documentation is:
```ts
// https://panda-css.com/docs/theming/tokens#borders 

const theme = {
  tokens: {
    borders: {
      // string value
      subtle: { value: '1px solid red' },
      // string value with reference to color token
      danger: { value: '1px solid {colors.red.400}' },
      // composite value
      accent: { value: { width: '1px', color: 'red', style: 'solid' } }
    }
  }
}
```

In the source code, it is:
```ts
// https://github.com/chakra-ui/panda/blob/main/packages/preset-panda/src/borders.ts

export const borders = {
  none: { value: 'none' },
}
```

**Comment by anubra266** [comment]
@s97712 That's just doc sample for explanation, feel free to extend your config to add borders needed in your design system
