### ISSUE TITLE
Issue with tokens colors in panda studio

### ISSUE THREAD

**Issue by BigDog1400** [chakra-ui/panda#2343]
### Description

When i run panda studio it give me an error with certain key value in my colors tokens

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-gjlyrs?file=package.json

### Steps to reproduce

1. Go to https://github.com/BigDog1400/panda-studio-bug (or the stackblitz)
2. Clone the repository
3. pnpm i && pnpm run prepare
4. pnpm run panda:studio
5. See the error

### JS Framework

TS

### Panda CSS Version

0.34.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

It just happens with colors with this pattern lowercaseUppercase

**Comment by anubra266** [comment]
Fixed in #2387. We'll push a release soon.
