### ISSUE TITLE
Slot selector doesn't work if hashing is enabled

### ISSUE THREAD

**Issue by paveldubovitsky** [chakra-ui/panda#2369]
### Description

I tried to do this:
```ts
const slotRecipe = defineSlotRecipe({
  className: 'root',
  slots: ['slot1', 'slot2'],
  base: {
    slot1: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: 'full',
      '& .root__slot2': {
        color: 'red.500',
      },
    },
    slot2: {
      display: 'flex',
      flexDirection: 'column',
      fontWeight: 'semibold',
      color: 'yellow.300',
      textAlign: 'center',
      textStyle: '4xl',
    },
  },
});
```

It only works if hashing is disabled. In addition this way seems a little tricky because I can't control the className generation. It would be great to use slots nesting in the same way as condition nesting:
```ts
const slotRecipe = defineSlotRecipe({
  className: 'root',
  slots: ['slot1', 'slot2'],
  base: {
    slot1: {
      display: 'flex',
      justifyContent: 'center',
      alignItems: 'center',
      height: 'full',
      slot2: {
        color: 'red.500',
      },
    },
  },
});
```

### Link to Reproduction

https://play.panda-css.com/pMMXil05pS

### Steps to reproduce

1. Open `panda.config.ts`
2. Set the `hash` option to `true`
3. The text should be red but it's yellow

### Panda CSS Version

0.34.3

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This falls under the category of “won’t fix”, it one of the downsides of hashing class names and we can’t mess with user code to transform/hash selectors within styles object. We might end up with some unexpected side effects 

I recommend switching to data attributes within your code instead if you have hashing turned on.
