### ISSUE TITLE
Enabling "syntax: template-literal" does not generate recipes

### ISSUE THREAD

**Issue by islami00** [chakra-ui/panda#2388]
### Description

When enabling template-literal syntax in the config

```
import { defineConfig, defineRecipe } from '@pandacss/dev'

const buttonRecipe = defineRecipe({
        className: 'button',
        description: 'The styles for the Button component',
        base: {
          borderRadius: 'md',
          fontWeight: 'semibold',
          h: '10',
          px: '4',
        },
        variants: {
          visual: {
            solid: {
              bg: { base: 'colorPalette.500', _dark: 'colorPalette.300' },
              color: { base: 'white', _dark: 'gray.800' },
            },
            outline: {
              border: '1px solid',
              color: { base: 'colorPalette.600', _dark: 'colorPalette.200' },
              borderColor: 'currentColor',
            },
          },
        },
      })

export const config = defineConfig({
  theme: {
        extend: {
          recipes: {
            button: buttonRecipe,
          },
        },
      },
  globalCss: {
    html: {
      h: 'full',
    },
    body: {
      bg: { base: 'white', _dark: '#2C2C2C' },
    },
  },
  jsxFramework: 'react',
  validation: 'error',
  syntax: "template-literal"
});
```

Recipes like the `button` recipe defined in the config can't be used anymore.

### Link to Reproduction

https://play.panda-css.com/Oiby0TVnDQ

### Steps to reproduce

1. Go to the playground link
2. Change the syntax to `template-literal`
3. notice the error `ReferenceError: getCompoundVariantCss is not defined` and that no styles are applied

### Panda CSS Version

0.35.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

If this is a known limitation about the current setup around template-literals something could be added to the docs to explain this.

**Comment by segunadebayo** [comment]
This is mentioned in the docs, but we can be more explicit by mentioning recipes as well.

I'll update that shortly.

<img width="861" alt="CleanShot 2024-03-16 at 18 31 39@2x" src="https://github.com/chakra-ui/panda/assets/6916170/666e03ea-d86e-4dac-8b2e-f4329174be82">
