### ISSUE TITLE
Tokens are not validated

### ISSUE THREAD

**Issue by zeeeeby** [chakra-ui/panda#2392]
### Description

I am faced with two problems:
1) the token is not validated if it is in a string and not a string
2) the typescript alerts errror at the Shadow type for `tokens`, but does not alert at `semanticTokens`

1. Example theme config:

```typescript
theme: {
	tokens: {
		shadows: {
			strong: {
				value: "2px 4px 16px 0px {colors.gray.100/16}, 0px 2px 4px 0px {colors.gray.100/8}",
			},
		},
	},
},
```

I expect, that panda compiler will tell me `- [tokens] Missing token: "colors.gray.100" used in "config.tokens.shadows.strong"`, but it does not.

2) So, if rewrite it to 
```typescript
value: {
	offsetX: "2px",
	offsetY: "4px",
	blur: "16px",
	spread: "0px",
	color: "{colors.gray.100/16}",
},
```
it anyway does not alert about non-existing token. But i have a typescript error. You can see it in play.panda 

### Link to Reproduction

https://play.panda-css.com/-j-bPpS9jV

### Steps to reproduce

1. Go to 'config'
2. See typescript error on `tokens.value`.
3. Notice that `semanticTokens.value` does not have typescript error
4. See alert: Invalid config has error only for `semanticTokens` and not for `tokens`. But their values are the same

### JS Framework

React 18.2.0

### Panda CSS Version

0.34.3

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@zeeeeby your typescriot error is because you're using the wrong types. String instead of numbers
https://play.panda-css.com/CTBahd8-gq?tab=config

**Comment by zeeeeby** [comment]
> @zeeeeby your typescriot error is because you're using the wrong types. String instead of numbers https://play.panda-css.com/CTBahd8-gq?tab=config

yes. But if i use the same config in `semanticTokens` i dont see typescript errors
<img width="438" alt="image" src="https://github.com/chakra-ui/panda/assets/44382546/5a8a09b3-d287-47c2-b684-79ecf2695c40">
