### ISSUE TITLE
className + slot selector does not work when hash is true

### ISSUE THREAD

**Issue by haseeb5i** [chakra-ui/panda#2409]
### Description

I have a slot recipe where I am using new className + slot name selector syntax introduced in 0.35. It works perfect but when i turn on the hash option, everything gets hashed and these selectors don't work any more (It seems to working in sva but not in config recipe).

### Link to Reproduction

https://play.panda-css.com/YFHxeOc924

### JS Framework

React (TS)

### Panda CSS Version

0.35.0

### Browser

Brave 122

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by astahmer** [comment]
we'd rather not introduce more custom syntax that we already have, it would require one to be able to select a slot when using hash: true
https://github.com/chakra-ui/panda/issues/2369#issuecomment-1992227993

**Comment by anubra266** [comment]
@haseeb5i You can achieve this with data-part selectors instead.

Add a data part to the element to be targeted e.g `data-part="item"` then use this in style. E.g.

```js
parent:{
    '& [data-part="item"]': {
       //styles
    }
}

sibling:{
    '& ~ [data-part="item"]': {
       //styles
    }
}
```
