### ISSUE TITLE
mask prop for a component with a slash ( mask="DD/MM") breaks panda

### ISSUE THREAD

**Issue by omridevk** [chakra-ui/panda#2495]
### Description

I suspect panda think this is a CSS prop while it is not, so it tries to applies color mixin on it. 

https://stackblitz.com/edit/vitejs-vite-3qwpeh?file=panda.config.ts

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-3qwpeh?file=panda.config.ts

### Steps to reproduce

1. See the styles are not applied.
2. Change the mask(it is just a react prop) of component `<MyMask mask="MM{/}YY2" />` to `<MyMask mask="MMYY2" />` (removing the slash)
3. styles will work again

### Panda CSS Version

latest

### Operating System

- [X] macOS
- [X] Windows
- [X] Linux

**Comment by omridevk** [comment]
@astahmer Yeah, but in the repo JSX is disabled.

**Comment by astahmer** [comment]
seems like you're using an outdated version of Panda, I remember this issue, it's been fixed here https://github.com/chakra-ui/panda/pull/1840
<img width="679" alt="image" src="https://github.com/chakra-ui/panda/assets/47224540/4af6b03b-f223-48fb-ac68-4e35d90585ef">

**Comment by omridevk** [comment]
@astahmer  I'll check, thank you

**Comment by omridevk** [comment]
@astahmer 
Actually, I am using the latest one, see here:
https://stackblitz.com/edit/vitejs-vite-3qwpeh?file=src/App.tsx
