### ISSUE TITLE
First letter of text never inherits the cursor

### ISSUE THREAD

**Issue by likewerealive** [chakra-ui/panda#2496]
### Description

When hovering over the first letter in a line of text, the cursor remains as the pointer rather than the text cursor. This happens in my app using panda, but also noticed it on the panda website

### Link to Reproduction

https://panda-css.com/

### Steps to reproduce

1. Go to the panda homepage
2. Hover over any of the first letters in any line of text
3. The cursor will stay as the pointer and turn to the text cursor on any subsequent letters

### JS Framework

React (TS)

### Panda CSS Version

0.37.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

From my tests, it seems to have been caused by ::first-letter being targeted in the reset here: https://github.com/chakra-ui/panda/blob/bc09d893a63ab2b40f6fe026ab3b7bd62dad289d/packages/generator/src/artifacts/css/reset-css.ts#L20

**Comment by segunadebayo** [comment]
Good catch @likewerealive.

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
