### ISSUE TITLE
JSX styles disappear after either a hot reload or navigation 

### ISSUE THREAD

**Issue by Southclaws** [chakra-ui/panda#2501]
### Description

While working on a site I started running into odd behaviour where Panda styles disappear from the site entirely after either a hot reload or a page navigation until `yarn dev` is killed and restarted. On first page load, the styles are fine, then after either saving a .tsx file or clicking a `<Link />` any styles from atomic classes (which I use jsx style props for) disappear from the bundled .css file.

This appears to only affect `yarn dev` and the production deployed sites are fine.

I've bisected the issue across all recent Panda versions and the site works fine on [0.24.0](https://github.com/chakra-ui/panda/releases/tag/%40pandacss%2Fdev%400.24.0) and upgrading Panda CSS to either [0.25.0](https://github.com/chakra-ui/panda/releases/tag/%40pandacss%2Fdev%400.25.0) or any future versions results in this bug. Here's the diff between those two versions if useful: https://github.com/chakra-ui/panda/compare/@pandacss/dev@0.24.0..@pandacss/dev@0.25.0

Here's a video, hot-linked from [the original Discord report](https://discord.com/channels/1118988919804010566/1120305029056831548/1226474493942169662):

https://cdn.discordapp.com/attachments/1120305029056831548/1226474491325059124/Screen_Recording_2024-04-07_at_11.03.00.mov?ex=6624e661&is=66127161&hm=49fabe3bf221b0fa60875038cc6e8fe38a2c68b7f0a5ab4885dfee51e628eaab&

(GitHub doesn't support .mov containers so I can convert it if anyone wants to see it and doesn't have Discord)

I'm not fully up to date with how Next.js, PostCSS and Panda really work under the hood so I've got no idea where to really look for solutions. Luckily, since 0.24.0 works fine I can stick on that version for now.

### Link to Reproduction

https://github.com/Southclaws/southcla.ws

### Steps to reproduce

- Clone this repo
- `yarn dev`
- click any of the posts
- or
- open up a `page.tsx` file and make a change then save the file to trigger a hot reload

### JS Framework

React TS

### Panda CSS Version

0.25.0+

### Browser

All major browsers

### Operating System

- [X] macOS
- [X] Windows
- [ ] Linux

### Additional Information

Usually, all these atomic classes end up in one of the two css files which Next.js generates:

![image](https://github.com/chakra-ui/panda/assets/1636971/7d2caeba-cbac-44c7-ab09-71806bcd17fc)

however, once you either trigger a hot reload or navigate to a new page, the css file only contains styles from `global.css` and does not contain any atomic classes at all.

**Comment by Southclaws** [comment]
It seems because I'm outputting the `styled-system` directory to `src/` via:

https://github.com/Southclaws/southcla.ws/blob/main/panda.config.ts#L20

But I did not specify [importMap](https://panda-css.com/docs/references/config#importmap) this caused the issue.

So, solved! But a DX improvement here would be awesome if it's possible for the Panda compiler to figure this out and throw an error!

**Comment by astahmer** [comment]
hey, I'm almost certain (havent tried tho) that it's related to https://github.com/chakra-ui/panda/pull/2500
and yes `importMap` fixes this, glad you found it !
