### ISSUE TITLE
`jsxFramework: "preact"` includes unused `mergeCss` import

### ISSUE THREAD

**Issue by danielberndt** [chakra-ui/panda#2532]
### Description

I've just set up a fresh astro project using preact and the autogenerated code results in a warning for each pattern, when building the code.

```
styled-system/jsx/visually-hidden.mjs:3:1 - warning ts(6133): 'mergeCss' is declared but its value is never read.

3 import { mergeCss } from '../css/css.mjs';
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
````

Here's my config

```ts
import {defineConfig} from "@pandacss/dev";
import tokens from "./src/styles/tokens";

export default defineConfig({
  include: [
    "./src/**/*.{ts,tsx,js,jsx,astro}",
    "./pages/**/*.{ts,tsx,js,jsx,astro}",
  ],
  exclude: [],

  strictTokens: true,
  strictPropertyValues: true,
  jsxFramework: "preact",

  theme: {
    tokens,
  },
  outdir: "styled-system",
});
```

### Link to Reproduction

https://play.panda-css.com/Ag0mUUq4Na

### Steps to reproduce

- add `jsxFramework: "preact"` to the panda config
- run the `prepare` script
- inspect the resulting files in`styled-system/jsx/`

### JS Framework

Preact

### Panda CSS Version

0.37.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
