### ISSUE TITLE
Type error when merging imported styles 

### ISSUE THREAD

**Issue by bruncun** [chakra-ui/panda#2570]
### Description

Hi! Thanks for the awesome library. When I attempt to merge two styles imported from another file, the first one passed to `css` shows the following type error: `Argument of type 'string' is not assignable to parameter of type 'Styles | Styles[]'.ts(2345)` If I roll back to v0.38.0, the error disappears.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-jsro6s?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. Open `App.tsx:7`
2. See error

### JS Framework

React (TS)

### Panda CSS Version

0.39.0

### Browser

N/A

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
sorry about that ! it has been fixed [here](https://github.com/chakra-ui/panda/pull/2561) and merged [here](https://github.com/chakra-ui/panda/pull/2562), released in npm as v0.39.1

**Comment by bruncun** [comment]
Np! Thanks for the quick turnaround and again for Panda! 🙏
