### ISSUE TITLE
Due to Safari 14 not supporting @layer, the application styles fail.

### ISSUE THREAD

**Issue by wind4gis** [chakra-ui/panda#2616]
### Description

when i open my website on safari 14, it apply css failed

### Link to Reproduction

https://play.panda-css.com/ 

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

0.32.0

### Browser

safari 14

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by wind4gis** [comment]
can panda support @layer polyfill ?

**Comment by astahmer** [comment]
we do actually https://panda-css.com/docs/references/config#polyfill
https://panda-css.com/docs/overview/browser-support#polyfills
