### ISSUE TITLE
strictTokens and strictPropertyValues not throwing errors in Next.js

### ISSUE THREAD

**Issue by kopestik** [chakra-ui/panda#2621]
### Description

I tried Panda with Next.js and followed the installation docs. I've set strictTokens and strictPropertyValues to true in Panda config but Typescript is not throwing error in VSCode for this, even when building.

Code (or check repro):
`<div className={css({ bg: "asdasdadn hasdjhasdhjsa" })}>Hello 🐼!</div>`

### Link to Reproduction

https://stackblitz.com/edit/nextjs-anpxrk?file=app%2Fpage.tsx

### Steps to reproduce

1. Turn on strictTokens and strictPropertyValues to true
2. Add `bg` with random value
3. Check VSCode TS errors
4. Also try building the app (yarn build)

### JS Framework

Next.js (TS)

### Panda CSS Version

0.39.1

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by kopestik** [comment]
I just had to run `panda codegen`

**Comment by zachbwh** [comment]
@kopestik Thank you for this lol
