### ISSUE TITLE
Wrong styled prop types with jsxStyleProps set to none or minimal

### ISSUE THREAD

**Issue by JohnnyCrazy** [chakra-ui/panda#2643]
### Description

Hi,

When specifying `jsxStyleProps: "none" | "minimal"` in the `panda.config.ts`, typescript types are still generated as for `jsxStyleProps: "all"`. The actual props do not have an effect, so it seems to be just on the type level.

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-82o8wx?file=src%2FApp.tsx&terminal=dev

### Steps to reproduce

1. Set `jsxStyleProps: "none" | "minimal"`
2. Run panda codegen
3. Use `<styled.button p="4">Hello</styled.button>`
4. See how TS reports no problems, but the padding is not actually applied

### JS Framework

React (TS)

### Panda CSS Version

0.40.0

### Browser

-

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This was still working in version `0.37.2`

**Comment by segunadebayo** [comment]
I fixed this in the recent commit [here](https://github.com/chakra-ui/panda/commit/d2cc156b4dbb215e55ea58399858bf36b128ceea)

We'll release a new version shortly.

**Comment by JohnnyCrazy** [comment]
Ah nice,  thanks for the quick update! Will this also fix it for minimal?
