### ISSUE TITLE
Generate ColorTokens based on current theme (especially if not extended from panda/preset-panda)

### ISSUE THREAD

**Issue by pkrawc** [chakra-ui/panda#2670]
### Description

Currently it looks like the ColorToken type generated within the `styled-system/tokens` folder is always a static export of all 600 default colors. I cannot use it to create expected types for my components like that if I'm not using those colors.

Eg.

```ts
type AvatarProps = {
  badgeColor: ColorToken // This doesn't work if I don't have the default color tokens in the theme.
}

<Avatar src="..." badge badgeColor="colors.brand.primary" />
```

### Problem Statement/Justification

I would love to include type safety and autocompletion to the end user of my internal library.

### Proposed Solution or API

Extract the color tokens into string form and add them to the ColorToken type at build time.

**Comment by astahmer** [comment]
this is already the current behaviour, generating types/CSS based on your specific panda.config, [so you must be including the `@pandacss/preset-panda`](https://panda-css.com/docs/customization/presets#which-panda-presets-will-be-included-)
feel free to make a minimal repro if you need help
