### ISSUE TITLE
PandaCSS fails with specific linear gradient CSS

### ISSUE THREAD

**Issue by tyteen4a03** [chakra-ui/panda#2737]
### Description

Using this CSS:

```
            bg: `linear-gradient(${token('colors.yellow.300')}, ${token('colors.yellow.300')}) bottom/100% 5px no-repeat, ${token('colors.yellow.500')}`
```

Panda fails to generate the correct CSS.

Inputting the expected style works as intended: `background: linear-gradient(var(--colors-yellow-300),var(--colors-yellow-300)) bottom/100% 5px no-repeat, var(--colors-yellow-500)`

### Link to Reproduction

https://play.panda-css.com/3agV8bKfpG

### Panda CSS Version

0.42.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is not a bug. I consider it a limitation of the compiler since it doesn't resolve string interpolations like this.

I recommend using a css var approach to keep things type-safe
```js
css({
    --start: 'colors.yellow.300',
    --end: 'colors.yellow.500',
    bg: 'linear-gradient(var(--start), var(--start) bottom/100% 5px no-repeat, var(--end))'
})
```
