### ISSUE TITLE
DEFAULT layerStyles isn't applied

### ISSUE THREAD

**Issue by benoitdeziel** [chakra-ui/panda#2753]
### Description

When using nested layerStyles, using the `DEFAULT` key isn't working when using the parent name. Referencing `name.DEFAULT` is working. I was expecting that this would work like any other tokens.

### Link to Reproduction

https://play.panda-css.com/yDrVDu3sVR

### Steps to reproduce

1. Create a nested layerStyle with DEFAULT as the key
2. Apply it to a JSX component with the layerStyle prop
3. Notice that the styles aren't applied

### JS Framework

React TS

### Panda CSS Version

0.44.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
That's a good point!

I just added support for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
