### ISSUE TITLE
Studio build has incorrect paths

### ISSUE THREAD

**Issue by rajat2502** [chakra-ui/panda#2756]
### Description

When I run the studio build command to generate the studio, the HTML file has incorrect paths to the different assets (CSS, JS, etc). Which breaks the final page. 

Here's the screenshot of the page with broken paths + what the current paths are:
![Screenshot 2024-07-26 at 12 44 25 PM](https://github.com/user-attachments/assets/488c2477-d1a1-4643-8ae8-2e65a6ab4836)
<img width="426" alt="Screenshot 2024-07-26 at 12 45 27 PM" src="https://github.com/user-attachments/assets/d6d5593a-5179-4be5-a160-c3b99a4ef0ca">

If I manually fix these paths, then the page works perfectly.

### Link to Reproduction

https://github.com/rajat2502/pandacss-experiments/pull/1

### Steps to reproduce

1. Checkout to the `design-system` directory.
2. Run `yarn studio:build`
3. The build should get generated, now open the `index.html` file from the `studio` folder. 
4. See the issue

### JS Framework

React (TS)

### Panda CSS Version

0.37.2

### Browser

CLI

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
After running the `studio:build`, I recommend running `npx serve ./studio` instead of manually opening the `index.html`

**Comment by rajat2502** [comment]
any way i can convert them to relative paths? I don't want to use a server for this particular build
