### ISSUE TITLE
Border token with composite value output an extra px if the width is a string containing px

### ISSUE THREAD

**Issue by benoitdeziel** [chakra-ui/panda#2759]
### Description

When defining a border token with composite value, as demonstrated in the [docs](https://panda-css.com/docs/theming/tokens#borders), using `'1px'` for the width is outputting the wrong css `1pxpx`.

![CleanShot 2024-07-26 at 11 02 45@2x](https://github.com/user-attachments/assets/69ede26c-579a-4ed8-9348-c5b5699866dd)

Using a string without the unit `'1'` or using a number `1` works

### Link to Reproduction

https://play.panda-css.com/tce-84OGuW

### Steps to reproduce

1. Take the example from the [docs](https://panda-css.com/docs/theming/tokens#borders)
2. Add it in the playground config
3. Apply the token with composite value to an element
4. Notice that the border is not rendered
5. In the generated token notice that it outputs `1pxpx`

### JS Framework

React TS

### Panda CSS Version

0.44.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
