### ISSUE TITLE
Styles not extracted in a nx monorepo lib

### ISSUE THREAD

**Issue by VictorienDruon** [chakra-ui/panda#2760]
### Description

Hi, I'm trying to use Panda CSS in an integrated monorepo with nx.

The solution I came up with is to create a styled-system lib that contains the panda config file and the generated code. I then import the generated code in my apps or libs that use Panda.

It works fine in my react app (with vite) but when i try to declare styles in a react lib (with no bundler), the styles are not extracted by Panda and thus are not reflected in the app.

In the attached repro,

**apps/web/src/app/app.tsx** :
```tsx
import { css } from '@panda-nx/styled-system/css';
import { Heading } from '@panda-nx/ui';

export function App() {
  return (
    <div>
      <h1 className={css({ color: 'red' })}>
        Color styled in red in apps/web : style correctly extracted
      </h1>
      <Heading>Color styled in blue in libs/ui : style not extracted</Heading>
    </div>
  );
}
```

**libs/ui/src/lib/heading.tsx** : 
```tsx
import { css } from '@panda-nx/styled-system/css';

type HeadingProps = { children: string; };

export const Heading = ({ children }: HeadingProps) => {
  return <h1 className={css({ color: 'blue' })}>{children}</h1>;
};
```

I've looked at other discussions about Panda in a nx monorepo but none really enlightened me. I don't know if it's only my panda config that is flawed or if it's my entire solution that is wrong, but if anyone has a solution for my use case i'm eager to hear it. Thanks in advance for your answers

### Link to Reproduction

https://stackblitz.com/~/github.com/VictorienDruon/panda-nx

### Steps to reproduce

1. Go to this [repro](https://stackblitz.com/~/github.com/VictorienDruon/panda-nx)
2. Run ```npx nx serve web```
3. See that the first text is red and the second is not blue. The first text styles were extracted while the second's weren't.

### JS Framework

React (TS)

### Panda CSS Version

0.44.0

### Browser

Chromium 126

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This shows we need to improve the docs around monorepos.

To resolve this, you need to move `panda.config.ts`  from `libs/ui/styled-system` to the `apps/www`

Here's what the config should look like:

```ts
import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: ['**/*.{ts,tsx}', "../../libs/ui/**/*.{ts,tsx}"],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {},
  },

  // The output directory for your css system
  importMap: '@panda-nx/styled-system',
  outdir: 'src',
});
```

Notice the include `include` and how I've added `../../libs/ui/**/*.{ts,tsx}` so that Panda can also extract from there.

Opened a PR here: https://github.com/VictorienDruon/panda-nx/pull/1

**Comment by VictorienDruon** [comment]
works great for me, thanks for the fix and the quick answer !

**Comment by floratmin** [comment]
Would be helpful if the sample repository would be accessible.
