### ISSUE TITLE
Token not resolved in pseudo elements

### ISSUE THREAD

**Issue by doksara** [chakra-ui/panda#2774]
### Description

When I pass the token to component and reference it in base styles of `css()` function, it's working just fine.

```
// This is working just fine
export const FormattedMessageA = ({
  children,
  backgroundColor = "magenta",
}: React.PropsWithChildren<FormattedMessageProps>) => {
  return (
    <StyledSpan
      className={css({
        backgroundColor: backgroundColor,
      })}
    >
      {children}
    </StyledSpan>
  )
}
```

But when I reference it in pseudo element styles, it's not working. Also, notice that if you simply don't pass the value, it resolves to default prop `backgroundColor = "magenta"` and then it's working again.

```
// This is NOT working 
export const FormattedMessageB = ({
  children,
  backgroundColor = "magenta",
}: React.PropsWithChildren<FormattedMessageProps>) => {
  return (
    <StyledSpan
      className={css({
        _before: {
          backgroundColor: backgroundColor,
        },
      })}
    >
      {children}
    </StyledSpan>
  )
}
```

What am I doing wrong?

### Link to Reproduction

https://play.panda-css.com/S4vWjd9xUA

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React (TS)

### Panda CSS Version

0.42.0

### Browser

Version 127.0.6533.89 (Official Build) (arm64)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is a static limitation of Panda since the compiler cannot know that the `backgroundColor ` is used inside of `_before `.

We recommend keeping the prop mapping as simple as possible. Consider using a `css` prop to style components from the outside.

**Comment by doksara** [comment]
@segunadebayo Why isn't it mentioned anywhere in the docs, for example in the [Using pseudo props](https://panda-css.com/docs/concepts/writing-styles#using-pseudo-props) section? Seems to me like a common use case.
