### ISSUE TITLE
The value will be overwritten if the difference is space and underline

### ISSUE THREAD

**Issue by jas-chen** [chakra-ui/panda#2792]
### Description

When I have code like this
```jsx
<div
  className={css({
    _before: { content: '"hello world"' },
  })}
>
</div>
<div
  className={css({
    _before: { content: '"hello_world"' },
  })}
>
</div>
```
I expected it would display
```
hello world
hello_world
```
But it displayed
```
hello_world
hello_world
```

### Link to Reproduction

https://play.panda-css.com/Z5qypT-tOn

### Steps to reproduce

You can see the value `hello_world` displayed 2 times.

### Panda CSS Version

0.45.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
For this use case, I recommend using the "escape hatch" approach, which preserves the content value.
https://play.panda-css.com/Z5qypT-tOn/XKxBmnuFj8

```jsx
<div
  className={css({
    _before: { content: '["hello world"]' },
  })}
>
</div>
<div
  className={css({
    _before: { content: '"hello_world"' },
  })}
>
</div>
```
