### ISSUE TITLE
no auto complete in JSX import when using panda as a package eg "@acme/styled-system/" 

### ISSUE THREAD

**Issue by faithfulojebiyi** [chakra-ui/panda#2877]
### Description

When i mport stuffs like import { Box, Flex, HStack, VStack } from "@cuuro/design-system/jsx";

I auto complete does not work. I cant see the props from any of them but if they are imported as fuctions from patters it works

![Screenshot 2024-09-17 at 00 16 33](https://github.com/user-attachments/assets/c6f77c33-6341-4a83-b2ff-000ef2103845)
![Screenshot 2024-09-17 at 00 16 52](https://github.com/user-attachments/assets/042a93a6-54c0-452d-b4c2-99d1b678284b)

The design system and the  package json

![Screenshot 2024-09-17 at 00 18 03](https://github.com/user-attachments/assets/8848316a-0a91-4e13-8b01-79ff80425462)
![Screenshot 2024-09-17 at 00 18 22](https://github.com/user-attachments/assets/6cd4b401-f497-4389-b118-21204f057eec)

panda config for the design system
![Screenshot 2024-09-17 at 00 21 37](https://github.com/user-attachments/assets/80b7eaa8-5331-4f20-a144-42bf22af4411)

Usage in UI LIbary
No auto complete
![Screenshot 2024-09-17 at 00 27 25](https://github.com/user-attachments/assets/870c4d46-9874-40d6-8da9-97f6b0b1d8fc)

Tsup Config for ui libary
![Screenshot 2024-09-17 at 00 28 03](https://github.com/user-attachments/assets/c9b19371-ec1c-46bb-8ed7-c5d0708bbcaa)

### Example reproduction

https://github.com/firzanarmani/turbo-panda

### JS Framework
React TS

_No response_

### Panda CSS Version

0.46.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey brother. Good to see you here.

The solution is to install @types/react and react in the styled-system package.

```json
  "dependencies": {
    "@types/react": "^18.2.62",
    "react": "^18.2.0"
  }
```

**Comment by faithfulojebiyi** [comment]
Thanks boss

**Comment by faithfulojebiyi** [comment]
Ill make a PR to add it to the docs so someone else doesn't miss it
