### ISSUE TITLE
Override/change hover behaviour

### ISSUE THREAD

**Issue by isaachinman** [chakra-ui/panda#2894]
### Subject

Conditional styles

### Description

I've noticed that `_hover` and `_active` fire incorrectly/unexpectedly on iOS touch devices. When scrolling a list of items, hover and active styles will be triggered.

I'm no CSS expert, but vaguely remember this as being a long-standing mobile web issue.

This styling reproduces the problem:

```ts
_hover={{
  backgroundColor: 'red'
}}
```

This styling fixes the problem:

```ts
className={
  css({
    '@media (hover: hover)': {
      _hover: {
        backgroundColor: 'red',
      },
    },
  })
}
```

I very much expect that the answer here will be that this is a CSS problem, not a Panda problem – fine, I get it.

However, I'd like to be able to redefine the global selector for all `_hover` conditional styles across my project. Initially it seemed like this might be possible via `utilities.extend`, but I have not been able to figure it out.

Surely I'm not the first to encounter this problem, and documentation would be great to have.

**Edit 1:** I have found the base configuration for hover [here](https://github.com/chakra-ui/panda/blob/main/packages/preset-base/src/conditions.ts#L2C3-L2C39).

I assume that this can be changed via:

```ts
export default defineConfig({
  conditions: {
    extend: {
      hover: '???',
    },
  },
}
```

But I do not have a working value yet...

**Edit 2:** I have not been able to get any media query working at all. The only thing I've been able to come up with thus far that works, is:

```ts
export default defineConfig({
  conditions: {
    extend: {
      hover: '[data-hover-supported="true"] &:is(:hover, [data-hover])',
    },
  },
})
```

Wherein I am manually applying a data attribute based on a runtime `window.matchMedia`.

Would appreciate a more elegant CSS-only solution, as there are clearly media queries in `preset-base` conditions.

**Comment by astahmer** [comment]
hey, you can replace the `hover` condition using `conditions.extend`, example here
https://play.panda-css.com/30JwSWcl2T

```ts
conditions: {
      extend: {
        hover: ['@media (hover: hover)', '&:is(:hover, [data-hover])']
      }
  },
```

see docs on the [extend keyword](https://panda-css.com/docs/concepts/extend), or [customizing custom conditions](https://panda-css.com/docs/customization/conditions#customizing-built-in-conditions) and finally [mixed conditions](https://panda-css.com/docs/customization/conditions#mixed-conditions) (media + selectors)

**Comment by isaachinman** [comment]
Ah, mixed conditions was the piece I was missing. Hilarious that `supportHover` was already in the docs – I did look for quite awhile but never found it. Thanks!
