### ISSUE TITLE
Margin shorthand doesn't recognize token

### ISSUE THREAD

**Issue by JuhG** [chakra-ui/panda#2912]
### Description

I have a token defined (`$1`)
```tsx
tokens: {
  spacing: {
    $1: {
      value: '100px'
    }
  }
}
```

When using it as `margin="$1"` it works as expected, but in the shorthand form it's not working: `margin="$1 0"`
Here's the output:
![Screenshot 2024-10-07 at 19 31 20](https://github.com/user-attachments/assets/0e8e70c4-9604-4345-bd6a-672aba78b5e0)

### Link to Reproduction

https://play.panda-css.com/gGnQINxIE2

### Steps to reproduce

Check reproduction link

### JS Framework

React (TS)

### Panda CSS Version

v0.46.1

### Browser

Chrome Version 129.0.6668.90

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
This is by design. Please see 
https://github.com/chakra-ui/panda/discussions/2735#discussioncomment-10071424 for a workaround

**Comment by JuhG** [comment]
it's a bit more manual than I hoped for, but it's working great, thank you :)
