### ISSUE TITLE
Unexpected conditions in tokens behaviour

### ISSUE THREAD

**Issue by Faithfinder** [chakra-ui/panda#2929]
### Description

I expect the button to change color when I hover it. Instead it changes color when I hover the page.

### Link to Reproduction

https://play.panda-css.com/8JELValJZ6

### JS Framework

React (TS)

### Panda CSS Version

v0.46.1

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Design tokens (which are effectively CSS Variables) should be scoped to attribute selectors or media queries.

**Comment by Faithfinder** [comment]
Anything you could do to clarify docs and maybe restrict behaviour?

### Docs

Docs do mention that token conditions must be an at-rule, but also mention "parent selectors" and link to condition reference. Except "Parent selector" is barely a CSS term (could be achieved with `has`, but `has` has more applications than that, eh?), and having a link to the reference is confusing since nothing there points at the condition suitability for this context. If you're not paying close attention, it looks like the link shows usable conditions.

### Codegen

Also, since this produces arguable useless result, should panda skip generating code for these conditions, or do a warning or something? I initially thought I just need to tweak something in the config for it to work, since the result looked "almost working"
