### ISSUE TITLE
Namespaced imports don't work with path aliases

### ISSUE THREAD

**Issue by vmarcosp** [chakra-ui/panda#2935]
### Description

I ran some tests with Panda and noticed that namespace imports don't work as expected when combined with path aliases:

<img width="962" alt="Screenshot 2024-10-21 at 12 03 55" src="https://github.com/user-attachments/assets/17eb6729-1146-4de9-97d7-08b4b402f10d">

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-xakquj?file=src%2FApp.tsx

### Steps to reproduce

1. Go to 'App.tsx'
2. Check the Stackblitz Preview
3. There are two divs, the first one styled and the second isn't

### JS Framework

React (TS)

### Panda CSS Version

0.47.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
you can explicitly tell Panda which tsconfig path alias you're using with `importMap: '@styled',`

also, the stackblitz link is using `latest` but it looks like it still is using an old version, explicitly setting the version seems to fix it `"@pandacss/dev": "0.47.0",` when using `pnpm`
https://panda-css.com/docs/overview/faq#hmr-does-not-work-when-i-use-tsconfig-paths
https://panda-css.com/docs/guides/component-library#summary
