### ISSUE TITLE
Bug when using token reference syntax in border's composite value

### ISSUE THREAD

**Issue by TheoLAFARGE** [chakra-ui/panda#2942]
### Description

Hello guys, I have a problem with a token usage :

```typescript
export const borderWidths = defineTokens.borderWidths({
  thin: { value: '1px' },
  thick: { value: '2px' },
})

export const borders = defineTokens.borders({
  brand: { value: { width: '{borderWidths.thick}', color: '#fff', style: 'solid' } },
})
```

The output is "--borders-brand: var(--border-widths-thick) px solid #fff;"

Which is equal "2px px solid #fff"

Note the "2px px" which cause the CSS to not apply.

### Link to Reproduction

https://play.panda-css.com/1736HE8uZB

### Steps to reproduce

1. Open console
2. Check the element with the "bd_brand" class
3. See the value of the border ? It's "2px px solid #fff"

### Panda CSS Version

0.47.0

### Operating System

- [x] macOS
- [x] Windows
- [x] Linux

**Comment by segunadebayo** [comment]
I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
