### ISSUE TITLE
Boolean variants css is not generated just in time with defineRecipe and conditions

### ISSUE THREAD

**Issue by nassimbenkirane** [chakra-ui/panda#2943]
### Description

Config Recipes with boolean variants don't work with simple conditions.

When I create a boolean variant with `defineRecipe` I expect it to be usable like this
```jsx
<Button isLoading={someState === 'loading'}>Save</Button>
```
But the css is not generated for isLoading variant

**Expectation**
It generates the css for isLoading=true & isLoading=false
**Reality**
It does generate the correct className, but the css is not output

### Link to Reproduction

https://play.panda-css.com/i6-6uds1EH

### Steps to reproduce

1. Go to https://play.panda-css.com/i6-6uds1EH
2. See that with boolean condition with explicit values: `loading={"key1" !== "key1" ? true : false}` css is generated
3. See that with boolean condition without explicit values: `loading={"key2" === "key2"}` css is not generated
4. Change the condition to `loading={true}` to see green background styling applied

### JS Framework

React

### Panda CSS Version

0.47.0

### Browser

Google Chrome 130.0.6723.70

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

- It works when explitely adding 'true' or 'false' : 
```jsx
<Button isLoading={someState === 'loading' ? true : false} />
``` 
(but in my case the linter would remove it)
- Without JSX recipe it still doesn't work 
```jsx
<button className={buttonRecipe({isLoading: someState === 'loading'})} >Save</button>
```
- The AST would wrongly put the compared string as the value, instead of outputting the `true` | `false` values
<img width="273" alt="Capture d’écran 2024-10-25 à 13 31 38" src="https://github.com/user-attachments/assets/7251bf7b-de01-4c24-b9bd-78a56c3a8e64">

**Comment by segunadebayo** [comment]
Due to Panda's static nature, it's difficult to predetermine when to generate the `isLoading` styles.

You guessed right: explicitly adding the `true` and `false` gets it to work.

Alternatively, you can use the `staticCss` option in the recipe to pregenerate the `isLoading` styles
