### ISSUE TITLE
Stack pattern "direction" prop doesn't match docs

### ISSUE THREAD

**Issue by Faithfinder** [chakra-ui/panda#2948]
### Description

When I use the [Stack](https://panda-css.com/docs/concepts/patterns#stack) pattern, I expect "vertical" and "horizontal" to be "direction" values, as docs say. Instead it maps to normal `flexDirection`.

### Link to Reproduction

https://play.panda-css.com/Ml16utIaFx

### Panda CSS Version

0.47.0

**Comment by segunadebayo** [comment]
Docs need an update instead. It's not a bug.

Will push an update shortly.
