### ISSUE TITLE
Invalid css property generated with gridTemplateColumns

### ISSUE THREAD

**Issue by VincentBee** [chakra-ui/panda#2990]
### Description

When i use the `gridTemplateColumns` property with the following value: `"3" `
I expect to have a generated class with: `repeat(<value>, minmax(0, 1fr))`
but i get `3px` instead.

When i change the value for `1fr 1fr 1fr` or `repeat(3, 1fr)`, it works as expected

I made a reproduction of the issue here: https://github.com/VincentBee/bug-reproduction/tree/pandacss/grid-column?tab=readme-ov-file#bug-reproduction

### Link to Reproduction

https://play.panda-css.com/B1gCpvUP6H

### Steps to reproduce

1. Follow installation guide: https://panda-css.com/docs/installation/vite
2. Add a grid using this documentation: https://panda-css.com/docs/utilities/flex-and-grid#grid
3. See the generated property for the div

### JS Framework

React (TS)

### Panda CSS Version

0.48.0

### Browser

Every

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Please see the changelog here:
https://github.com/chakra-ui/panda/blob/main/CHANGELOG.md#changed

We'll update the docs shortly
