### ISSUE TITLE
Incorrect type for `scrollbarGutter`

### ISSUE THREAD

**Issue by jakst** [chakra-ui/panda#3012]
### Description

The scrollbarGutter property can have values `auto | stable | both-edges`, but currently in Panda you get a type error if you specify any of those (when panda is set to strictTokens). It's currently typed as ``ConditionalValue<WithEscapeHatch<`var(--${string})` | SpacingToken>>``. If strictTokens is off, then you can use the correct values, but panda also autocompletes spacing tokens, which are invalid values for this property.

### Link to Reproduction

https://play.panda-css.com/1g6EYoUUWA

### Steps to reproduce

1. Go to reproduction
2. Check type error in code

### Panda CSS Version

0.48.0

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
That's a good point. Spacing tokens are indeed invalid values

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
