### ISSUE TITLE
Support Semantic Tokens in a CompositeShadow

### ISSUE THREAD

**Issue by cgatian** [chakra-ui/panda#3041]
### Description

Composite shadows do not support using semantic tokens.

### Problem Statement/Justification

Composite shadows take numerical values, not string values which _could_ be semantic tokens.
```
  offsetX: number
  offsetY: number
  blur: number
  spread: number
```

This makes mapping values from a W3 spec difficult to implement as you need to combine the properties into the string version.

```json
 "drop-shadow-3": {
    "$type": "shadow",
    "$value": [
      {
        "offsetX": "{Atomic Scale.0}",
        "offsetY": "{Atomic Scale.300}",
        "blur": "{Atomic Scale.400}",
        "spread": "{Atomic Scale.100}",
        "color": "{Surface.drop-shadow}"
      }
    ]
  },

```

### Proposed Solution or API

Allow supplying `number` or `string` values which are sematic tokens

### Alternatives

Using the `string` version works properly. I was able to wrap my shadows in a reducer before supplying them to the panda theme.

```js
shadows: Object.entries(getShadows()).reduce((acc, [key, entry]) => {
    acc[key] = {
      value: `${entry.value.offsetX} ${entry.value.offsetY} ${entry.value.blur} ${entry.value.spread} ${entry.value.color}`,
    };
    return acc;
  }, {}),
  ```

**Comment by segunadebayo** [comment]
Sounds like a good idea. 

I just implemented it in Panda. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
