### ISSUE TITLE
Boolean variants are not being generated correctly for inputs

### ISSUE THREAD

**Issue by taylorpreston** [chakra-ui/panda#3055]
### Description

When I add a boolean variant to an input I expect the passing true or false to effect the component's styles.

I am passing isError: true, and isError:false and getting the same styles.

https://play.panda-css.com/7Acj3Q7yDq

### Link to Reproduction

https://play.panda-css.com/7Acj3Q7yDq

### Steps to reproduce

Look at the playground I set up.

### Panda CSS Version

current

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by amandaguthrie** [comment]
In the reproduction playground config `inputRecipe`: `variants` is a child of `base` when it should be a sibling to `base`. Once `variants` is moved, the background color displays when true and doesn't when false.

https://play.panda-css.com/wTcbE6p6YI
```typescript
const inputRecipe = defineRecipe({
  className: 'tint-input',
  base: {
    //  Removed for brevity
  },
  variants: {
    isError: {
      true: {
        backgroundColor: 'red.900',
      },
    },
  },
});```

**Comment by segunadebayo** [comment]
Closing based on: https://github.com/chakra-ui/panda/issues/3055#issuecomment-2558605218
