### ISSUE TITLE
[wsl / vscode] import autocompletion issue

### ISSUE THREAD

**Issue by YannBirba** [chakra-ui/panda#699]
Using react with vite and postcss panda integration.

Panda cli doesn't add the panda outDir to tsconfig include array and documentation doesn't mention it, so we have 0 import autocompletion. Is it planned to be added to the cli or should i make a PR to edit the doc ?

**Comment by YannBirba** [comment]
Also no autocompletion from @pandacss/dev

**Comment by anubra266** [comment]
@YannBirba Please give more details about the issue; framework, environment. A reproduction would be best.

**Comment by YannBirba** [comment]
Just followed the doc : [Repo is here](https://github.com/YannBirba/panda-css-doc)

**Comment by astahmer** [comment]
adding your `config.outdir` (defaults to `styled-system`) to tsconfig.include should fix that

**Comment by anubra266** [comment]
@YannBirba I'm not sure what issue you're facing. And could you make a stackblitz reproduction. Makes it easier for multiple people to look into any issues you might have

**Comment by astahmer** [comment]
from what I understand, OP is asking to mention in the docs that it might be needed to add the `config.outdir` (defaults to `styled-system`) in the tsconfig.include to get proper auto-imports completions

**Comment by YannBirba** [comment]
> from what I understand, OP is asking to mention in the docs that it might be needed to add the `config.outdir` (defaults to `styled-system`) in the tsconfig.include to get proper auto-imports completions

Yeah, exactly sorry if that was not really clear...Docs update is a thing, but i think that when doing `panda init` or `panda codegen` it could be soo better to update the tsconfig as well. I think it's better than mention it in the doc.

**Comment by segunadebayo** [comment]
Yes, let's update the docs to add this note.

If it becomes a common issue, we can figure out how to automatically update tsconfig.

**Comment by segunadebayo** [comment]
I just pushed the note about this.

Thanks
