### ISSUE TITLE
Can't remove default patterns, conditions and utilities

### ISSUE THREAD

**Issue by pawelblaszczyk5** [chakra-ui/panda#716]
### Description

Hello, 
First and foremost - PandaCSS is sooooo awesome, amazing work ♥️

I feel like that if I'm not using `extends` key in config it should overwrite the defaults - and it seems to work like this for e.g. tokens inside of theme. However,  it doesn't seem to work with patterns, conditions and utilities, I've tried a few ways and the defaults are always available. Setting presets to an empty array also don't remove all the defaults. 

Is there a way to remove these defaults so I can tailor them exactly to my needs?

### Link to Reproduction

https://github.com/pawelblaszczyk5/next-playground-panda-css/tree/153b1cdf1d25ac7205afcb3339d83eb8318454da

### Steps to reproduce

1. Go to `panda.config.ts`
2. Set conditions/utilities or patterns to an empty object or create only one entry 
3. Run codegen
4. Observe default conditions/utilities/patterns still being generated

### JS Framework

n/a

### Panda CSS Version

0.3.1

### Browser

n/a

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by pawelblaszczyk5** [comment]
Thanks a lot for this!

**Comment by matthew-ia** [comment]
#774 seems to have fixed being able to remove default tokens, but I am still getting default patterns, conditions, and utilities.

E.g., if I have the config:

```ts
export default defineConfig({
  // ...
  theme: {},
  patterns: {},
  conditions: {},
})
```
Then run: `npx panda codegen --clean`

I still get output for all patterns, etc.:

<img width="209" alt="Screenshot 2023-09-03 at 17 35 24@2x" src="https://github.com/chakra-ui/panda/assets/17885141/77b577f5-4b24-414d-9bbd-e71d983ed08b">

**Comment by anubra266** [comment]
@matthew-ia There's no issue with `eject`. The issue here is that the `clean` flag isn't removing the patterns that were generated before. 
Please open a different issue for this.

**Comment by matthew-ia** [comment]
@anubra266 thanks for the help, but it was just user error on my part. I didn't use `eject` at first, thinking just not using `extends` / empty objects would do the trick as this issue originally mentioned. 

Using `eject` and using `--clean` are indeed working as expected!
