### ISSUE TITLE
Top-level README.md still mentions Astro

### ISSUE THREAD

**Issue by thobas-dnvgl** [chakra-ui/panda#733]
### Description

From the top-level README (emphasis mine):

> The recommended way to install the latest version of **Astro** is by running the command below:

### Link to Reproduction

https://raw.githubusercontent.com/chakra-ui/panda/main/README.md

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

latest

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Good catch! Fixed it
