### ISSUE TITLE
Unable to share when using the playground

### ISSUE THREAD

**Issue by paulm17** [chakra-ui/panda#735]
### Description

When I click the share button, nothing happens.

Chrome: ![Chrome Screenshot](https://i.imgur.com/QqNSBmT.png)

Firefox: ![Firefox Screenshot](https://i.imgur.com/OXeKVPI.png)

### Link to Reproduction

n/a

### Steps to reproduce

1. Go to 'https://play.panda-css.com/'
2. Edit the text so the share button activates
3. Click share
4. See error in console

### JS Framework

n/a

### Panda CSS Version

latest

### Browser

Latest Chrome and Firefox

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @paulm17,

It works now https://play.panda-css.com/oOj9g-jNpT

The Prisma database was asleep, that's why it threw and error.
