### ISSUE TITLE
Token type does not work for globalCss

### ISSUE THREAD

**Issue by makotot** [chakra-ui/panda#741]
### Description

In the following code such like [the example from the official documentation](https://panda-css.com/docs/concepts/writing-styles#global-styles), when specifying a token value (such as gray.900) for the value of background-color, auto-completion does not work from the type. Since the background color is reflected as specified, I believe it should be an available value. I assume this is probably the case, but is this a bug?

```ts
  globalCss: {
    'html, body': {
      backgroundColor: 'gray.900', // auto-completion does not work
      lineHeight: '1.5',
    },
  },
```

<img width="662" alt="スクリーンショット 2023-06-20 0 18 06" src="https://github.com/chakra-ui/panda/assets/1129027/4defb042-0896-4d4f-818e-bfcfebe41743">

### Link to Reproduction

https://stackblitz.com/edit/vitejs-vite-l78ege?file=panda.config.ts

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React, Vite, TypeScript

### Panda CSS Version

0.3.2

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @makotot,

Please use the `defineGlobalStyles` function to get autocomplete.

```ts
import { defineConfig, defineGlobalStyles } from '@pandacss/dev';

const globalCss = defineGlobalStyles({
  'html, body': {
    backgroundColor: 'gray.900',
    lineHeight: '1.5',
  },
});
```

Here's the working code: https://stackblitz.com/edit/vitejs-vite-uk85nu?file=panda.config.ts,tsconfig.json

**Comment by makotot** [comment]
I see, thanks for letting me know. Thanks also for the update on the documentation!
