### ISSUE TITLE
Docs Page on Mobile Not Responsive

### ISSUE THREAD

**Issue by saintmalik** [chakra-ui/panda#747]
### Description

Went to the docs page from my device and the docs sidebar covered up the contents, not a common thing with docusaurus docs.

![Screenshot_2023-06-20-07-19-00-289_com brave browser](https://github.com/chakra-ui/panda/assets/37118134/bc11de95-abe4-44f9-9f87-9a07be620128)

### Link to Reproduction

https://panda-css.com/docs

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### Panda CSS Version

0.3.2

### Browser

Brave

### Operating System

- [ ] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Can't reproduce this at the moment. We'll keep an eye out for this issue.
