### ISSUE TITLE
The extended font is placed at the end of the font list 

### ISSUE THREAD

**Issue by FlatMapIO** [chakra-ui/panda#767]
### Description

I think the reasonable result should be to place my extended font variable at the top of the list

### Link to Reproduction

https://

### Steps to reproduce

This is my configuration 

```tsx
import { preset } from '@pandacss/preset-panda'
export default defineConfig({
  presets: [preset],
  theme: { extend: { tokens: { fonts: { sans: value: ['"Inter var"'] ...
})
```

The result is as follows
```tsx
--fonts-sans: ui-sans-serif, system-ui, -apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, "Helvetica Neue", Arial, "Noto Sans", sans-serif, "Apple Color Emoji", "Segoe UI Emoji", "Segoe UI Symbol", "Noto Color Emoji", 
"Inter var";
```

### JS Framework

qwik ts

### Panda CSS Version

0.3.2

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @FlatMapIO,

Please consider overriding the entire font of sans by replacing it with a string, or updating the preset as needed.

In the future, we'll consider improving the array merging strategy.
