### ISSUE TITLE
Does not integrate with meteor build system

### ISSUE THREAD

**Issue by Grubba27** [chakra-ui/panda#793]
### Description

While doing the [getting started](https://panda-css.com/docs/getting-started/postcss) integration with [Meteor](https://github.com/meteor/meteor),I got the following  error:
![Screenshot 2023-06-22 at 00 16 43](https://github.com/chakra-ui/panda/assets/70247653/74581270-c6dd-4e82-91a7-e0162acae1c8)

<details>
<summary>Error trace</summary>

```bash
=> Errors prevented startup:                  
   
   While minifying app stylesheet:
   app/styled-system/chunks/imports__ui__App.css: While loading postcss config:
   Loading PostCSS Plugin failed: Unexpected token '||='
   
   (@/Users/grubba/Desktop/work/meteor/tests/panda/postcss.config.cjs)
```
</details>

I was expecting to be displayed a H1 with red bg:

```jsx
import React from "react";
import { css } from "/styled-system/css";
export const App = () => (
  <div>
    <h1 className={css({
      bg: 'red.400'
    })}>Welcome to Meteor!</h1>
  </div>
);

```

### Link to Reproduction

https://github.com/Grubba27/panda

### Steps to reproduce

1. Make sure to have Meteor CLI [installed](https://docs.meteor.com/install.html)
2. Create a new app with `meteor create app --typescript`
3. Follow getting started from [docs](https://panda-css.com/docs) 
4. run your meteor app
5. See error

or, you can:

1. Git Clone this [repo](https://github.com/Grubba27/panda)
2. Having Meteor [installed](https://docs.meteor.com/install.html) in your machine
3. Run `meteor npm start`
4. See error in console while building

### JS Framework

MeteorJS

### Panda CSS Version

0.4.0

### Browser

Chromium Engine Version 114.0.5735.133 (Arc 0.108.1)

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

I would ask where I could start to look to help solve this issue. But I'm unsure where to start. This issue can be related to how the meteor build system work as well.

**Comment by astahmer** [comment]
hey, it seems to be a module resolution with Meteor
I could fix it locally by adding this to the `panda.config.ts`:

```ts
outExtension: "js"
```

so that the files in the `styled-system` folder will have `.js` extension instead of `.mjs`

**Comment by Grubba27** [comment]
I think I did something wrong 😢 

my config as it follows:

```js
{
  outExtension: "js",
  preflight: true,
  include: ['./imports/ui/**/*.{ts,tsx,js,jsx}', './client/**/*.{ts,tsx,js,jsx}', ],
  exclude: [],
  outdir: 'styled-system'
}
```

but now I'm getting the error like this:
<details>
<summary>
Trace
</summary>

```bash

While minifying app stylesheet:
   app/styled-system/chunks/imports__ui__App.css: While loading postcss config:
   Unexpected token '||='
   
   While minifying app stylesheet:
   app/styled-system/chunks/imports__ui__App.css: While loading postcss config: While
   loading postcss config: Unexpected token '||='

```

</details>

**Comment by henriquealbert** [comment]
@astahmer, it works, but the styles do not apply. Any clue what might be happening?
https://github.com/henriquealbert/meteor-with-panda-css
![Screenshot 2023-06-22 at 11 36 04](https://github.com/chakra-ui/panda/assets/59376543/5559da74-2fb5-462e-aba4-aec34de1237a)

**Comment by astahmer** [comment]
@henriquealbert I don't see an import to the styles built with the CLI in your repo : 
`import "/styled-system/styles.css";`

**Comment by abrahamhurtado** [comment]
@Grubba27 what `node` version you're using? I got this same error today and fixed by upgrading above v15.

The Logical OR assignment `||=` is available from node 15 onwards: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Logical_OR_assignment

**Comment by Grubba27** [comment]
Hey! Meteor, by default in the newest version, uses a node v14([we are working to be compatible with newer versions](https://github.com/meteor/meteor/discussions/11505)). This might be the reason why it does not work with it today.
