### ISSUE TITLE
Cant install extension: Version specified in engines.vscode (*) is not specific enough.

### ISSUE THREAD

**Issue by MichaelPriebe** [chakra-ui/panda#802]
### Description

When I try to install the Panda CSS extension in VSCode I get:

```
Version specified in engines.vscode (*) is not specific enough. For vscode versions before 1.0.0, please define at a minimum the major and minor desired version. E.g. ^0.10.0, 0.10.x, 0.11.0, etc.
```

### Link to Reproduction

https://marketplace.visualstudio.com/items?itemName=chakra-ui.panda-css-vscode

### Steps to reproduce

1. Go to: https://marketplace.visualstudio.com/items?itemName=chakra-ui.panda-css-vscode
2. Install Pre-Release Version (Release was not available at this time.)
3. Error.

### Panda CSS Version

N/A

### Browser

VSCode

### Operating System

- [ ] macOS
- [X] Windows
- [ ] Linux

**Comment by anubra266** [comment]
The extension is still under development.
