### ISSUE TITLE
Support CSS SVG properties

### ISSUE THREAD

**Issue by lucgagan** [chakra-ui/panda#809]
### Description

Properties like strokeLinecap, strokeWidth, and strokeOpacity are currently giving errors.

### Problem Statement/Justification

N/A

### Proposed Solution or API

N/A

**Comment by anubra266** [comment]
Hi, @lucgagan you haven't specified any errors, code giving error or an online reproduction. We can't help without any of that information.

**Comment by lucgagan** [comment]
They are just not recognized properties. TypeScript is giving an error that property is not valid. Not clear what else to provide here.
