### ISSUE TITLE
recipes are not working

### ISSUE THREAD

**Issue by omarkhatibco** [chakra-ui/panda#814]
### Description

Hello, 

So I was trying the recipes functionalty and noticed that it's not working, I tried the example [here on the home page](https://panda-css.com/docs/concepts/recipes#defining-recipe).

so the classes are generated but the css is not, I even tried to build the app and checked the generated css file.

I tried both extending theme with recipes and without.

I also tried both `v0.3.2` and `v0.4.0`

### Link to Reproduction

https://codesandbox.io/p/github/omarkhatibco/pandacss-test/main?layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj3g2y4k000b3b6nca8rhglx%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clj3g2y4k000d3b6npw8t91vd%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clj3g2y4k000b3b6nca8rhglx%2522%253A%257B%2522id%2522%253A%2522clj3g2y4k000b3b6nca8rhglx%2522%252C%2522activeTabId%2522%253A%2522cljata9m400gc3b6n26dfc20h%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clj3g2y4k000a3b6ne53qyvb8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Ftsconfig.node.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522id%2522%253A%2522clj68o72000613b6oi5qawc4e%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clj7ma6l000603b6nvsblxl9s%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TERMINAL%2522%252C%2522shellId%2522%253A%2522clj7ma6u7005cfwgn8ts8gj5d%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fstyled-system%252Frecipes%252Fbutton-recipe.mjs%2522%252C%2522id%2522%253A%2522cljata9m400gc3b6n26dfc20h%2522%252C%2522mode%2522%253A%2522temporary%2522%257D%255D%257D%252C%2522clj3g2y4k000d3b6npw8t91vd%2522%253A%257B%2522id%2522%253A%2522clj3g2y4k000d3b6npw8t91vd%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522id%2522%253A%2522clj3g527g00h73b6nc0l440p1%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A5173%252C%2522id%2522%253A%2522clj3g55w900na3b6n5jyzb1zg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clj3g55w900na3b6n5jyzb1zg%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D

### Steps to reproduce

Check the button component on the page and on the preview.

### JS Framework

React (TS)

### Panda CSS Version

0.4.0

### Browser

Latest

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hey @omarkhatibco,

I went around in circles trying to figure out why it didn't work because the website uses recipes, and it worked there 😅.

It boils down to the key used in the recipe here 
![CleanShot 2023-06-25 at 18 25 00@2x](https://github.com/chakra-ui/panda/assets/6916170/f135886d-8ecd-44d4-8610-1f099f4b156e)

What you currently have is this:

```js
export const recipes = {
  buttonRecipe,
};
```

instead of

```js
export const recipes = {
  button: buttonRecipe,
};
```

I've also used the `extend` key for the theme to pull in the default spacing tokens.

https://codesandbox.io/p/github/omarkhatibco/pandacss-test/csb-l9pfj2/draft/peaceful-heisenberg?file=/recipes.ts:30,1-32,3

**Comment by omarkhatibco** [comment]
Thanks @segunadebayo,

is it because of the `Recipe` in the key?

**Comment by segunadebayo** [comment]
@omarkhatibco, yes.

The recipe "key" should match the "name" in the recipe.
