### ISSUE TITLE
Css lineClamp generates pixel instead of number

### ISSUE THREAD

**Issue by minhchu** [chakra-ui/panda#818]
### Description

When I use `lineClamp`:
```tsx
<h3 className={css({ lineClamp: 1 })}>
  This line should be truncated to 1 line only
</h3>
```
panda generates the following css:
```css
-webkit-line-clamp: 1px;
```

it should be:

```css
-webkit-line-clamp: 1;
```

### Link to Reproduction

https://stackblitz.com/edit/stackblitz-starters-jcaasa?file=pages%2Findex.js

### Steps to reproduce

Open the above stackblitz link, then inspect the text elements

### JS Framework

NextJS / Typescript

### Panda CSS Version

0.4.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by segunadebayo** [comment]
Good catch @minhchu!

I just pushed a fix for this. We'll release an update shortly.

If the issue persists after upgrading, I'll re-open it.
