### ISSUE TITLE
Broken Link in Sidebar Leading to 404 Error

### ISSUE THREAD

**Issue by sakimyto** [chakra-ui/panda#839]
### Subject

Design System

### Description

Hello maintainers,

First and foremost, I want to extend my gratitude for the hard work that has been put into this project. It is really a great resource.

I have noticed an issue that I would like to bring to your attention. While it might be a minor thing, I thought it's worth reporting. In the sidebar of the documentation, there is a link which seems to be broken as it leads to a 404 page not found error.

Location: Sidebar > Guides > Design System
Link: https://panda-css.com/docs/guides/design-system

Please let me know if you need any further information or if there is anything I can do to assist in resolving this issue.

Thank you once again for your dedication to this project.

Best regards

**Comment by segunadebayo** [comment]
Thanks for bringing this up @sakimyto.

It is now fixed!
