### ISSUE TITLE
Cannot read properties of undefined (reading 'replace')

### ISSUE THREAD

**Issue by Temzasse** [chakra-ui/panda#855]
### Description

I'm trying to setup Panda CSS in our company's project template that is using Vite and when I start the dev server after generating the styled system I get a lot of `Cannot read properties of undefined (reading 'replace')` errors to the terminal and the styles don't seem to be applied for elements that use the `css()` helper (see `/routes/login/index.tsx`).

### Link to Reproduction

https://github.com/TaitoUnited/full-stack-template/tree/panda-css/client

### Steps to reproduce

1. Go to `/client` folder
2. `npm install`
3. `npm run styled-system:codegen`
4. `npm start`
5. See error `Cannot read properties of undefined (reading 'replace')`
6. Open app in browser (should open the login page)
7. No styles are applied when using `css()` helper from Panda

### JS Framework

React (TS)

### Panda CSS Version

0.5.0

### Browser

Google Chrome 114

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

### Additional Information

This is how it looks like when the dev server is started:

<img width="624" alt="Screenshot 2023-06-28 at 13 26 54" src="https://github.com/chakra-ui/panda/assets/6152032/de4fb95a-edf9-4674-a419-0751d8188247">

I tried to debug the problem with vscode's npm script debugger by running `panda debug` and was able to narrow the error to this [line](https://github.com/chakra-ui/panda/blob/509103fc40679aae607f3bbf8f9d03adeb8a1f21/packages/shared/src/astish.ts#L5).

<img width="1118" alt="Screenshot 2023-06-28 at 13 12 42" src="https://github.com/chakra-ui/panda/assets/6152032/70b152fe-cb26-4906-8793-87afa82a89fa">

So for some reason the `val` arg is `undefined`. I have no idea why this error is happening and I wasn't able to reproduce it with a clean and minimal Vite project.

The current setup for Panda in the repro might differ a bit from the docs (I have the postcss plugin applied in `vite.config.js` instead of having a separate postcss config) since I was testing different things. However I got the same error with the exact same setup that the docs suggest.

**Comment by mleralec** [comment]
:wave:
Same issue on my side, I rollback `@pandacss/dev` from `0.5.0` to `0.4.0` and it seems to work 🤷🏻‍♂️
