### ISSUE TITLE
staticCss failing with `<css input>:33:21: Missed semicolon` on a base setup

### ISSUE THREAD

**Issue by rafaelchiti** [chakra-ui/panda#858]
### Description

I get an error trying to use 'staticCss' config, on a base/clean setup.

### Link to Reproduction

https://github.com/rafaelchiti/pandarepo-fork

### Steps to reproduce

I linked a fork of the example repo https://github.com/olafurns7/pandarepo where I simply added a staticCss config.
In that fork if you run `pnpm i` on the `root` and then `pnpm panda codegen` (inside `packages/styled-ui`). The error will show up.

But this also happens on a simple setup f.i. following https://panda-css.com/docs/getting-started/storybook 
And then I add config for the 'staticCss' prop in the panda config. Like this:

```
import { defineConfig } from "@pandacss/dev";
export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: ["./src/**/*.{js,jsx,ts,tsx}"],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {},
  },

  staticCss: {
    css: [
      {
        properties: {
          margin: ["*"],
          padding: ["*", "50px", "80px"],
        },
        responsive: true,
      },
      {
        properties: {
          color: ["*"],
          backgroundColor: ["green.200", "red.400"],
        },
        conditions: ["light", "dark"],
      },
    ],
  },

  // The output directory for your css system
  outdir: "styled-system",
  emitPackage: true,
  jsxFramework: "react",
});
````

When I run `pnpm panda codegen` I get the error:
```
<css input>:33:21: Missed semicolon
 ELIFECYCLE  Command failed with exit code 1.
```

### JS Framework

React TS

### Panda CSS Version

0.4.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by Ding-Fan** [comment]
I ran into this error again, then I 

- replace my `"[data-state-checked=true] &"` with [group selectors](https://panda-css.com/docs/concepts/conditional-styles#group-selectors)
- delete `styled-system` and generate it with `yarn`

the error is gone
