### ISSUE TITLE
recipe not applying styles

### ISSUE THREAD

**Issue by FilipePfluck** [chakra-ui/panda#861]
### Description

I'm creating a recipe like this

export const dropdownItemCheckedIndicatorRecipe = defineRecipe({
  name: 'dropdownItemCheckedIndicator',
  base: {
    position: 'absolute!',
    left: '0px!',
  },
  jsx: [
    'DropdownItemCheckedIndicator',
    'DropdownRadioItem',
    'DropdownCheckboxItem',
  ],
})

adding it to panda.config correctly, just like my other recipes, and then using it like this:

export const DropdownItemCheckedIndicator = styled(
  DropdownMenu.ItemIndicator,
  dropdownItemCheckedIndicator,
)

The name of the component is the same as the recipe name (only capitalized, of course), and I've been looking into this for hours and it seems identycal to my other recipes. Yet, this one does not work for some reason. 

Here is my repo: 
https://github.com/FilipePfluck/my-components

this issue is on those files: 
src/components/Dropdowns/Dropdown/styles.ts
src/components/Dropdowns/components/parts.ts

### Link to Reproduction

src/components/Dropdowns/Dropdown/styles.ts

### Steps to reproduce

clone the repo
run storybook
go to dropdowns/radixExampleDropdown story
check one of the options on the dropdown
see that the indicator is not absolutely positioned as written in the recipe

### JS Framework

React (TS)

### Panda CSS Version

0.4.0

### Operating System

- [ ] macOS
- [ ] Windows
- [X] Linux

**Comment by astahmer** [comment]
fixed by https://github.com/chakra-ui/panda/pull/879
