### ISSUE TITLE
Component Library usecase: Ship the build info file - Recipes not included in app

### ISSUE THREAD

**Issue by paulm17** [chakra-ui/panda#869]
### Description

My use case is a component library.  I'm using turborepo as the monorepo with pnpm.

With the package:

panda.config.ts

```
import { defineConfig } from '@pandacss/dev';
import { badgeRoot, badgeLabel, badgeSection } from './src/components/Badge/badge.recipe'

export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: ['./src/components/**/*.{ts,tsx}'],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {
      recipes: {
        badgeRoot: badgeRoot,
        badgeLabel: badgeLabel,
        badgeSection: badgeSection
      }      
    }
  },

  // The output directory for your css system
  outdir: '@raikou/styled-system',
  emitPackage: true,
  jsxFramework: 'react',
});
```

When I run codegen...

```
paul@Pauls-MacBook-Pro raikou-core % pnpm panda codegen

> @raikou/core@0.0.12 panda /Users/paul/development/src/github/raikou/packages/raikou-core
> panda codegen "codegen"

✔️ `@raikou/styled-system/css`: the css function to author styles
✔️ `@raikou/styled-system/tokens`: the css variables and js function to query your tokens
✔️ `@raikou/styled-system/patterns`: functions to implement apply common layout patterns
✔️ `@raikou/styled-system/recipes`: functions to create multi-variant styles
✔️ `@raikou/styled-system/jsx`: style prop powered elements for react
```

I then build and ship:

```
"scripts": {
    "build": "tsup src/index.ts --format esm,cjs --clean --external @raikou/styled-system && pnpm ship",
    "panda": "panda codegen",
    "ship": "panda ship --outfile dist/panda.buildinfo.json" 
```

With the app:

panda.config.ts:

```
import { defineConfig } from '@pandacss/dev';

export default defineConfig({
  // Whether to use css reset
  preflight: true,

  // Where to look for your css declarations
  include: [
    './node_modules/@raikou/core/dist/panda.buildinfo.json',
    './app/**/*.{ts,tsx}'
  ],

  // Files to exclude
  exclude: [],

  // Useful for theme customization
  theme: {
    extend: {}
  },

  // The output directory for your css system
  outdir: '@raikou/styled-system',
  emitPackage: true,
  jsxFramework: 'react',
});
```

I run codegen:

```
paul@Pauls-MacBook-Pro web % pnpm panda codegen

> web@1.0.0 panda /Users/paul/development/src/github/raikou/apps/web
> panda codegen "codegen"

✔️ `@raikou/styled-system/css`: the css function to author styles
✔️ `@raikou/styled-system/tokens`: the css variables and js function to query your tokens
✔️ `@raikou/styled-system/patterns`: functions to implement apply common layout patterns
✔️ `@raikou/styled-system/jsx`: style prop powered elements for react
```

No recipes...  any components which use a recipe are not styled.

### Link to Reproduction

https://github.com/paulm17/raikou

### Steps to reproduce

Hopefully I have outlined this in the op.

### Panda CSS Version

0.5.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by astahmer** [comment]
here you go
https://github.com/paulm17/raikou/pull/1/files

**Comment by paulm17** [comment]
Hi Alex,

Thank you for taking at look at this issue.

Unfortunately.  This does not solve the use case.  Which is my fault, as I should have been more clearer and I apologise for that.

I have two use cases:

1) The storybook which is in apps/docs.

The first use case is getting storybook to work with panda.buildinfo.json.  This has the same issue that recipes are not found.

2) A website which imports the component library through yarn.

I was using apps/web, as this use case.  I see you have used the "Ship the src files" method and this isn't my use case.  It should simulate a yarn install therefore panda.buildinfo.json needs to be used.

---

The use case here, is that the user importing the component library into their application does not know about the internals.  Therefore they wouldn't be importing any recipes as they wouldn't have the documentation to do so.

The only item that should be included is the panda.buildinfo.json and this should contain all the relevant detail.  Also, how the component library is built right now, does not expose any of the source files.

Please let me know if I can explain anything more in detail.

Thanks

**Comment by paulm17** [comment]
I also applied the PR to include the badge changes you made.  But you can revert the change to panda.config.

**Comment by paulm17** [comment]
Closing this for now.  If need be.  I'll re-open it if I have any other issues.
