### ISSUE TITLE
Writing styles using Object Property Shorthand does not work

### ISSUE THREAD

**Issue by RyoheiTomiyama** [chakra-ui/panda#870]
### Description

I write styles using object property shorthand, but it's style is not working

### Link to Reproduction

https://play.panda-css.com/EDdN1qV7WC

### Steps to reproduce

Please show https://play.panda-css.com/EDdN1qV7WC .

this is working.

```js
const width = '300px';
css({
    width: width,
})
```

but, this is not working.
```js
const height = '100px';
css({
    height,
})
```

### Panda CSS Version

0.5.0

### Browser

Chrome

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
Hi @RyoheiTomiyama css panda works by static extraction. No runtime. We don't encourage this method.
https://panda-css.com/docs/guides/dynamic-styling

**Comment by RyoheiTomiyama** [comment]
@anubra266 Thanks for your reply.

But, I think i can write it. 
Like [this document](https://panda-css.com/docs/guides/dynamic-styling#referenced-values).

![スクリーンショット 2023-06-30 8 30 31](https://github.com/chakra-ui/panda/assets/10805686/f4464cfd-1a70-4509-aa69-1fde0184d61d)

If  use Object Property Shorthand, it not work.


Is `height` not a static variable?

```js
const height = '100px';
css({
    height,
})
```

I don't know, Object that write longhand is working, but shorthand one is not working.
