### ISSUE TITLE
Docs: mention of spacing / spacings

### ISSUE THREAD

**Issue by grbd** [chakra-ui/panda#894]
### Subject

docs typo

### Description

Within https://panda-css.com/docs/theming/tokens
It mentions the token key is "spacings"
Within https://panda-css.com/docs/customization/theme#spacing
It mentions the token key is "spacing"

Currently it's "spacing" in code
This might just be a minor typo in the docs
but I wasn't sure if the config property needs renaming to "spacings" to be inline with all the other props such as "colors"

Also I noticed breakpoints was mentioned in docs/customization/theme but not docs/theming/tokens
Not sure if that needs adding in

**Comment by anubra266** [comment]
@grbd
-  the correct syntax is `spacing` you can open a PR
- `breakpoints` are not tokens.

**Comment by grbd** [comment]
Ok sorry, I think for breakpoints vscode didn't complain when it was in the wrong place which confused me a bit with that one.
Might be just the way the types are setup
```ts
  theme: {
    extend: {
      // Correct place for breakpoints
      breakpoints: {},
      tokens: {
        // This shows up in the vscode auto complete for some reason, doesn't error
        breakpoints: {}
      },
      semanticTokens: {
        // This shows up in the vscode auto complete for some reason, doesn't error
        breakpoints: {},
      }
    }
  },
```
