### ISSUE TITLE
Changes to tokens in other file are not reflected (Next, Vite)

### ISSUE THREAD

**Issue by RDeluxe** [chakra-ui/panda#906]
### Description

Hello,

Using Next13 with pages. I created a file that exports my tokens. 
Update to this file are not reflected on my site : if I change a colour I have to restart the app to see the changes. 

However if I change the panda.config.ts file directly, everything works as intended. 

### Link to Reproduction

https://stackblitz.com/edit/panda-next-repro-tokens?file=tokens.ts

### Steps to reproduce

1. Run the app
2. Change colour in token.ts - it won’t work
3. Restart app, changes are shown
4. Try doing the same thing by putting the colour token in panda.config.ts directly 

### JS Framework

Next TS

### Panda CSS Version

0.5.0

### Browser

Edge

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by RDeluxe** [comment]
I first asked on this issue but I don’t think it’s the same problem, as modifying panda.config.ts does work. 

https://github.com/chakra-ui/panda/issues/797

**Comment by RDeluxe** [comment]
I reproed with React + Vite [here](https://stackblitz.com/edit/vitejs-vite-izbks9?file=colorTokens.ts)

Again, if you change the color in `panda.config.ts` you will see the changes right away. If you change the color in `tokenColors.ts` you won't see your changes (until you restart the server or if you change `panda.config.ts`)

**Comment by astahmer** [comment]
thanks for the minimal repro ! this should be fixed [here](https://github.com/chakra-ui/panda/pull/910)

**Comment by RDeluxe** [comment]
Awesome, thank you 🙏
