### ISSUE TITLE
Nested Conditional for Presets

### ISSUE THREAD

**Issue by grbd** [chakra-ui/panda#907]
### Description

One of the ideas I had was to try and create a bunch of presets / themes
similar to the ones used in daisyui - https://daisyui.com/docs/themes/

Looking here:
https://panda-css.com/docs/guides/multiple-themes
https://panda-css.com/docs/customization/presets

I think its possible via something like:
```ts
const preset1 = definePreset({
  conditions: {
    extend: {
      pinkTheme: '[data-theme=pink] &',
    },
  },
  theme: {
    semanticTokens: {
      colors: {
        rose: {
          50: { value: {_pinkTheme: "#fff1f2"} },
          800: { value: {_pinkTheme: "#9f2233"} },
        },
      },
    },
  }
})
```

### Problem Statement/Justification

Currently I think it's only possible to use conditionals within semanticTokens and not tokens.
Maybe thats by design I'm not sure.
Adding in nested conditionals on semanticTokens at least might make it easier when writing multiple presets using different data-theme's

### Proposed Solution or API

what would be nicer is if you could avoid naming the conditional on every property
```ts
const preset1 = definePreset({
  conditions: {
    extend: {
      pinkTheme: '[data-theme=pink] &',
    },
  },
  theme: {
    _pinkTheme: {
      semanticTokens: {
        colors: {
          rose: {
            50: { value: "#fff1f2"},
            800: { value: "#9f2233"},
          },
        },
      },
    }
  }
})
```

**Comment by anubra266** [comment]
@grbd panda follows the [W3C Token Format](https://tr.designtokens.org/format/).
Every part of the config has their individual role, and tokens should not be conditional.
If you want multiple themes, we provide a guide for that.
https://panda-css.com/docs/guides/multiple-themes

**Comment by grbd** [comment]
Yeah I know I posted the same link above
In order to select different themes via data-theme you need conditionals
Currently it's possible to apply conditionals to semanticTokens (not tokens) but you have to do it for every prop individually

It's not that big of an issue since I can code around it, but it would have been a nice to have

**Comment by anubra266** [comment]
@grbd could you give an example syntax code of how you'd love it to work

**Comment by grbd** [comment]
Maybe something like this
```ts
const preset1 = definePreset({
  conditions: {
    extend: {
      pinkTheme: '[data-theme=pink] &',
    },
  },
  theme: {
    semanticTokens: {
      _pinkTheme: {
        colors: {
          rose: {
            50: { value: "#fff1f2"},
            800: { value: "#9f2233"},
          },
        },
      },
    }
  }
})
```

**Comment by anubra266** [comment]
@grbd how would you like to consume this in the code?

**Comment by anubra266** [comment]
@grbd I'm not sure I see what advantage this has over this:
![CleanShot 2023-07-02 at 14 00 07@2x](https://github.com/chakra-ui/panda/assets/30869823/8a93782e-20eb-4c75-97c5-b70a5e9b720a)

**Comment by grbd** [comment]
To try and explain what I'm trying to do
1. start off with an object that has a set number of default values for a theme
2. add to that some custom properties such as primary colors
3. then run a function(s) that adds in some secondary colors if they're missing calculated from the primary ones above
4. repeat multiple times for multiple themes under different names.

I'm not sure if this is a common design patttern since I'm not that familiar with design tokens myself
Similar to what's happening here
https://github.com/saadeghi/daisyui/blob/master/src/theming/themes.js
https://github.com/saadeghi/daisyui/blob/master/src/theming/functions.js#L73

Keeping the theme name on every prop just means I'll have to write some additional code to translate from one object to another is all.
I wasn't sure if this was something others might find useful
