### ISSUE TITLE
Not able to use booleans or primitives when extending css properties in panda.config.

### ISSUE THREAD

**Issue by 55Cancri** [chakra-ui/panda#908]
### Description

I like to create a Grid component and use like this:

```typescript 
 <Grid mb="15vh" alignC justifyC>
  //
</Grid>
```
Where alignC and justifyC are shorthands for alignContent and justifyContent. In stitches, I would be able to map `true` to `"center"` or `"100%"`, but it doesn't seem I can do that in panda config. In the config, the closet I could do was a mapped value:

```typescript
  utilities: {
    extend: {
      alignContent: {
        shorthand: "alignC",
        property: "alignContent",
        values: {
          true: "center",
        },
        transform(value) {
          return { alignContent: value === true ? "center" : value };
        },
      },
  // ...
}
```
However, true is mapped to a string here and I have use this prop like `alignC="true"` instead of `alignC`.

### Link to Reproduction

na

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React (TS)

### Panda CSS Version

^0.5.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
```ts
const config = {
  utilities: {
    extend: {
      alignContent: {
        shorthand: "alignC",
        property: "alignContent",
        values: { type: "boolean" },
        transform(value) {
          if (!value) return {};
          return { alignContent: "center" };
        },
      },
    },
  },
};
```
