### ISSUE TITLE
No way to apply arbitrary type to custom props in panda.config

### ISSUE THREAD

**Issue by 55Cancri** [chakra-ui/panda#914]
### Description

Suppose I have a custom grid component wrapped in a framer motion `MotionConfig` component:

```typescript
import { MotionConfig } from "framer-motion";

const Base = styled(motion.div, {
  base: {
    display: "grid",
  },
});

const Grid = React.forwardRef<HTMLDivElement, GridProps>((props, ref) => {
  const { children, config, ...rest } = props;
  return (
    <MotionConfig transition={config}>
      <Base ref={ref} {...rest}>
        {children}
      </Base>
    </MotionConfig>
  );
});

Grid.displayName = "Grid";

export default Grid;
```

I want all of my custom elements to be capable of receiving a config prop of type `Transition`, which comes from the framer motion package. It is not possible to define this property and type in the panda.config file:

```typescript
import type { Transition } from "framer-motion";

export default defineConfig({
  utilities: {
    extend: {
      config: {
        values: { type: Transition }, // <-- doesn't work, expected value received type
        transform(value) {
          return { config: value };
        },
      },
})
```

### Link to Reproduction

na

### Steps to reproduce

2. Click on '...'
3. Scroll down to '...'

### JS Framework

React (TS)

### Panda CSS Version

^0.5.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by anubra266** [comment]
@55Cancri I'm not sure what you're trying to do, but it doesn't work this way. Besides you're assigning a type to a value

**Comment by 55Cancri** [comment]
> @55Cancri I'm not sure what you're trying to do, but it doesn't work this way. Besides you're assigning a type to a value

In the end, I will be able to use my grid component and define framer motion values:

```typescript
<Grid
   w={120} // <-- panda props
   bg="red.900" // <-- panda props
   config={  <-- my prop defined generally for all panda components
      duration: 0.14 // <-- define how components animate
   }
>
  stuff here
</Grid>

**Comment by anubra266** [comment]
@55Cancri that's outside the scope of panda, we're only handling styling. You should wrap the component with something else to handle framer motion.
