### ISSUE TITLE
Invalid utility class generated when using grid container

### ISSUE THREAD

**Issue by swallowtail62** [chakra-ui/panda#959]
### Description

First of all, thanks for providing us with a great library.

I found that when using panda css to style the grid container, an incorrect utility class is generated. It seems to happen when using multiple `gridTemplateColumns` or `gridTemplateColumns` for example.

If write the following code

```ts
export default function Home() {
  return (
    <div
      className={css({
        minH: "100vh",
        display: "grid",
        gridTemplateRows: "auto 1fr",
      })}
    >
      <header className={css({ bgColor: "gray.100", h: 12 })}>
        some header
      </header>
      <div
        className={css({ display: "grid", gridTemplateColumns: "auto 1fr" })}
      >
        <aside className={css({ w: 80, bgColor: "blue.100" })}>
          sidebar navigation
        </aside>
        <div className={css({ fontSize: "2xl", fontWeight: "bold" })}>
          Hello 🐼!
        </div>
      </div>
    </div>
  );
}
```

Unexpected `grid-template-columns: auto 1fr` style applied to root div tag.

![image](https://github.com/chakra-ui/panda/assets/45661101/21d6b44e-6068-48b4-9ab1-f0b7bf3392e8)

If I write the same code using the style attribute,

```ts
export default function Home() {
  return (
    <div
      style={{
        minHeight: "100vh",
        display: "grid",
        gridTemplateRows: "auto 1fr",
      }}
    >
      <header style={{ backgroundColor: "gray", height: "48px" }}>
        some header
      </header>
      <div style={{ display: "grid", gridTemplateColumns: "auto 1fr" }}>
        <aside style={{ width: "320px", backgroundColor: "skyblue" }}>
          sidebar navigation
        </aside>
        <div style={{ fontSize: "2xl", fontWeight: "bold" }}>Hello 🐼!</div>
      </div>
    </div>
  );
}
```

I get the following, as expected.

![image](https://github.com/chakra-ui/panda/assets/45661101/4ed194c5-ad58-4406-9164-ba450fdbf3f7)

Maybe a similar issue could happen with something other than grid properties, but is there a good workaround for this? For now I'm trying to get away with using flex container in preference.

### Link to Reproduction

https://stackblitz.com/edit/nextjs-pandacss-issue-repro?file=src%2Fapp%2Fpage.tsx

### Steps to reproduce

1. Go to the stackblitz page
2. See preview

### JS Framework

React (TS)

### Panda CSS Version

0.5.1

### Browser

*

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
Hi @swallowtail62,

This has been fixed in a recent commit.

<img width="1511" alt="CleanShot 2023-07-06 at 12 38 07@2x" src="https://github.com/chakra-ui/panda/assets/6916170/2e9f675d-5302-4bbe-800e-7953005f4d2f">

We'll release an update shortly.
