### ISSUE TITLE
using the `token()` function to retrieve tokens in compound styles doesn't work for `css()` or JSX components

### ISSUE THREAD

**Issue by mayteio** [chakra-ui/panda#999]
### Description

When I use css or JSX elements and use the `token()` function [in composite values as the docs describe](https://panda-css.com/docs/theming/usage#composite-values) to reference semantic tokens, I expect it to use the token correctly. but instead it doesn't:

<img width="994" alt="Screenshot 2023-07-10 at 7 31 05 am" src="https://github.com/chakra-ui/panda/assets/43975092/b244f5e5-4a1b-464c-a639-228e8bd7c932">

<img width="975" alt="Screenshot 2023-07-10 at 7 31 54 am" src="https://github.com/chakra-ui/panda/assets/43975092/f09bec5c-c229-45ee-88d4-9f088161cfa6">

<img width="969" alt="Screenshot 2023-07-10 at 7 36 05 am" src="https://github.com/chakra-ui/panda/assets/43975092/b22ca0bd-6227-4320-a96f-089a88921eec">

<img width="964" alt="Screenshot 2023-07-10 at 7 45 37 am" src="https://github.com/chakra-ui/panda/assets/43975092/3b3b7798-477b-45d2-91f7-d01f2587cc03">

### Link to Reproduction

[Code sandbox reproduction](https://codesandbox.io/p/github/mayteio/panda-next-storybook/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljvy0vm2000b3b6nk4x7it5m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljvy0vm2000d3b6nk6tdt1hf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.997562224344136%252C55.002437775655864%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljvy0vm2000b3b6nk4x7it5m%2522%253A%257B%2522id%2522%253A%2522cljvy0vm2000b3b6nk4x7it5m%2522%252C%2522activeTabId%2522%253A%2522cljvy5u8g01wp3b6np0o3wak8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljvy0vm1000a3b6n674l36ia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cljvy1s0u00hc3b6ni3th0hr6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522cljvy5u8g01wp3b6np0o3wak8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljvy0vm2000d3b6nk6tdt1hf%2522%253A%257B%2522id%2522%253A%2522cljvy0vm2000d3b6nk6tdt1hf%2522%252C%2522activeTabId%2522%253A%2522cljvy3m3m01hj3b6ndvqlmolm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljvy0vm2000c3b6nemyly30v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cljvy2ouz00qe3b6n5so6sph8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Run%2520app%2522%252C%2522id%2522%253A%2522cljvy2qmc00u43b6nmdx7ec6a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cljvy322w013k3b6nwkd6ovxi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Run%2520storybook%2522%257D%252C%257B%2522id%2522%253A%2522cljvy3gur01cu3b6ntaq1bdjg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522Run%2520app%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522cljvy3m3m01hj3b6ndvqlmolm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A6006%252C%2522taskId%2522%253A%2522Run%2520storybook%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fstory%252Fapp-page--primary%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

### Steps to reproduce

1. [Visit codesandbox](https://codesandbox.io/p/github/mayteio/panda-next-storybook/main?layout=%257B%2522sidebarPanel%2522%253A%2522GIT%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljvy0vm2000b3b6nk4x7it5m%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522cljvy0vm2000d3b6nk6tdt1hf%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B44.997562224344136%252C55.002437775655864%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522cljvy0vm2000b3b6nk4x7it5m%2522%253A%257B%2522id%2522%253A%2522cljvy0vm2000b3b6nk4x7it5m%2522%252C%2522activeTabId%2522%253A%2522cljvy5u8g01wp3b6np0o3wak8%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljvy0vm1000a3b6n674l36ia%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252FREADME.md%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252F.codesandbox%252Ftasks.json%2522%252C%2522id%2522%253A%2522cljvy1s0u00hc3b6ni3th0hr6%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522type%2522%253A%2522FILE%2522%252C%2522filepath%2522%253A%2522%252Fapp%252Fpage.tsx%2522%252C%2522id%2522%253A%2522cljvy5u8g01wp3b6np0o3wak8%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%257D%252C%2522cljvy0vm2000d3b6nk6tdt1hf%2522%253A%257B%2522id%2522%253A%2522cljvy0vm2000d3b6nk6tdt1hf%2522%252C%2522activeTabId%2522%253A%2522cljvy3m3m01hj3b6ndvqlmolm%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522cljvy0vm2000c3b6nemyly30v%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522PROJECT_SETUP%2522%257D%252C%257B%2522type%2522%253A%2522EMPTY_DEVTOOL%2522%252C%2522id%2522%253A%2522cljvy2ouz00qe3b6n5so6sph8%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Run%2520app%2522%252C%2522id%2522%253A%2522cljvy2qmc00u43b6nmdx7ec6a%2522%252C%2522mode%2522%253A%2522permanent%2522%257D%252C%257B%2522id%2522%253A%2522cljvy322w013k3b6nwkd6ovxi%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522Run%2520storybook%2522%257D%252C%257B%2522id%2522%253A%2522cljvy3gur01cu3b6ntaq1bdjg%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A3000%252C%2522taskId%2522%253A%2522Run%2520app%2522%252C%2522path%2522%253A%2522%252F%2522%257D%252C%257B%2522id%2522%253A%2522cljvy3m3m01hj3b6ndvqlmolm%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522TASK_PORT%2522%252C%2522port%2522%253A6006%252C%2522taskId%2522%253A%2522Run%2520storybook%2522%252C%2522path%2522%253A%2522%252F%253Fpath%253D%252Fstory%252Fapp-page--primary%2522%257D%255D%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)
2. Run either the storybook or dev task
3. Check JSX/css calls in `app/page.tsx`
4. See only passing token-only properties allow tokens to be retrieved

### JS Framework

React (TS), Next.js

### Panda CSS Version

0.6.0

### Operating System

- [X] macOS
- [ ] Windows
- [ ] Linux

**Comment by segunadebayo** [comment]
The token function argument should be an absolute token path. In this case token(colors.light)

**Comment by mayteio** [comment]
Thanks for the tips @segunadebayo! Missed that detail in the docs. cheers.
